# Put document versions here for every major or minor release
# Every TOML list item contains the following properties:
# - "version"   - text that appears in versions menu
# - "dirpath"   - directory name (relative to contentDir) where documentation
#                 for given version resides
# - "url"       - url for link in version menu. May be absolute URL.
# - "latestTag" - docker image tag for the latest patch version. Must be changed
#                 on every patch release of respective branch

[apiReference]
    homepage = "https://sdk.gooddata.com/gooddata-ui-apidocs/"
    versionPage = "https://sdk.gooddata.com/gooddata-ui-apidocs/VERSION/docs/index.html"

[[versions]]
    version = "11.43"
    dirpath = "latest"
    url = "/latest/"
[[versions]]
    dirpath = "11.42"
    url = "/11.42/"
    version = "11.42"
[[versions]]
    dirpath = "11.41"
    url = "/11.41/"
    version = "11.41"
[[versions]]
    dirpath = "11.40"
    url = "/11.40/"
    version = "11.40"
[[versions]]
    dirpath = "11.39"
    url = "/11.39/"
    version = "11.39"
[[versions]]
    dirpath = "11.38"
    url = "/11.38/"
    version = "11.38"
[[versions]]
    dirpath = "11.36"
    url = "/11.36/"
    version = "11.36"
[[versions]]
    dirpath = "11.35"
    url = "/11.35/"
    version = "11.35"
[[versions]]
    dirpath = "11.34"
    url = "/11.34/"
    version = "11.34"
[[versions]]
    dirpath = "11.32"
    url = "/11.32/"
    version = "11.32"
[[versions]]
    dirpath = "11.31"
    url = "/11.31/"
    version = "11.31"
[[versions]]
    dirpath = "11.30"
    url = "/11.30/"
    version = "11.30"
[[versions]]
    dirpath = "11.29"
    url = "/11.29/"
    version = "11.29"
[[versions]]
    dirpath = "11.28"
    url = "/11.28/"
    version = "11.28"
[[versions]]
    dirpath = "11.27"
    url = "/11.27/"
    version = "11.27"
[[versions]]
    dirpath = "11.26"
    url = "/11.26/"
    version = "11.26"
[[versions]]
    dirpath = "11.25"
    url = "/11.25/"
    version = "11.25"
[[versions]]
    dirpath = "11.24"
    url = "/11.24/"
    version = "11.24"
[[versions]]
    dirpath = "11.22"
    url = "/11.22/"
    version = "11.22"
[[versions]]
    dirpath = "11.21"
    url = "/11.21/"
    version = "11.21"
[[versions]]
    dirpath = "11.20"
    url = "/11.20/"
    version = "11.20"
[[versions]]
    dirpath = "11.19"
    url = "/11.19/"
    version = "11.19"
[[versions]]
    dirpath = "11.18"
    url = "/11.18/"
    version = "11.18"
[[versions]]
    dirpath = "11.17"
    url = "/11.17/"
    version = "11.17"
[[versions]]
    changelog = "https://github.com/gooddata/gooddata-react-components/blob/master/CHANGELOG.md#630"
    dirpath = "6.3"
    url = "https://sdk.gooddata.com/gooddata-ui/docs/6.3.0/about_gooddataui.html"
    version = "6.3"
