# Put document versions here for every major or minor release
# Every TOML list item contains the following properties:
# - "version"   - text that appears in versions menu
# - "dirpath"   - directory name (relative to contentDir) where documentation
#                 for given version resides
# - "url"       - url for link in version menu. May be absolute URL.
# - "latestTag" - docker image tag for the latest patch version. Must be changed
#                 on every patch release of respective branch

[apiReference]
    homepage = "https://sdk.gooddata.com/gooddata-ui-apidocs/"
    versionPage = "https://sdk.gooddata.com/gooddata-ui-apidocs/VERSION/docs/index.html"

[[versions]]
    version = "11.28"
    dirpath = "latest"
    url = "/latest/"
[[versions]]
    version = "11.27"
    dirpath = "11.27"
    url = "/11.27/"
[[versions]]
    version = "11.26"
    dirpath = "11.26"
    url = "/11.26/"
[[versions]]
    version = "11.25"
    dirpath = "11.25"
    url = "/11.25/"
[[versions]]
    version = "11.24"
    dirpath = "11.24"
    url = "/11.24/"
[[versions]]
    version = "11.22"
    dirpath = "11.22"
    url = "/11.22/"
[[versions]]
    version = "11.21"
    dirpath = "11.21"
    url = "/11.21/"
[[versions]]
    version = "11.20"
    dirpath = "11.20"
    url = "/11.20/"
[[versions]]
    version = "11.19"
    dirpath = "11.19"
    url = "/11.19/"
[[versions]]
    version = "11.18"
    dirpath = "11.18"
    url = "/11.18/"
[[versions]]
    version = "11.17"
    dirpath = "11.17"
    url = "/11.17/"
[[versions]]
    version = "11.16"
    dirpath = "11.16"
    url = "/11.16/"
[[versions]]
    version = "11.15"
    dirpath = "11.15"
    url = "/11.15/"
[[versions]]
    version = "11.14"
    dirpath = "11.14"
    url = "/11.14/"
[[versions]]
    version = "11.13"
    dirpath = "11.13"
    url = "/11.13/"
[[versions]]
    version = "11.12"
    dirpath = "11.12"
    url = "/11.12/"
[[versions]]
    version = "11.11"
    dirpath = "11.11"
    url = "/11.11/"
[[versions]]
    version = "11.10"
    dirpath = "11.10"
    url = "/11.10/"
[[versions]]
    version = "8.12"
    changelog = "https://github.com/gooddata/gooddata-react-components/blob/master/CHANGELOG.md#8120"
    dirpath = "8.12"
    url = "https://sdk.gooddata.com/gooddata-ui/docs/about_gooddataui.html"
[[versions]]
    version = "6.3"
    changelog = "https://github.com/gooddata/gooddata-react-components/blob/master/CHANGELOG.md#630"
    dirpath = "6.3"
    url = "https://sdk.gooddata.com/gooddata-ui/docs/6.3.0/about_gooddataui.html"
