// (C) 2025-2026 GoodData Corporation

/* oxlint-disable no-barrel-files/no-barrel-files */

// Actions API - Export commonly used ActionsApi functions
export {
    ActionsApi_ManageOrganizationPermissions,
    type ActionsApiManageOrganizationPermissionsRequest,
    ActionsApi_WorkspaceResolveAllSettings,
    type ActionsApiWorkspaceResolveAllSettingsRequest,
    ActionsApi_ResolveAllEntitlements,
    ActionsApi_ResolveAllSettingsWithoutWorkspace,
    ActionsApi_DeleteWorkspaceAutomations,
    type ActionsApiDeleteWorkspaceAutomationsRequest,
    ActionsApi_PauseWorkspaceAutomations,
    type ActionsApiPauseWorkspaceAutomationsRequest,
    ActionsApi_UnpauseWorkspaceAutomations,
    type ActionsApiUnpauseWorkspaceAutomationsRequest,
    ActionsApi_UnsubscribeAutomation,
    type ActionsApiUnsubscribeAutomationRequest,
    ActionsApi_UnsubscribeSelectedWorkspaceAutomations,
    type ActionsApiUnsubscribeSelectedWorkspaceAutomationsRequest,
    ActionsApi_InheritedEntityPrefixes,
    type ActionsApiInheritedEntityPrefixesRequest,
    ActionsApi_MetadataSync,
    type ActionsApiMetadataSyncRequest,
    ActionsApi_ListWorkspaceUsers,
    type ActionsApiListWorkspaceUsersRequest,
    ActionsApi_RegisterUploadNotification,
    type ActionsApiRegisterUploadNotificationRequest,
    ActionsApi_DeleteOrganizationAutomations,
    type ActionsApiDeleteOrganizationAutomationsRequest,
    ActionsApi_PauseOrganizationAutomations,
    type ActionsApiPauseOrganizationAutomationsRequest,
    ActionsApi_UnpauseOrganizationAutomations,
    type ActionsApiUnpauseOrganizationAutomationsRequest,
    ActionsApi_UnsubscribeOrganizationAutomations,
    type ActionsApiUnsubscribeOrganizationAutomationsRequest,
    ActionsApi_GetDependentEntitiesGraph,
    type ActionsApiGetDependentEntitiesGraphRequest,
    ActionsApi_GetDependentEntitiesGraphFromEntryPoints,
    type ActionsApiGetDependentEntitiesGraphFromEntryPointsRequest,
    ActionsApi_AllPlatformUsage,
    ActionsApi_ParticularPlatformUsage,
    type ActionsApiParticularPlatformUsageRequest,
    ActionsApi_GenerateLogicalModel,
    type ActionsApiGenerateLogicalModelRequest,
    ActionsApi_CheckEntityOverrides,
    type ActionsApiCheckEntityOverridesRequest,
    ActionsApi_SetCertification,
    type ActionsApiSetCertificationRequest,
    ActionsApi_DashboardPermissions,
    type ActionsApiDashboardPermissionsRequest,
    ActionsApi_ManageDashboardPermissions,
    type ActionsApiManageDashboardPermissionsRequest,
    ActionsApi_AvailableAssignees,
    type ActionsApiAvailableAssigneesRequest,
    ActionsApi_WorkspaceResolveSettings,
    type ActionsApiWorkspaceResolveSettingsRequest,
} from "../../generated/metadata-json-api/index.js";

// Execution Result API and Knowledge Documents API
export {
    // Execution Result
    ActionsApi_ResolveLlmEndpoints,
    type ActionsApiResolveLlmEndpointsRequest,
    ActionsApi_ResolveLlmProviders,
    type ActionsApiResolveLlmProvidersRequest,
    ActionsApi_GenerateDescription,
    type ActionsApiGenerateDescriptionRequest,
    ActionsApi_GenerateTitle,
    type ActionsApiGenerateTitleRequest,
    // Knowledge Documents
    ActionsApi_CreateDocument,
    type ActionsApiCreateDocumentRequest,
    ActionsApi_DeleteDocument,
    type ActionsApiDeleteDocumentRequest,
    ActionsApi_GetDocument,
    type ActionsApiGetDocumentRequest,
    ActionsApi_ListDocuments,
    type ActionsApiListDocumentsRequest,
    ActionsApi_PatchDocument,
    type ActionsApiPatchDocumentRequest,
    ActionsApi_SearchKnowledge,
    type ActionsApiSearchKnowledgeRequest,
    ActionsApi_UpsertDocument,
    type ActionsApiUpsertDocumentRequest,
} from "../../generated/afm-rest-api/index.js";
