// (C) 2025 GoodData Corporation

// Actions API - Export commonly used ActionsApi functions
export {
    ActionsApi_ManageOrganizationPermissions,
    type ActionsApiManageOrganizationPermissionsRequest,
    ActionsApi_WorkspaceResolveAllSettings,
    type ActionsApiWorkspaceResolveAllSettingsRequest,
    ActionsApi_ResolveAllEntitlements,
    ActionsApi_ResolveAllSettingsWithoutWorkspace,
    ActionsApi_DeleteWorkspaceAutomations,
    type ActionsApiDeleteWorkspaceAutomationsRequest,
    ActionsApi_PauseWorkspaceAutomations,
    type ActionsApiPauseWorkspaceAutomationsRequest,
    ActionsApi_UnpauseWorkspaceAutomations,
    type ActionsApiUnpauseWorkspaceAutomationsRequest,
    ActionsApi_UnsubscribeAutomation,
    type ActionsApiUnsubscribeAutomationRequest,
    ActionsApi_UnsubscribeSelectedWorkspaceAutomations,
    type ActionsApiUnsubscribeSelectedWorkspaceAutomationsRequest,
    ActionsApi_InheritedEntityPrefixes,
    type ActionsApiInheritedEntityPrefixesRequest,
    ActionsApi_MetadataSync,
    type ActionsApiMetadataSyncRequest,
    ActionsApi_ListWorkspaceUsers,
    type ActionsApiListWorkspaceUsersRequest,
    ActionsApi_RegisterUploadNotification,
    type ActionsApiRegisterUploadNotificationRequest,
    ActionsApi_DeleteOrganizationAutomations,
    type ActionsApiDeleteOrganizationAutomationsRequest,
    ActionsApi_PauseOrganizationAutomations,
    type ActionsApiPauseOrganizationAutomationsRequest,
    ActionsApi_UnpauseOrganizationAutomations,
    type ActionsApiUnpauseOrganizationAutomationsRequest,
    ActionsApi_UnsubscribeOrganizationAutomations,
    type ActionsApiUnsubscribeOrganizationAutomationsRequest,
    ActionsApi_GetDependentEntitiesGraph,
    type ActionsApiGetDependentEntitiesGraphRequest,
    ActionsApi_GetDependentEntitiesGraphFromEntryPoints,
    type ActionsApiGetDependentEntitiesGraphFromEntryPointsRequest,
    ActionsApi_AllPlatformUsage,
    ActionsApi_ParticularPlatformUsage,
    type ActionsApiParticularPlatformUsageRequest,
    ActionsApi_GenerateLogicalModel,
    type ActionsApiGenerateLogicalModelRequest,
    ActionsApi_CheckEntityOverrides,
    type ActionsApiCheckEntityOverridesRequest,
    ActionsApi_DashboardPermissions,
    type ActionsApiDashboardPermissionsRequest,
    ActionsApi_ManageDashboardPermissions,
    type ActionsApiManageDashboardPermissionsRequest,
    ActionsApi_AvailableAssignees,
    type ActionsApiAvailableAssigneesRequest,
    ActionsApi_WorkspaceResolveSettings,
    type ActionsApiWorkspaceResolveSettingsRequest,
} from "../../generated/metadata-json-api/index.js";
