# (C) 2021 GoodData Corporation

FROM nginxinc/nginx-unprivileged:1.17.2-alpine

RUN ls -l

COPY dist/ /usr/share/nginx/html/dashboard-plugin-tests/
COPY nginx/nginx.conf /etc/nginx/nginx.conf

ARG GIT_COMMIT=unspecified
LABEL image_name="Gooddata UI SDK Dashboard Plugin Tests - Local"
LABEL maintainer="RAIL <rail@gooddata.com>"
LABEL git_repository_url="https://github.com/gooddata/gooddata-ui-sdk"
LABEL parent_image="nginxinc/nginx-unprivileged:1.17.2-alpine"
LABEL git_commit=$GIT_COMMIT
