// (C) 2019-2026 GoodData Corporation

/**
 * This package provides several React components related to filters.
 *
 * @remarks
 * These include attribute filters, measure value filters, ranking filters, and date filters and utilities
 * to work with those. You can use them to quickly add filtering to your application.
 *
 * @packageDocumentation
 */

export {
    type IDateFilterCallbackProps,
    type IDateFilterOwnProps,
    type IDateFilterProps,
    type IDateFilterState,
    type IDateFilterStatePropsIntersection,
    type AbsoluteDateFilterOption,
    type DateFilterOption,
    type DateFilterRelativeOptionGroup,
    type IDateFilterOptionsByType,
    type IExtendedDateFilterErrors,
    type IDateFilterRelativeFormErrors,
    type RelativeDateFilterOption,
    type IUiAbsoluteDateFilterForm,
    type IUiRelativeDateFilterForm,
    type GranularityIntlKey,
    type DateFilterLabelMode,
    type IDateAndMessageTranslator,
    type IDateTranslator,
    type IMessageTranslator,
    type IFilterConfigurationProps,
    type IDateFilterAbsoluteDateTimeFormErrors,
    type DateRangePosition,
    type CalendarTabType,
    type IFiscalTabsConfig,
    type IUiRelativeDateFilterFormLike,
    DateFilter,
    DateFilterHelpers,
    defaultDateFilterOptions,
    isAbsoluteDateFilterOption,
    isRelativeDateFilterOption,
    isRelativeDateFilterWithBoundOption,
    filterVisibleDateFilterOptions,
    isUiRelativeDateFilterForm,
    getLocalizedIcuDateFormatPattern,
    getFiscalTabsConfig,
    getDefaultCalendarTab,
    getFilteredPresets,
    getFilteredGranularities,
    hasFiscalPresets,
    hasStandardPresets,
    filterStandardPresets,
    filterFiscalPresets,
    filterStandardGranularities,
    filterFiscalGranularities,
    getTabForPreset,
    isFiscalGranularity,
    ensureCompatibleGranularity,
} from "./DateFilter/index.js";
export {
    type IMeasureValueFilterProps,
    type IMeasureValueFilterState,
    MeasureValueFilter,
} from "./MeasureValueFilter/MeasureValueFilter.js";
export {
    type IMeasureValueFilterDropdownProps,
    MeasureValueFilterDropdown,
} from "./MeasureValueFilter/MeasureValueFilterDropdown.js";
export {
    type IMeasureValueFilterCommonProps,
    type IDimensionalityItem,
    type DimensionalityItemType,
    type WarningMessage,
    type IWarningMessage,
    isWarningMessage,
} from "./MeasureValueFilter/typings.js";
export type { MeasureValueFilterOperator } from "./MeasureValueFilter/types.js";
export { intervalIncludesZero } from "./MeasureValueFilter/helpers/intervalIncludesZero.js";
export { type IRankingFilterProps, RankingFilter } from "./RankingFilter/RankingFilter.js";
export {
    type IRankingFilterDropdownProps,
    RankingFilterDropdown,
} from "./RankingFilter/RankingFilterDropdown.js";
export type {
    IMeasureDropdownItem,
    IAttributeDropdownItem,
    ICustomGranularitySelection,
} from "./RankingFilter/types.js";

export {
    type Correlation,
    type CallbackRegistration,
    type Callback,
    type CallbackPayloadWithCorrelation,
    type Unsubscribe,
    type AsyncOperationStatus,
    type IAttributeLoader,
    type IAttributeElementLoader,
    type IAttributeFilterLoader,
    type ILoadElementsResult,
    type ILoadElementsOptions,
    type ILoadIrrelevantElementsResult,
    type OnInitCancelCallbackPayload,
    type OnInitErrorCallbackPayload,
    type OnInitStartCallbackPayload,
    type OnInitSuccessCallbackPayload,
    type OnLoadAttributeCancelCallbackPayload,
    type OnLoadAttributeErrorCallbackPayload,
    type OnLoadAttributeStartCallbackPayload,
    type OnLoadAttributeSuccessCallbackPayload,
    type OnLoadCustomElementsCancelCallbackPayload,
    type OnLoadCustomElementsErrorCallbackPayload,
    type OnLoadCustomElementsStartCallbackPayload,
    type OnLoadCustomElementsSuccessCallbackPayload,
    type OnLoadInitialElementsPageCancelCallbackPayload,
    type OnLoadInitialElementsPageErrorCallbackPayload,
    type OnLoadInitialElementsPageStartCallbackPayload,
    type OnLoadInitialElementsPageSuccessCallbackPayload,
    type OnLoadNextElementsPageCancelCallbackPayload,
    type OnLoadNextElementsPageErrorCallbackPayload,
    type OnLoadNextElementsPageStartCallbackPayload,
    type OnLoadNextElementsPageSuccessCallbackPayload,
    type OnInitTotalCountStartCallbackPayload,
    type OnInitTotalCountSuccessCallbackPayload,
    type OnInitTotalCountErrorCallbackPayload,
    type OnInitTotalCountCancelCallbackPayload,
    type OnSelectionChangedCallbackPayload,
    type OnSelectionCommittedCallbackPayload,
    type OnLoadIrrelevantElementsStartCallbackPayload,
    type OnLoadIrrelevantElementsSuccessCallbackPayload,
    type OnLoadIrrelevantElementsCancelCallbackPayload,
    type OnLoadIrrelevantElementsErrorCallbackPayload,
    type IAttributeFilterHandlerOptions,
    type IAttributeFilterHandlerOptionsBase,
    type AttributeElementKey,
    type ISingleSelectionHandler,
    type IStagedSingleSelectionHandler,
    type ISingleSelectAttributeFilterHandlerOptions,
    type InvertableSelection,
    type IInvertableSelectionHandler,
    type IStagedInvertableSelectionHandler,
    type IMultiSelectAttributeFilterHandlerOptions,
    type InvertableAttributeElementSelection,
    type IAttributeFilterHandler,
    type ISingleSelectAttributeFilterHandler,
    type IMultiSelectAttributeFilterHandler,
    newAttributeFilterHandler,
} from "./AttributeFilterHandler/index.js";

export {
    type IAttributeFilterProps,
    type IAttributeFilterButtonProps,
    type IAttributeFilterBaseProps,
    type IAttributeFilterErrorProps,
    type IAttributeFilterLoadingProps,
    type IAttributeFilterDropdownButtonProps,
    type IAttributeFilterDropdownBodyProps,
    type IAttributeFilterDropdownActionsProps,
    type IAttributeFilterElementsSearchBarProps,
    type IAttributeFilterElementsActionsProps,
    type IAttributeFilterElementsSelectProps,
    type IAttributeFilterElementsSelectItemProps,
    type IAttributeFilterElementsSelectErrorProps,
    type IAttributeFilterElementsSelectLoadingProps,
    type IAttributeFilterEmptyResultProps,
    type IAttributeFilterStatusBarProps,
    type OnApplyCallbackType,
    type OnSelectCallbackType,
    type ParentFilterOverAttributeType,
    type IAttributeFilterCoreProps,
    type IAttributeFilterCustomComponentProps,
    type IUseAttributeFilterControllerProps,
    type IUseAttributeFilterHandlerProps,
    type IAttributeFilterContext,
    type IAttributeDatasetInfoProps,
    type IAttributeDisplayFormSelectProps,
    type IAttributeFilterAllValuesFilteredResultProps,
    type IAttributeFilterConfigurationButtonProps,
    type IAttributeFilterDeleteButtonProps,
    type IAttributeFilterFilteredStatusProps,
    type IAttributeFilterSelectionStatusProps,
    type IUseAttributeFilterSearchProps,
    type AttributeFilterController,
    type AttributeFilterControllerData,
    type AttributeFilterControllerCallbacks,
    type IAttributeFilterDependencyTooltipProps,
    AttributeFilter,
    AttributeFilterButton,
    useAttributeFilterController,
    useAttributeFilterHandler,
    useAttributeFilterContext,
    AttributeDisplayFormSelect,
    AttributeFilterAllValuesFilteredResult,
    AttributeFilterConfigurationButton,
    AttributeFilterDeleteButton,
    AttributeFilterDropdownActions,
    AttributeFilterDropdownBody,
    AttributeFilterDropdownButton,
    AttributeFilterElementsActions,
    AttributeFilterElementsSearchBar,
    AttributeFilterElementsSelect,
    AttributeFilterElementsSelectError,
    AttributeFilterElementsSelectItem,
    SingleSelectionAttributeFilterElementsSelectItem,
    AttributeFilterElementsSelectLoading,
    AttributeFilterEmptyAttributeResult,
    AttributeFilterEmptyResult,
    AttributeFilterEmptySearchResult,
    AttributeFilterError,
    AttributeFilterFilteredStatus,
    AttributeFilterLoading,
    AttributeFilterSelectionStatus,
    AttributeFilterSimpleDropdownButton,
    AttributeFilterSimpleDropdownButtonWithSelection,
    AttributeFilterStatusBar,
    SingleSelectionAttributeFilterStatusBar,
    AttributeDatasetInfo,
    AttributeFilterButtonTooltip,
    EmptyElementsSearchBar,
    useAutoOpenAttributeFilterDropdownButton,
    useOnCloseAttributeFilterDropdownButton,
    useAttributeFilterSearch,
    AttributeFilterDependencyTooltip,
    getAttributeFilterSubtitle,
} from "./AttributeFilter/index.js";

export { FilterGroup, type IFilterGroupProps } from "./FilterGroup/index.js";

export type { IFilterButtonCustomIcon, VisibilityMode } from "./shared/index.js";

export type { IDateFilterButtonProps } from "./DateFilter/DateFilterButton/DateFilterButton.js";
