# (C) 2021 GoodData Corporation

FROM 020413372491.dkr.ecr.us-east-1.amazonaws.com/pullthrough/docker.io/nginxinc/nginx-unprivileged:1.31.1-alpine@sha256:85bcbc6b2edd325462560c597d784ecee415024f1c6a004e53ac5f202b8ca561

RUN ls -l

COPY scenarios/build /usr/share/nginx/html/gooddata-ui-sdk/
COPY nginx/nginx.conf /etc/nginx/nginx.conf

ARG GIT_COMMIT=unspecified
LABEL image_name="GOODDATA UI SDK - development"
LABEL maintainer="RAIL <rail@gooddata.com>"
LABEL git_repository_url="https://github.com/gooddata/gooddata-ui-sdk"
LABEL parent_image="020413372491.dkr.ecr.us-east-1.amazonaws.com/pullthrough/docker.io/nginxinc/nginx-unprivileged:1.25.2-alpine"
LABEL git_commit=$GIT_COMMIT
