// (C) 2025-2026 GoodData Corporation

/* oxlint-disable no-barrel-files/no-barrel-files */

export {
    // DashboardsApi
    DashboardsApi_GetAllEntitiesAnalyticalDashboards,
    DashboardsApi_GetEntityAnalyticalDashboards,
    DashboardsApi_CreateEntityAnalyticalDashboards,
    DashboardsApi_UpdateEntityAnalyticalDashboards,
    DashboardsApi_PatchEntityAnalyticalDashboards,
    DashboardsApi_DeleteEntityAnalyticalDashboards,
    type DashboardsApiGetAllEntitiesAnalyticalDashboardsRequest,
    type DashboardsApiGetEntityAnalyticalDashboardsRequest,
    type DashboardsApiCreateEntityAnalyticalDashboardsRequest,
    type DashboardsApiUpdateEntityAnalyticalDashboardsRequest,
    type DashboardsApiPatchEntityAnalyticalDashboardsRequest,
    type DashboardsApiDeleteEntityAnalyticalDashboardsRequest,
    // EntitiesApi - Search
    EntitiesApi_SearchEntitiesAnalyticalDashboards,
    type EntitiesApiSearchEntitiesAnalyticalDashboardsRequest,
    EntitiesApi_SearchEntitiesVisualizationObjects,
    type EntitiesApiSearchEntitiesVisualizationObjectsRequest,
    EntitiesApi_SearchEntitiesMetrics,
    type EntitiesApiSearchEntitiesMetricsRequest,
    EntitiesApi_SearchEntitiesAttributes,
    type EntitiesApiSearchEntitiesAttributesRequest,
    EntitiesApi_SearchEntitiesFacts,
    type EntitiesApiSearchEntitiesFactsRequest,
    // EntitiesApi - DashboardPlugins
    EntitiesApi_CreateEntityDashboardPlugins,
    EntitiesApi_DeleteEntityDashboardPlugins,
    EntitiesApi_GetEntityDashboardPlugins,
    EntitiesApi_GetAllEntitiesDashboardPlugins,
    type EntitiesApiCreateEntityDashboardPluginsRequest,
    type EntitiesApiDeleteEntityDashboardPluginsRequest,
    type EntitiesApiGetEntityDashboardPluginsRequest,
    type EntitiesApiGetAllEntitiesDashboardPluginsRequest,
    // FilterViewsApi
    FilterViewsApi_GetAllEntitiesFilterViews,
    FilterViewsApi_GetEntityFilterViews,
    FilterViewsApi_CreateEntityFilterViews,
    FilterViewsApi_DeleteEntityFilterViews,
    FilterViewsApi_PatchEntityFilterViews,
    type FilterViewsApiGetAllEntitiesFilterViewsRequest,
    type FilterViewsApiGetEntityFilterViewsRequest,
    type FilterViewsApiCreateEntityFilterViewsRequest,
    type FilterViewsApiDeleteEntityFilterViewsRequest,
    type FilterViewsApiPatchEntityFilterViewsRequest,
    // ContextFiltersApi
    FilterContextApi_CreateEntityFilterContexts,
    FilterContextApi_GetEntityFilterContexts,
    FilterContextApi_UpdateEntityFilterContexts,
    type FilterContextApiCreateEntityFilterContextsRequest,
    type FilterContextApiGetEntityFilterContextsRequest,
    type FilterContextApiUpdateEntityFilterContextsRequest,
    // EntitiesApi - Workspaces
    EntitiesApi_GetEntityWorkspaces,
    EntitiesApi_GetAllEntitiesWorkspaces,
    EntitiesApi_CreateEntityWorkspaces,
    EntitiesApi_PatchEntityWorkspaces,
    EntitiesApi_DeleteEntityWorkspaces,
    type EntitiesApiGetEntityWorkspacesRequest,
    type EntitiesApiGetAllEntitiesWorkspacesRequest,
    type EntitiesApiCreateEntityWorkspacesRequest,
    type EntitiesApiPatchEntityWorkspacesRequest,
    type EntitiesApiDeleteEntityWorkspacesRequest,
    // EntitiesApi - VisualizationObjects
    EntitiesApi_GetAllEntitiesVisualizationObjects,
    EntitiesApi_GetEntityVisualizationObjects,
    EntitiesApi_CreateEntityVisualizationObjects,
    EntitiesApi_UpdateEntityVisualizationObjects,
    EntitiesApi_PatchEntityVisualizationObjects,
    EntitiesApi_DeleteEntityVisualizationObjects,
    type EntitiesApiGetAllEntitiesVisualizationObjectsRequest,
    type EntitiesApiGetEntityVisualizationObjectsRequest,
    type EntitiesApiCreateEntityVisualizationObjectsRequest,
    type EntitiesApiUpdateEntityVisualizationObjectsRequest,
    type EntitiesApiPatchEntityVisualizationObjectsRequest,
    type EntitiesApiDeleteEntityVisualizationObjectsRequest,
    // EntitiesApi - Metrics
    EntitiesApi_GetAllEntitiesMetrics,
    EntitiesApi_GetEntityMetrics,
    EntitiesApi_CreateEntityMetrics,
    EntitiesApi_UpdateEntityMetrics,
    EntitiesApi_PatchEntityMetrics,
    EntitiesApi_DeleteEntityMetrics,
    type EntitiesApiGetAllEntitiesMetricsRequest,
    type EntitiesApiGetEntityMetricsRequest,
    type EntitiesApiCreateEntityMetricsRequest,
    type EntitiesApiUpdateEntityMetricsRequest,
    type EntitiesApiPatchEntityMetricsRequest,
    type EntitiesApiDeleteEntityMetricsRequest,
    // EntitiesApi - Facts
    EntitiesApi_GetAllEntitiesFacts,
    EntitiesApi_GetEntityFacts,
    EntitiesApi_PatchEntityFacts,
    type EntitiesApiGetAllEntitiesFactsRequest,
    type EntitiesApiGetEntityFactsRequest,
    type EntitiesApiPatchEntityFactsRequest,
    // EntitiesApi - ExportDefinitions
    EntitiesApi_GetAllEntitiesExportDefinitions,
    EntitiesApi_GetEntityExportDefinitions,
    EntitiesApi_CreateEntityExportDefinitions,
    EntitiesApi_UpdateEntityExportDefinitions,
    EntitiesApi_DeleteEntityExportDefinitions,
    type EntitiesApiGetAllEntitiesExportDefinitionsRequest,
    type EntitiesApiGetEntityExportDefinitionsRequest,
    type EntitiesApiCreateEntityExportDefinitionsRequest,
    type EntitiesApiUpdateEntityExportDefinitionsRequest,
    type EntitiesApiDeleteEntityExportDefinitionsRequest,
    // EntitiesApi - ApiTokens
    EntitiesApi_GetAllEntitiesApiTokens,
    EntitiesApi_CreateEntityApiTokens,
    EntitiesApi_DeleteEntityApiTokens,
    type EntitiesApiGetAllEntitiesApiTokensRequest,
    type EntitiesApiCreateEntityApiTokensRequest,
    type EntitiesApiDeleteEntityApiTokensRequest,
    // EntitiesApi - Themes
    EntitiesApi_GetAllEntitiesThemes,
    EntitiesApi_CreateEntityThemes,
    EntitiesApi_UpdateEntityThemes,
    EntitiesApi_DeleteEntityThemes,
    type EntitiesApiGetAllEntitiesThemesRequest,
    type EntitiesApiCreateEntityThemesRequest,
    type EntitiesApiUpdateEntityThemesRequest,
    type EntitiesApiDeleteEntityThemesRequest,
    // EntitiesApi - ColorPalettes
    EntitiesApi_GetAllEntitiesColorPalettes,
    EntitiesApi_CreateEntityColorPalettes,
    EntitiesApi_UpdateEntityColorPalettes,
    EntitiesApi_DeleteEntityColorPalettes,
    type EntitiesApiGetAllEntitiesColorPalettesRequest,
    type EntitiesApiCreateEntityColorPalettesRequest,
    type EntitiesApiUpdateEntityColorPalettesRequest,
    type EntitiesApiDeleteEntityColorPalettesRequest,
    // EntitiesApi - Organizations
    EntitiesApi_GetEntityOrganizations,
    EntitiesApi_PatchEntityOrganizations,
    type EntitiesApiGetEntityOrganizationsRequest,
    type EntitiesApiPatchEntityOrganizationsRequest,
    // EntitiesApi - Entitlements
    EntitiesApi_GetAllEntitiesEntitlements,
    type EntitiesApiGetAllEntitiesEntitlementsRequest,
    // EntitiesApi - DataSources
    EntitiesApi_CreateEntityDataSources,
    EntitiesApi_DeleteEntityDataSources,
    EntitiesApi_GetAllEntitiesDataSourceIdentifiers,
    EntitiesApi_GetAllEntitiesDataSources,
    EntitiesApi_GetEntityDataSourceIdentifiers,
    EntitiesApi_GetEntityDataSources,
    EntitiesApi_PatchEntityDataSources,
    EntitiesApi_UpdateEntityDataSources,
    type EntitiesApiCreateEntityDataSourcesRequest,
    type EntitiesApiDeleteEntityDataSourcesRequest,
    type EntitiesApiGetAllEntitiesDataSourceIdentifiersRequest,
    type EntitiesApiGetAllEntitiesDataSourcesRequest,
    type EntitiesApiGetEntityDataSourceIdentifiersRequest,
    type EntitiesApiGetEntityDataSourcesRequest,
    type EntitiesApiPatchEntityDataSourcesRequest,
    type EntitiesApiUpdateEntityDataSourcesRequest,
    // EntitiesApi - Datasets
    EntitiesApi_GetAllEntitiesDatasets,
    type EntitiesApiGetAllEntitiesDatasetsRequest,
    // EntitiesApi - WorkspaceDataFilters
    EntitiesApi_GetEntityWorkspaceDataFilters,
    EntitiesApi_GetAllEntitiesWorkspaceDataFilters,
    EntitiesApi_CreateEntityWorkspaceDataFilters,
    EntitiesApi_PatchEntityWorkspaceDataFilters,
    EntitiesApi_DeleteEntityWorkspaceDataFilters,
    type EntitiesApiGetEntityWorkspaceDataFiltersRequest,
    type EntitiesApiGetAllEntitiesWorkspaceDataFiltersRequest,
    type EntitiesApiCreateEntityWorkspaceDataFiltersRequest,
    type EntitiesApiPatchEntityWorkspaceDataFiltersRequest,
    type EntitiesApiDeleteEntityWorkspaceDataFiltersRequest,
    // EntitiesApi - WorkspaceDataFilterSettings
    EntitiesApi_GetEntityWorkspaceDataFilterSettings,
    EntitiesApi_GetAllEntitiesWorkspaceDataFilterSettings,
    EntitiesApi_CreateEntityWorkspaceDataFilterSettings,
    EntitiesApi_DeleteEntityWorkspaceDataFilterSettings,
    type EntitiesApiGetEntityWorkspaceDataFilterSettingsRequest,
    type EntitiesApiGetAllEntitiesWorkspaceDataFilterSettingsRequest,
    type EntitiesApiCreateEntityWorkspaceDataFilterSettingsRequest,
    type EntitiesApiDeleteEntityWorkspaceDataFilterSettingsRequest,
    // EntitiesApi - CspDirectives
    EntitiesApi_GetAllEntitiesCspDirectives,
    EntitiesApi_GetEntityCspDirectives,
    EntitiesApi_CreateEntityCspDirectives,
    EntitiesApi_UpdateEntityCspDirectives,
    EntitiesApi_DeleteEntityCspDirectives,
    type EntitiesApiGetAllEntitiesCspDirectivesRequest,
    type EntitiesApiGetEntityCspDirectivesRequest,
    type EntitiesApiCreateEntityCspDirectivesRequest,
    type EntitiesApiUpdateEntityCspDirectivesRequest,
    type EntitiesApiDeleteEntityCspDirectivesRequest,
    // EntitiesApi - CustomApplicationSettings
    EntitiesApi_GetAllEntitiesCustomApplicationSettings,
    EntitiesApi_GetEntityCustomApplicationSettings,
    EntitiesApi_CreateEntityCustomApplicationSettings,
    EntitiesApi_DeleteEntityCustomApplicationSettings,
    type EntitiesApiGetAllEntitiesCustomApplicationSettingsRequest,
    type EntitiesApiGetEntityCustomApplicationSettingsRequest,
    type EntitiesApiCreateEntityCustomApplicationSettingsRequest,
    type EntitiesApiDeleteEntityCustomApplicationSettingsRequest,
    // EntitiesApi - Users
    EntitiesApi_GetAllEntitiesUsers,
    EntitiesApi_GetEntityUsers,
    EntitiesApi_CreateEntityUsers,
    EntitiesApi_PatchEntityUsers,
    type EntitiesApiGetAllEntitiesUsersRequest,
    type EntitiesApiGetEntityUsersRequest,
    type EntitiesApiCreateEntityUsersRequest,
    type EntitiesApiPatchEntityUsersRequest,
    // EntitiesApi - UserGroups
    EntitiesApi_CreateEntityUserGroups,
    EntitiesApi_DeleteEntityUserGroups,
    EntitiesApi_GetAllEntitiesUserGroups,
    EntitiesApi_GetEntityUserGroups,
    EntitiesApi_PatchEntityUserGroups,
    EntitiesApi_UpdateEntityUserGroups,
    type EntitiesApiCreateEntityUserGroupsRequest,
    type EntitiesApiDeleteEntityUserGroupsRequest,
    type EntitiesApiGetAllEntitiesUserGroupsRequest,
    type EntitiesApiGetEntityUserGroupsRequest,
    type EntitiesApiPatchEntityUserGroupsRequest,
    type EntitiesApiUpdateEntityUserGroupsRequest,
    // EntitiesApi - WorkspaceSettings
    EntitiesApi_GetAllEntitiesWorkspaceSettings,
    EntitiesApi_UpdateEntityWorkspaceSettings,
    EntitiesApi_CreateEntityWorkspaceSettings,
    EntitiesApi_DeleteEntityWorkspaceSettings,
    type EntitiesApiGetAllEntitiesWorkspaceSettingsRequest,
    type EntitiesApiUpdateEntityWorkspaceSettingsRequest,
    type EntitiesApiCreateEntityWorkspaceSettingsRequest,
    type EntitiesApiDeleteEntityWorkspaceSettingsRequest,
    // EntitiesApi - Attributes
    EntitiesApi_GetAllEntitiesAttributes,
    EntitiesApi_GetAllEntitiesLabels,
    EntitiesApi_GetEntityAttributes,
    EntitiesApi_PatchEntityAttributes,
    type EntitiesApiGetAllEntitiesAttributesRequest,
    type EntitiesApiGetAllEntitiesLabelsRequest,
    type EntitiesApiGetEntityAttributesRequest,
    type EntitiesApiPatchEntityAttributesRequest,
    // EntitiesApi - AttributeHierarchies
    EntitiesApi_CreateEntityAttributeHierarchies,
    EntitiesApi_UpdateEntityAttributeHierarchies,
    EntitiesApi_DeleteEntityAttributeHierarchies,
    type EntitiesApiCreateEntityAttributeHierarchiesRequest,
    type EntitiesApiUpdateEntityAttributeHierarchiesRequest,
    type EntitiesApiDeleteEntityAttributeHierarchiesRequest,
    // EntitiesApi - Automations
    EntitiesApi_GetAllEntitiesAutomations,
    EntitiesApi_GetEntityAutomations,
    EntitiesApi_CreateEntityAutomations,
    EntitiesApi_UpdateEntityAutomations,
    EntitiesApi_DeleteEntityAutomations,
    type EntitiesApiGetAllEntitiesAutomationsRequest,
    type EntitiesApiGetEntityAutomationsRequest,
    type EntitiesApiCreateEntityAutomationsRequest,
    type EntitiesApiUpdateEntityAutomationsRequest,
    type EntitiesApiDeleteEntityAutomationsRequest,
    // EntitiesApi - LlmEndpoints
    EntitiesApi_GetAllEntitiesLlmEndpoints,
    EntitiesApi_GetEntityLlmEndpoints,
    EntitiesApi_CreateEntityLlmEndpoints,
    EntitiesApi_UpdateEntityLlmEndpoints,
    EntitiesApi_PatchEntityLlmEndpoints,
    EntitiesApi_DeleteEntityLlmEndpoints,
    type EntitiesApiGetAllEntitiesLlmEndpointsRequest,
    type EntitiesApiGetEntityLlmEndpointsRequest,
    type EntitiesApiCreateEntityLlmEndpointsRequest,
    type EntitiesApiUpdateEntityLlmEndpointsRequest,
    type EntitiesApiPatchEntityLlmEndpointsRequest,
    type EntitiesApiDeleteEntityLlmEndpointsRequest,
    // EntitiesApi - MemoryItems
    EntitiesApi_GetAllEntitiesMemoryItems,
    EntitiesApi_CreateEntityMemoryItems,
    EntitiesApi_UpdateEntityMemoryItems,
    EntitiesApi_PatchEntityMemoryItems,
    EntitiesApi_DeleteEntityMemoryItems,
    type EntitiesApiGetAllEntitiesMemoryItemsRequest,
    type EntitiesApiCreateEntityMemoryItemsRequest,
    type EntitiesApiUpdateEntityMemoryItemsRequest,
    type EntitiesApiPatchEntityMemoryItemsRequest,
    type EntitiesApiDeleteEntityMemoryItemsRequest,
    // EntitiesApi - NotificationChannels
    EntitiesApi_GetAllEntitiesNotificationChannels,
    EntitiesApi_GetAllEntitiesNotificationChannelIdentifiers,
    EntitiesApi_GetEntityNotificationChannels,
    EntitiesApi_CreateEntityNotificationChannels,
    EntitiesApi_UpdateEntityNotificationChannels,
    EntitiesApi_PatchEntityNotificationChannels,
    EntitiesApi_DeleteEntityNotificationChannels,
    type EntitiesApiGetAllEntitiesNotificationChannelsRequest,
    type EntitiesApiGetAllEntitiesNotificationChannelIdentifiersRequest,
    type EntitiesApiGetEntityNotificationChannelsRequest,
    type EntitiesApiCreateEntityNotificationChannelsRequest,
    type EntitiesApiUpdateEntityNotificationChannelsRequest,
    type EntitiesApiPatchEntityNotificationChannelsRequest,
    type EntitiesApiDeleteEntityNotificationChannelsRequest,
    // EntitiesApi - OrganizationSettings
    EntitiesApi_GetAllEntitiesOrganizationSettings,
    EntitiesApi_UpdateEntityOrganizationSettings,
    EntitiesApi_CreateEntityOrganizationSettings,
    EntitiesApi_DeleteEntityOrganizationSettings,
    type EntitiesApiGetAllEntitiesOrganizationSettingsRequest,
    type EntitiesApiUpdateEntityOrganizationSettingsRequest,
    type EntitiesApiCreateEntityOrganizationSettingsRequest,
    type EntitiesApiDeleteEntityOrganizationSettingsRequest,
    // EntitiesApi - UserSettings
    EntitiesApi_GetAllEntitiesUserSettings,
    EntitiesApi_UpdateEntityUserSettings,
    EntitiesApi_CreateEntityUserSettings,
    EntitiesApi_DeleteEntityUserSettings,
    type EntitiesApiGetAllEntitiesUserSettingsRequest,
    type EntitiesApiUpdateEntityUserSettingsRequest,
    type EntitiesApiCreateEntityUserSettingsRequest,
    type EntitiesApiDeleteEntityUserSettingsRequest,
    // AutomationOrganizationViewControllerApi
    AutomationOrganizationViewControllerApi_GetAllAutomationsWorkspaceAutomations,
    type AutomationOrganizationViewControllerApiGetAllAutomationsWorkspaceAutomationsRequest,
} from "../../generated/metadata-json-api/index.js";
