// (C) 2019-2025 GoodData Corporation
import { AxiosInstance } from "axios";
import {
    ActionsApi,
    ActionsApiGetNotificationsRequest,
    ActionsApiInterface,
    ActionsApiMarkAsReadNotificationAllRequest,
    ActionsApiMarkAsReadNotificationRequest,
    ActionsApiTestExistingNotificationChannelRequest,
    ActionsApiTestNotificationChannelRequest,
    ActionsApiTriggerAutomationRequest,
    ActionsApiTriggerExistingAutomationRequest,
    AdHocAutomation,
    AlertDescription,
    AlertDescriptionStatusEnum,
    AlertEvaluationRow,
    AutomationExternalRecipient,
    AutomationMetadata,
    AutomationNotification,
    AutomationTabularExport,
    AutomationVisualExport,
    CustomLabel,
    CustomMetric,
    CustomOverride,
    DeclarativeAnalyticalDashboardIdentifier,
    DeclarativeAnalyticalDashboardIdentifierTypeEnum,
    DeclarativeNotificationChannelIdentifier,
    DeclarativeNotificationChannelIdentifierTypeEnum,
    DeclarativeUserIdentifier,
    DeclarativeUserIdentifierTypeEnum,
    DefaultSmtp,
    DefaultSmtpTypeEnum,
    ExportResult,
    ExportResultStatusEnum,
    InPlatform,
    InPlatformTypeEnum,
    MetricRecord,
    Notification,
    NotificationContent,
    NotificationFilter,
    Notifications,
    NotificationsMeta,
    NotificationsMetaTotal,
    PdfTableStyle,
    PdfTableStyleProperty,
    Settings,
    Smtp,
    SmtpPortEnum,
    SmtpTypeEnum,
    TabularExportRequest,
    TabularExportRequestFormatEnum,
    TestDestinationRequest,
    TestNotification,
    TestResponse,
    TriggerAutomationRequest,
    VisibleFilter,
    VisualExportRequest,
    Webhook,
    WebhookAutomationInfo,
    WebhookMessage,
    WebhookMessageData,
    WebhookMessageTypeEnum,
    WebhookRecipient,
    WebhookTypeEnum,
} from "./generated/automation-json-api/index.js";

/**
 * Tiger execution client factory
 */
export const tigerAutomationClientFactory = (axios: AxiosInstance): ActionsApiInterface =>
    new ActionsApi(undefined, "", axios);

export type {
    ActionsApiGetNotificationsRequest as AutomationActionsApiGetNotificationsRequest,
    ActionsApiInterface as AutomationActionsApiInterface,
    ActionsApiMarkAsReadNotificationAllRequest as AutomationActionsApiMarkAsReadNotificationAllRequest,
    ActionsApiMarkAsReadNotificationRequest as AutomationActionsApiMarkAsReadNotificationRequest,
    ActionsApiTestExistingNotificationChannelRequest as AutomationActionsApiTestExistingNotificationChannelRequest,
    ActionsApiTestNotificationChannelRequest as AutomationActionsApiTestNotificationChannelRequest,
    ActionsApiTriggerAutomationRequest as AutomationActionsApiTriggerAutomationRequest,
    ActionsApiTriggerExistingAutomationRequest as AutomationActionsApiTriggerExistingAutomationRequest,
    AdHocAutomation as AutomationAdHocAutomation,
    AlertDescription as AutomationAlertDescription,
    AlertDescriptionStatusEnum as AutomationAlertDescriptionStatusEnum,
    AlertEvaluationRow as AutomationAlertEvaluationRow,
    AutomationExternalRecipient as AutomationAutomationExternalRecipient,
    AutomationMetadata as AutomationAutomationMetadata,
    AutomationNotification as AutomationAutomationNotification,
    AutomationTabularExport as AutomationAutomationTabularExport,
    AutomationVisualExport as AutomationAutomationVisualExport,
    CustomLabel as AutomationCustomLabel,
    CustomMetric as AutomationCustomMetric,
    CustomOverride as AutomationCustomOverride,
    DeclarativeAnalyticalDashboardIdentifier as AutomationDeclarativeAnalyticalDashboardIdentifier,
    DeclarativeAnalyticalDashboardIdentifierTypeEnum as AutomationDeclarativeAnalyticalDashboardIdentifierTypeEnum,
    DeclarativeNotificationChannelIdentifier as AutomationDeclarativeNotificationChannelIdentifier,
    DeclarativeNotificationChannelIdentifierTypeEnum as AutomationDeclarativeNotificationChannelIdentifierTypeEnum,
    DeclarativeUserIdentifier as AutomationDeclarativeUserIdentifier,
    DeclarativeUserIdentifierTypeEnum as AutomationDeclarativeUserIdentifierTypeEnum,
    DefaultSmtp as AutomationDefaultSmtp,
    DefaultSmtpTypeEnum as AutomationDefaultSmtpTypeEnum,
    ExportResult as AutomationExportResult,
    ExportResultStatusEnum as AutomationExportResultStatusEnum,
    InPlatform as AutomationInPlatform,
    InPlatformTypeEnum as AutomationInPlatformTypeEnum,
    MetricRecord as AutomationMetricRecord,
    Notification as AutomationNotification,
    NotificationContent as AutomationNotificationContent,
    NotificationFilter as AutomationNotificationFilter,
    Notifications as AutomationNotifications,
    NotificationsMeta as AutomationNotificationsMeta,
    NotificationsMetaTotal as AutomationNotificationsMetaTotal,
    PdfTableStyle as AutomationPdfTableStyle,
    PdfTableStyleProperty as AutomationPdfTableStyleProperty,
    Settings as AutomationSettings,
    Smtp as AutomationSmtp,
    SmtpPortEnum as AutomationSmtpPortEnum,
    SmtpTypeEnum as AutomationSmtpTypeEnum,
    TabularExportRequest as AutomationTabularExportRequest,
    TabularExportRequestFormatEnum as AutomationTabularExportRequestFormatEnum,
    TestDestinationRequest as AutomationTestDestinationRequest,
    TestNotification as AutomationTestNotification,
    TestResponse as AutomationTestResponse,
    TriggerAutomationRequest as AutomationTriggerAutomationRequest,
    VisibleFilter as AutomationVisibleFilter,
    VisualExportRequest as AutomationVisualExportRequest,
    Webhook as AutomationWebhook,
    WebhookAutomationInfo as AutomationWebhookAutomationInfo,
    WebhookMessage as AutomationWebhookMessage,
    WebhookMessageData as AutomationWebhookMessageData,
    WebhookMessageTypeEnum as AutomationWebhookMessageTypeEnum,
    WebhookRecipient as AutomationWebhookRecipient,
    WebhookTypeEnum as AutomationWebhookTypeEnum,
};
