// (C) 2019-2026 GoodData Corporation

/**
 * This package provides low-level functions for communication with GoodData Cloud and GoodData.CN.
 *
 * @remarks
 * The package is used by `@gooddata/sdk-backend-tiger`, which you should use instead of directly using
 * `@gooddata/api-client-tiger` whenever possible.
 *
 * @packageDocumentation
 */
import {
    axios as defaultAxios,
    newAxios,
    setAxiosAuthorizationToken,
    setGlobalAuthorizationToken,
} from "./axios.js";
import { type ITigerClient, tigerClientFactory } from "./client.js";

export {
    VisualizationObjectModelV1,
    VisualizationObjectModelV2,
    AnalyticalDashboardModelV1,
    AnalyticalDashboardModelV2,
    isAttributeHeader,
    isAfmObjectIdentifier,
    isAfmObjectLocalIdentifier,
    isResultAttributeHeader,
    isResultMeasureHeader,
    isResultTotalHeader,
    isVisualizationObjectsItem,
    isFilterContextData,
    isDashboardPluginsItem,
    isDataSetItem,
    isLabelItem,
    isAttributeItem,
    isMetricItem,
    isFactItem,
} from "./gd-tiger-model/index.js";

export { newAxios, setAxiosAuthorizationToken, setGlobalAuthorizationToken };

export type {
    AFM as AfmModel,
    AfmIdentifier as AfmModelIdentifier,
    AfmLocalIdentifier as AfmModelLocalIdentifier,
    AfmObjectIdentifierAttributeIdentifier as AfmModelObjectIdentifierAttributeIdentifier,
    AfmObjectIdentifierCore as AfmModelObjectIdentifierCore,
    AfmObjectIdentifierCoreIdentifier as AfmModelObjectIdentifierCoreIdentifier,
    AfmObjectIdentifierDataset as AfmModelObjectIdentifierDataset,
    AfmObjectIdentifierDatasetIdentifier as AfmModelObjectIdentifierDatasetIdentifier,
    AfmObjectIdentifierIdentifier as AfmModelObjectIdentifierIdentifier,
    AfmObjectIdentifierLabel as AfmModelObjectIdentifierLabel,
    AfmObjectIdentifierAttribute as AfmModelObjectIdentifierAttribute,
    AfmObjectIdentifierLabelIdentifier as AfmModelObjectIdentifierLabelIdentifier,
    AbsoluteDateFilter as AfmAbsoluteDateFilter,
    AbsoluteDateFilterAbsoluteDateFilter as AfmAbsoluteDateFilterAbsoluteDateFilter,
    AbstractMeasureValueFilter,
    AfmExecution,
    AfmExecutionResponse,
    AfmObjectIdentifier as AfmModelObjectIdentifier,
    AfmValidObjectsQuery,
    AfmValidObjectsResponse,
    ArithmeticMeasureDefinition as AfmArithmeticMeasureDefinition,
    ArithmeticMeasureDefinitionArithmeticMeasure as AfmArithmeticMeasureDefinitionArithmeticMeasure,
    AttributeExecutionResultHeader,
    AttributeFilter as AfmAttributeFilter,
    AttributeFilterElements as AfmAttributeFilterElements,
    AttributeHeader,
    AttributeHeaderAttributeHeader,
    AttributeItem as AfmAttributeItem,
    AttributeResultHeader,
    ComparisonMeasureValueFilter as AfmComparisonMeasureValueFilter,
    ComparisonMeasureValueFilterComparisonMeasureValueFilter as AfmComparisonMeasureValueFilterComparisonMeasureValueFilter,
    DataColumnLocator,
    DataColumnLocators,
    DateFilter as AfmDateFilter,
    Dimension,
    DimensionHeader,
    Element,
    ElementsRequest,
    FilterBy,
    ElementsResponse,
    ExecutionLinks,
    ExecutionResponse,
    ExecutionResult,
    ExecutionResultDataSourceMessage,
    ExecutionResultGrandTotal,
    ExecutionResultHeader,
    ExecutionResultMetadata,
    ExecutionResultPaging,
    ExecutionSettings as AfmExecutionSettings,
    FilterDefinition as AfmFilterDefinition,
    FilterDefinitionForSimpleMeasure as AfmFilterDefinitionForSimpleMeasure,
    HeaderGroup,
    InlineFilterDefinition as AfmInlineFilterDefinition,
    InlineFilterDefinitionInline as AfmInlineFilterDefinitionInline,
    InlineMeasureDefinition as AfmInlineMeasureDefinition,
    InlineMeasureDefinitionInline as AfmInlineMeasureDefinitionInline,
    MeasureDefinition as AfmMeasureDefinition,
    MeasureExecutionResultHeader,
    MeasureGroupHeaders,
    MeasureHeader,
    MeasureItem as AfmMeasureItem,
    MeasureResultHeader,
    MeasureValueFilter,
    NegativeAttributeFilter as AfmNegativeAttributeFilter,
    NegativeAttributeFilterNegativeAttributeFilter as AfmNegativeAttributeFilterNegativeAttributeFilter,
    Paging,
    PopDataset as AfmPopDataset,
    PopMeasureDefinition as AfmPopMeasureDefinition,
    PopDatasetMeasureDefinition as AfmPopDatasetMeasureDefinition,
    PopDatasetMeasureDefinitionPreviousPeriodMeasure as AfmPopDatasetMeasureDefinitionPreviousPeriodMeasure,
    PopDate as AfmPopDate,
    PopDateMeasureDefinition as AfmPopDateMeasureDefinition,
    PopDateMeasureDefinitionOverPeriodMeasure as AfmPopDateMeasureDefinitionOverPeriodMeasure,
    PositiveAttributeFilter as AfmPositiveAttributeFilter,
    PositiveAttributeFilterPositiveAttributeFilter as AfmPositiveAttributeFilterPositiveAttributeFilter,
    RangeMeasureValueFilter as AfmRangeMeasureValueFilter,
    RangeMeasureValueFilterRangeMeasureValueFilter as AfmRangeMeasureValueFilterRangeMeasureValueFilter,
    RankingFilter as AfmRankingFilter,
    RankingFilterRankingFilter as AfmRankingFilterRankingFilter,
    RelativeDateFilter as AfmRelativeDateFilter,
    RelativeDateFilterRelativeDateFilter as AfmRelativeDateFilterRelativeDateFilter,
    BoundedFilter as AfmBoundedFilter,
    ResultCacheMetadata,
    ResultDimension,
    ResultDimensionHeader,
    ResultSpec,
    SimpleMeasureDefinition as AfmSimpleMeasureDefinition,
    SimpleMeasureDefinitionMeasure as AfmSimpleMeasureDefinitionMeasure,
    SortKey,
    SortKeyAttribute,
    SortKeyAttributeAttribute,
    SortKeyTotal,
    SortKeyTotalTotal,
    SortKeyValue,
    SortKeyValueValue,
    TotalExecutionResultHeader,
    TotalResultHeader,
    ActionsApiInterface as AfmActionsApiInterface,
    ActionsApiComputeLabelElementsPostRequest,
    ActionsApiComputeReportRequest,
    ActionsApiComputeValidObjectsRequest,
    ActionsApiExplainAFMRequest,
    ActionsApiRetrieveResultRequest,
    ActionsApiRetrieveExecutionMetadataRequest,
    ActionsApiResolveLlmEndpointsRequest,
    RestApiIdentifier,
    Total,
    TotalDimension,
    AttributeFormat,
    ActionsApiComputeValidDescendantsRequest,
    AfmValidDescendantsQuery,
    AfmValidDescendantsResponse,
    DependsOn,
    DependsOnDateFilter,
    ValidateByItem,
    ForecastRequest,
    ActionsApiForecastRequest,
    SmartFunctionResponse,
    ActionsApiForecastResultRequest,
    ForecastResult,
    ClusteringRequest,
    ClusteringResult,
    ActionsApiClusteringRequest,
    ActionsApiClusteringResultRequest,
    KeyDriversRequest,
    ActionsApiKeyDriverAnalysisRequest,
    KeyDriversResponse,
    ActionsApiKeyDriverAnalysisResultRequest,
    KeyDriversResult,
    KeyDriversDimension,
    AnomalyDetectionRequest,
    ActionsApiAnomalyDetectionRequest,
    ActionsApiAnomalyDetectionResultRequest,
    AnomalyDetectionResult,
    SearchRequest,
    ActionsApiAiSearchRequest,
    SearchResult,
    SearchResultObject,
    SearchRelationshipObject,
    RouteResult,
    RouteResultUseCaseEnum,
    CreatedVisualization,
    Metric,
    DimAttribute,
    DimAttributeTypeEnum,
    MetricTypeEnum,
    ChatRequest,
    ChatHistoryRequest,
    ChatHistoryRequestUserFeedbackEnum,
    ChatHistoryInteraction,
    ChatHistoryInteractionUserFeedbackEnum,
    Suggestion as ChatSuggestion,
    ActionsApiAiChatRequest,
    ActionsApiAiChatStreamRequest,
    ActionsApiAiChatUsageRequest,
    ActionsApiAiChatHistoryRequest,
    ChatUsageResponse,
    ChatResult,
    ChatHistoryResult,
    FoundObjects,
    UserContext,
    CreatedVisualizations,
    ActiveObjectIdentification,
    AttributeNegativeFilter,
    AttributePositiveFilter,
    DateAbsoluteFilter,
    DateRelativeFilter,
    ActionsApiCancelExecutionsRequest,
    AfmCancelTokens,
    SavedVisualization,
    ActionsApiValidateLLMEndpointRequest,
    ActionsApiValidateLLMEndpointByIdRequest,
    ValidateLLMEndpointRequest,
    ValidateLLMEndpointResponse,
    ValidateLLMEndpointByIdRequest,
    ResolvedLlmEndpoint,
    ResolvedLlmEndpoints,
    ChatHistoryRequestResponseStateEnum,
    CreatedVisualizationFiltersInner,
    ElementsRequestDependsOnInner,
    AnalyticsCatalogCreatedBy as AfmAnalyticsCatalogCreatedBy,
    AnalyticsCatalogUser as AfmAnalyticsCatalogUser,
    AnalyticsCatalogTags as AfmAnalyticsCatalogTags,
    MemoryItemCreatedByUsers as AfmMemoryItemCreatedByUsers,
    MemoryItemUser as AfmMemoryItemUser,
    MetricValueChange as AfmMetricValueChange,
    QualityIssue as AfmQualityIssue,
    QualityIssueObject as AfmQualityIssueObject,
    GetQualityIssuesResponse as AfmGetQualityIssuesResponse,
    ActionsApiGetQualityIssuesRequest as AfmActionsApiGetQualityIssuesRequest,
    ActionsApiTriggerQualityIssuesCalculationRequest as AfmActionsApiTriggerQualityIssuesCalculationRequest,
    TriggerQualityIssuesCalculationResponse as AfmTriggerQualityIssuesCalculationResponse,
    ActionsApiGetQualityIssuesCalculationStatusRequest as AfmActionsApiGetQualityIssuesCalculationStatusRequest,
    QualityIssuesCalculationStatusResponse as AfmQualityIssuesCalculationStatusResponse,
    QualityIssuesCalculationStatusResponseStatusEnum as AfmQualityIssuesCalculationStatusResponseStatusEnum,
    ChangeAnalysisRequest as AfmChangeAnalysisRequest,
} from "./generated/afm-rest-api/api.js";
export type {
    AfmObjectIdentifierAttributeIdentifierTypeEnum as AfmModelObjectIdentifierAttributeIdentifierTypeEnum,
    AfmObjectIdentifierCoreIdentifierTypeEnum as AfmModelObjectIdentifierCoreIdentifierTypeEnum,
    AfmObjectIdentifierDatasetIdentifierTypeEnum as AfmModelObjectIdentifierDatasetIdentifierTypeEnum,
    AfmObjectIdentifierIdentifierTypeEnum as AfmModelObjectIdentifierIdentifierTypeEnum,
    AfmObjectIdentifierLabelIdentifierTypeEnum as AfmModelObjectIdentifierLabelIdentifierTypeEnum,
    AfmValidObjectsQueryTypesEnum,
    ArithmeticMeasureDefinitionArithmeticMeasureOperatorEnum as AfmArithmeticMeasureDefinitionArithmeticMeasureOperatorEnum,
    AttributeHeaderAttributeHeaderGranularityEnum,
    ComparisonMeasureValueFilterComparisonMeasureValueFilterOperatorEnum as AfmComparisonMeasureValueFilterComparisonMeasureValueFilterOperatorEnum,
    FilterByLabelTypeEnum,
    ElementsRequestSortOrderEnum,
    DateRelativeFilterGranularityEnum,
    RangeMeasureValueFilterRangeMeasureValueFilterOperatorEnum as AfmRangeMeasureValueFilterRangeMeasureValueFilterOperatorEnum,
    RankingFilterRankingFilterOperatorEnum as AfmRankingFilterRankingFilterOperatorEnum,
    RelativeDateFilterRelativeDateFilterGranularityEnum as AfmRelativeDateFilterRelativeDateFilterGranularityEnum,
    BoundedFilterGranularityEnum as AfmBoundedFilterGranularityEnum,
    SimpleMeasureDefinitionMeasureAggregationEnum as AfmSimpleMeasureDefinitionMeasureAggregationEnum,
    SortKeyTotalTotalDirectionEnum,
    SortKeyValueValueDirectionEnum,
    SortKeyAttributeAttributeDirectionEnum,
    SortKeyAttributeAttributeSortTypeEnum,
    ActionsApi as AfmActionsApi,
    TotalFunctionEnum,
    ElementsResponseGranularityEnum,
    AttributeHeaderAttributeHeaderValueTypeEnum,
    KeyDriversRequestSortDirectionEnum,
    KeyDriversDimensionGranularityEnum,
    KeyDriversDimensionValueTypeEnum,
    SearchRequestObjectTypesEnum,
    CreatedVisualizationVisualizationTypeEnum,
    MetricAggFunctionEnum,
} from "./generated/afm-rest-api/api.js";
export type {
    ActionsApiInterface as AuthActionsApiInterface,
    ActionsApiProcessInvitationRequest,
    Invitation,
} from "./generated/auth-json-api/api.js";
// export { ActionsApiFactory as AuthActionsApiFactory } from "./generated/auth-json-api/api.js";
export type { ConfigurationParameters } from "./generated/auth-json-api/configuration.js";
export { Configuration } from "./generated/auth-json-api/configuration.js";
export type {
    AutomationNotificationFilter,
    AutomationNotificationContent,
    AutomationFilterDefinition,
    AutomationAttributeElements,
    AutomationAttributeFilterElements,
    AutomationNegativeAttributeFilter,
    AutomationAttributeElementsByValue,
    AutomationNegativeAttributeFilterNegativeAttributeFilter,
    AutomationAutomationNotification,
    AutomationVisualExportRequest,
    AutomationSlidesExportRequest,
    AutomationImageExportRequest,
    AutomationAutomationImageExport,
    AutomationAutomationAlert,
    AutomationAlertAfm,
    AutomationAutomationExternalRecipient,
    AutomationTabularExportRequest,
    AutomationAFMFiltersInner,
    AutomationAdHocAutomation,
    AutomationVisibleFilter,
    AutomationBoundedFilter,
    AutomationAttributeFilter,
    AutomationAttributeFilterByDate,
    AutomationAttributeFilterParent,
    AutomationPositiveAttributeFilter,
    AutomationPopDate,
    AutomationPopDataset,
    AutomationDashboardDateFilterDateFilter,
    AutomationDateValue,
    ActionsAutomationGetNotificationsRequest,
    ActionsAutomationInterface,
    ActionsAutomationMarkAsReadNotificationRequest,
    ActionsAutomationMarkAsReadNotificationAllRequest,
    ActionsAutomationTestNotificationChannelRequest,
    ActionsAutomationTriggerAutomationRequest,
    AutomationTestDestinationRequest,
    ActionsAutomationTriggerExistingAutomationRequest,
    AutomationAbsoluteDateFilter,
    AutomationAbsoluteDateFilterAbsoluteDateFilter,
    AutomationAFM,
    AutomationAfmIdentifier,
    AutomationAfmLocalIdentifier,
    AutomationAfmObjectIdentifier,
    AutomationAfmObjectIdentifierCore,
    AutomationAfmObjectIdentifierAttribute,
    AutomationRelativeDateFilter,
    AutomationAbstractMeasureValueFilter,
    AutomationArithmeticMeasure,
    AutomationArithmeticMeasureDefinitionArithmeticMeasure,
    AutomationRangeMeasureValueFilter,
    AutomationInlineMeasureDefinition,
    AutomationInlineFilterDefinitionInline,
    AutomationAfmObjectIdentifierAttributeIdentifier,
    AutomationAfmObjectIdentifierCoreIdentifier,
    AutomationAfmObjectIdentifierDataset,
    AutomationIdentifierRefIdentifier,
    AutomationAfmObjectIdentifierDatasetIdentifier,
    AutomationAttributeElementsByRef,
    AutomationIdentifierRef,
    AutomationAfmObjectIdentifierIdentifier,
    AutomationAfmObjectIdentifierLabel,
    AutomationCustomLabel,
    AutomationRawCustomLabel,
    AutomationRawCustomMetric,
    AutomationRawCustomOverride,
    AutomationArithmeticMeasureDefinition,
    AutomationSimpleMeasureDefinition,
    AutomationMeasureItemDefinition,
    AutomationPopMeasureDefinition,
    AutomationPopDatasetMeasureDefinition,
    AutomationPopDateMeasureDefinition,
    AutomationAutomationAlertCondition,
    AutomationAlertDescription,
    AutomationAlertConditionOperand,
    AutomationAutomationMetadata,
    AutomationDashboardExportSettings,
    AutomationPdfTableStyleProperty,
    AutomationWebhookAutomationInfo,
    AutomationWebhookRecipient,
    AutomationPdfTableStyle,
    AutomationWebhookMessage,
    AutomationWebhookMessageData,
    AutomationNotificationData,
    AutomationNotificationsMeta,
    AutomationComparison,
    AutomationComparisonWrapper,
    AutomationCustomOverride,
    AutomationCustomMetric,
    AutomationMetricRecord,
    AutomationRelative,
    AutomationRelativeWrapper,
    AutomationRangeWrapper,
    AutomationRange,
    AutomationSettings,
    AutomationExecutionSettings,
    AutomationWebhook,
    AutomationNotificationsMetaTotal,
    AutomationTestNotification,
    AutomationTestResponse,
    AutomationNotification,
    AutomationNotifications,
    AutomationOver,
    AutomationInPlatform,
    AutomationSmtp,
    AutomationDefaultSmtp,
    AutomationAfmObjectIdentifierLabelIdentifier,
    AutomationLocalIdentifier,
    AutomationAttributeItem,
    AutomationAlertCondition,
    AutomationAlertEvaluationRow,
    AutomationAutomationTabularExport,
    AutomationExportResult,
    AutomationAutomationDashboardTabularExport,
    AutomationDashboardTabularExportRequestV2,
    AutomationDashboardFilter,
    AutomationDashboardAttributeFilter,
    AutomationDashboardDateFilter,
    AutomationDashboardDateFilterDateFilterFrom,
    AutomationPositiveAttributeFilterPositiveAttributeFilter,
    AutomationDashboardAttributeFilterAttributeFilter,
    AutomationDateFilter,
    AutomationRelativeDateFilterRelativeDateFilter,
    AutomationComparisonMeasureValueFilterComparisonMeasureValueFilter,
    AutomationMeasureDefinition,
    AutomationSimpleMeasureDefinitionMeasure,
    AutomationRangeMeasureValueFilterRangeMeasureValueFilter,
    AutomationRankingFilter,
    AutomationRankingFilterRankingFilter,
    AutomationAutomationSlidesExport,
    AutomationAutomationVisualExport,
    AutomationAutomationRawExport,
    AutomationRawExportAutomationRequest,
    AutomationTriggerAutomationRequest,
    AutomationTestDestinationRequestDestination,
    AutomationComparisonMeasureValueFilter,
    AutomationValue,
    AutomationMeasureValueFilter,
    AutomationMeasureItem,
    AutomationInlineMeasureDefinitionInline,
    AutomationInlineFilterDefinition,
    AutomationPopDateMeasureDefinitionOverPeriodMeasure,
    AutomationPopDatasetMeasureDefinitionPreviousPeriodMeasure,
    AutomationRelativeBoundedDateFilter,
    AutomationNotificationChannelDestination,
    AutomationDeclarativeNotificationChannelIdentifier,
    AutomationDeclarativeUserIdentifier,
    AutomationDeclarativeAnalyticalDashboardIdentifier,
    AutomationFilterDefinitionForSimpleMeasure,
    AutomationsAutomationInterface,
    AutomationsAutomationTriggerAutomationRequest,
    AutomationsAutomationTriggerExistingAutomationRequest,
    NotificationChannelsAutomationGetNotificationsRequest,
    NotificationChannelsAutomationInterface,
    NotificationChannelsAutomationMarkAsReadNotificationAllRequest,
    NotificationChannelsAutomationMarkAsReadNotificationRequest,
    NotificationChannelsAutomationTestNotificationChannelRequest,
    ActionsAutomationTestExistingNotificationChannelRequest,
    NotificationChannelsAutomationTestExistingNotificationChannelRequest,
} from "./generated/automation-json-api/index.js";
export type {
    ActionsAutomation,
    AutomationAfmObjectIdentifierAttributeIdentifierTypeEnum,
    AutomationAfmObjectIdentifierCoreIdentifierTypeEnum,
    AutomationAfmObjectIdentifierDatasetIdentifierTypeEnum,
    AutomationWebhookMessageTypeEnum,
    AutomationAfmObjectIdentifierIdentifierTypeEnum,
    AutomationAfmObjectIdentifierLabelIdentifierTypeEnum,
    AutomationAlertDescriptionStatusEnum,
    AutomationArithmeticMeasureOperatorEnum,
    AutomationArithmeticMeasureDefinitionArithmeticMeasureOperatorEnum,
    AutomationAutomationAlertTriggerEnum,
    AutomationBoundedFilterGranularityEnum,
    AutomationComparisonOperatorEnum,
    AutomationComparisonMeasureValueFilterComparisonMeasureValueFilterOperatorEnum,
    AutomationDashboardDateFilterDateFilterGranularityEnum,
    AutomationDashboardAttributeFilterAttributeFilterSelectionModeEnum,
    AutomationDashboardDateFilterDateFilterTypeEnum,
    AutomationDeclarativeAnalyticalDashboardIdentifierTypeEnum,
    AutomationDashboardTabularExportRequestV2FormatEnum,
    AutomationExportResultStatusEnum,
    AutomationImageExportRequestFormatEnum,
    AutomationDeclarativeNotificationChannelIdentifierTypeEnum,
    AutomationDeclarativeUserIdentifierTypeEnum,
    AutomationDefaultSmtpTypeEnum,
    AutomationInPlatformTypeEnum,
    AutomationIdentifierRefIdentifierTypeEnum,
    AutomationRangeOperatorEnum,
    AutomationRangeMeasureValueFilterRangeMeasureValueFilterOperatorEnum,
    AutomationRelativeOperatorEnum,
    AutomationRankingFilterRankingFilterOperatorEnum,
    AutomationRawExportAutomationRequestFormatEnum,
    AutomationRelativeBoundedDateFilterGranularityEnum,
    AutomationRelativeDateFilterRelativeDateFilterGranularityEnum,
    AutomationsAutomation,
    //AutomationsAutomationFactory,
    //    AutomationsAutomationAxiosParamCreator,
    //    AutomationsAutomationFp,
    AutomationSlidesExportRequestFormatEnum,
    AutomationSmtpPortEnum,
    AutomationSmtpTypeEnum,
    AutomationTabularExportRequestFormatEnum,
    AutomationWebhookTypeEnum,
    AutomationSimpleMeasureDefinitionMeasureAggregationEnum,
    //NotificationChannelsAutomationAxiosParamCreator,
    // NotificationChannelsAutomationFactory,
    NotificationChannelsAutomation,
    //NotificationChannelsAutomationFp,
} from "./generated/automation-json-api/index.js";
export type {
    Configuration as AutomationConfiguration,
    ConfigurationParameters as AutomationConfigurationParameters,
} from "./generated/automation-json-api/index.js";
export type {
    BaseAPI as AutomationBaseAPI,
    RequestArgs as AutomationRequestArgs,
} from "./generated/automation-json-api/base.js";
export * from "./generated/metadata-json-api/api.js";

export type {
    ActionsApiGetDataSourceSchemataRequest,
    ActionsApiScanDataSourceRequest,
    ActionsApiTestDataSourceDefinitionRequest,
    ActionsApiTestDataSourceRequest,
    DataSourceSchemata,
    DeclarativeColumn as ScanModelDeclarativeColumn,
    DeclarativeTable as ScanModelDeclarativeTable,
    DeclarativeTables as ScanModelDeclarativeTables,
    ScanRequest,
    ScanResultPdm,
    TableWarning,
    TestDefinitionRequest,
    TestQueryDuration,
    TestResponse,
    ColumnWarning,
    DataSourceParameter,
    TestRequest,
    ScanSqlResponse,
    ActionsApiScanSqlRequest,
    SqlColumn as ScanApiSqlColumn,
    ScanSqlRequest,
    ActionsApiColumnStatisticsRequest,
    ColumnStatisticsResponse,
    ColumnStatistic,
    Histogram,
    Frequency,
    ColumnStatisticWarning,
    ColumnStatisticsRequest,
    SqlQuery,
    Table,
    HistogramBucket,
    HistogramProperties,
    FrequencyBucket,
    FrequencyProperties,
    ColumnStatisticsRequestFrom,
} from "./generated/scan-json-api/api.js";
export type {
    DeclarativeColumnDataTypeEnum as ScanModelDeclarativeColumnDataTypeEnum,
    TestDefinitionRequestTypeEnum,
    SqlColumnDataTypeEnum as ScanApiSqlColumnDataTypeEnum,
    ColumnStatisticTypeEnum,
    ColumnStatisticsRequestStatisticsEnum,
} from "./generated/scan-json-api/api.js";

export type {
    ActionsApiAnalyzeCsvRequest,
    ActionsApiDeleteFilesRequest,
    ActionsApiImportCsvRequest,
    ActionsApiListFilesRequest,
    ActionsApiReadCsvFileManifestsRequest,
    ActionsApiStagingUploadRequest,
    AnalyzeCsvRequest,
    AnalyzeCsvRequestItem,
    AnalyzeCsvRequestItemConfig,
    AnalyzeCsvResponse,
    AnalyzeCsvResponseColumn,
    AnalyzeCsvResponseConfig,
    CacheRemovalInterval,
    CacheUsageData,
    CsvConvertOptions,
    CsvConvertOptionsColumnType,
    CsvManifestBody,
    CsvParseOptions,
    CsvReadOptions,
    DeleteFilesRequest,
    GdStorageFile,
    ImportCsvRequest,
    ImportCsvResponse,
    ImportCsvRequestTable,
    ImportCsvRequestTableSource,
    ImportCsvRequestTableSourceConfig,
    OrganizationCacheSettings,
    OrganizationCacheUsage,
    OrganizationCurrentCacheUsage,
    ReadCsvFileManifestsRequest,
    ReadCsvFileManifestsRequestItem,
    ReadCsvFileManifestsResponse,
    UploadFileResponse,
    WorkspaceCacheSettings,
    WorkspaceCacheUsage,
    WorkspaceCurrentCacheUsage,
} from "./generated/result-json-api/api.js";
export type { GdStorageFileTypeEnum } from "./generated/result-json-api/api.js";

export * from "./generated/export-json-api/index.js";
export type {
    Configuration as ExportConfiguration,
    ConfigurationParameters as ExportConfigurationParameters,
} from "./generated/export-json-api/index.js";
export type {
    BaseAPI as ExportBaseAPI,
    RequestArgs as ExportRequestArgs,
} from "./generated/export-json-api/base.js";

export * from "./client.js";

export { jsonApiHeaders, JSON_API_HEADER_VALUE, ValidateRelationsHeader } from "./constants.js";

export type {
    MetadataGetEntitiesResult,
    MetadataGetEntitiesFn,
    MetadataGetEntitiesOptions,
    MetadataGetEntitiesParams,
    MetadataGetEntitiesThemeParams,
    MetadataGetEntitiesColorPaletteParams,
    MetadataGetEntitiesWorkspaceParams,
    MetadataGetEntitiesUserParams,
} from "./metadataUtilities.js";
export { MetadataUtilities } from "./metadataUtilities.js";

export type {
    OrganizationGetEntitiesResult,
    OrganizationGetEntitiesSupportingIncludedResult,
    OrganizationGetEntitiesFn,
    OrganizationGetEntitiesParams,
} from "./organizationUtilities.js";
export { OrganizationUtilities } from "./organizationUtilities.js";

export { ActionsUtilities } from "./actionsUtilities.js";

export {
    AacApi_GetAnalyticsModelAac,
    AacApi_GetLogicalModelAac,
    AacApi_SetAnalyticsModelAac,
    AacApi_SetLogicalModelAac,
} from "./api-endpoints/aac/index.js";
export type {
    AacAnalyticsModel,
    AacAnalyticsModelExclude,
    AacLogicalModel,
    AacApiGetAnalyticsModelAacRequest,
    AacApiGetLogicalModelAacRequest,
    AacApiSetAnalyticsModelAacRequest,
    AacApiSetLogicalModelAacRequest,
} from "./api-endpoints/aac/index.js";

export const defaultTigerClient: ITigerClient = tigerClientFactory(defaultAxios);
/**
 * @deprecated This will be removed in the next major release, please use the named export "tigerFactory" instead
 */
// eslint-disable-next-line no-restricted-exports
export default defaultTigerClient;
