// (C) 2019-2026 GoodData Corporation

/* eslint-disable no-barrel-files/no-barrel-files */

/**
 * This package defines APIs for embedding and interfacing with the embedded GoodData applications - Analytical Designer and Dashboards/KPI Dashboards.
 *
 * @remarks
 * You can use this package to manipulate the embedded GoodData applications from your application by sending
 * commands to the embedded GoodData applications and receiving events from them.
 *
 * @packageDocumentation
 */

// EmbeddedGdc
export {
    type IAttributeFilterConfig,
    type IPositiveAttributeFilter,
    type INegativeAttributeFilter,
    type IAbsoluteDateFilter,
    type IRelativeDateFilter,
    type IRankingFilter,
    type AttributeFilterItem,
    type DateFilterItem,
    type FilterItem,
    type AttributeFilterItemSelectionMode,
    type IRemoveDateFilterItem,
    type IRemoveAttributeFilterItem,
    type IRemoveRankingFilterItem,
    type RemoveFilterItem,
    type IFilterContextContent,
    type IRemoveFilterContextContent,
    type AllTimeType,
    type AbsoluteType,
    type RelativeType,
    type DateString,
    type DateFilterGranularity,
    type IDashboardAllTimeDateFilter,
    type IDashboardAbsoluteDateFilter,
    type IDashboardRelativeDateFilter,
    type DashboardDateFilter,
    type IDashboardAttributeFilter,
    type IResolvedAttributeFilterValues,
    type IResolvedDateFilterValue,
    type ResolvedDateFilterValues,
    type IResolvedFilterValues,
    isDateFilter,
    isRelativeDateFilter,
    isAbsoluteDateFilter,
    isAttributeFilter,
    isPositiveAttributeFilter,
    isNegativeAttributeFilter,
    isRankingFilter,
    isRemoveDateFilter,
    isRemoveAttributeFilter,
    isRemoveRankingFilter,
    isDashboardDateFilter,
    isDashboardAllTimeDateFilter,
    isDashboardAbsoluteDateFilter,
    isDashboardRelativeDateFilter,
    isDashboardAttributeFilter,
} from "./iframe/EmbeddedGdc.js";

// EmbeddedAnalyticalDesigner
export {
    type IInsightExportConfig,
    type IGdcAdMessageEvent,
    type IGdcAdMessageEnvelope,
    type AdCommandFailed,
    type AdCommandFailedData,
    type AdDrillableItemsCommand,
    type AdDrillableItemsCommandData,
    type IAdOpenInsightCommandBody,
    type AdOpenInsightCommand,
    type AdOpenInsightCommandData,
    type AdClearCommand,
    type AdClearCommandData,
    type AdClearInsightCommand,
    type AdClearInsightCommandData,
    type AdRequestCancellationCommand,
    type AdRequestCancellationCommandData,
    type IAdSaveCommandBody,
    type AdSaveInsightCommand,
    type AdSaveInsightCommandData,
    type IAdSaveAsInsightCommandBody,
    type AdSaveAsInsightCommand,
    type AdSaveAsInsightCommandData,
    type IAdExportInsightCommandBody,
    type AdExportInsightCommand,
    type AdExportInsightCommandData,
    type AdUndoCommand,
    type AdUndoCommandData,
    type AdRedoCommand,
    type AdRedoCommandData,
    type AdSetFilterContextCommandData,
    type AdSetFilterContextCommand,
    type AdRemoveFilterContextCommandData,
    type AdRemoveFilterContextCommand,
    type IAdAvailableCommands,
    type AdNewInsightInitializedBody,
    type AdNewInsightInitialized,
    type AdNewInsightInitializedData,
    type AdInsightOpenedBody,
    type AdInsightOpened,
    type AdInsightOpenedData,
    type AdInsightRenderedBody,
    type AdInsightRendered,
    type AdInsightRenderedData,
    type AdClearFinished,
    type AdClearFinishedData,
    type AdClearInsightFinished,
    type AdClearInsightFinishedData,
    type AdInsightSavedBody,
    type AdInsightSaved,
    type AdInsightSavedData,
    type AdExportFinishedBody,
    type AdExportFinished,
    type AdExportFinishedData,
    type AdUndoFinishedBody,
    type AdUndoFinished,
    type AdUndoFinishedData,
    type AdRedoFinishedBody,
    type AdRedoFinished,
    type AdRedoFinishedData,
    type AdSetFilterContextFinishedData,
    type AdRemoveFilterContextFinishedData,
    type AdFilterContextChangedBody,
    type AdFilterContextChangedData,
    type AdInsightChangedBody,
    type AdInsightChangedData,
    type IAdSetApiTokenBody,
    type AdSetApiTokenCommand,
    type AdSetApiTokenCommandData,
    type AdAttributeHierarchyModifiedCommand,
    type AdAttributeHierarchyModifiedCommandData,
    GdcAdCommandType,
    GdcAdEventType,
    isAdCommandFailedData,
    isAdDrillableItemsCommandData,
    isAdOpenInsightCommandData,
    isAdClearCommandData,
    isAdClearInsightCommandData,
    isAdRequestCancellationCommandData,
    isAdSaveInsightCommandData,
    isAdSaveAsInsightCommandData,
    isAdExportInsightCommandData,
    isAdUndoCommandData,
    isAdRedoCommandData,
    isAdSetFilterContextCommandData,
    isAdRemoveFilterContextCommandData,
    isAdNewInsightInitializedData,
    isAdInsightOpenedData,
    isAdInsightRenderedData,
    isAdClearFinishedData,
    isAdClearInsightFinishedData,
    isAdInsightSavedData,
    isAdExportFinishedData,
    isAdUndoFinishedData,
    isAdRedoFinishedData,
    isAdSetApiTokenCommandData,
    isAttributeHierarchyModifiedCommandData,
} from "./iframe/EmbeddedAnalyticalDesigner.js";

// EmbeddedKpiDashboard
export {
    type IGdcKdMessageEvent,
    type IGdcKdMessageEnvelope,
    type IKdAvailableCommands,
    type IKdSaveCommandBody,
    type KdSaveDashboardCommand,
    type KdSaveDashboardCommandData,
    type KdSaveAsDashboardCommand,
    type KdSaveAsDashboardCommandData,
    type KdCancelEditCommand,
    type KdCancelEditCommandData,
    type KdDeleteDashboardCommand,
    type KdDeleteDashboardCommandData,
    type KdSwitchToEditCommand,
    type KdSwitchToEditCommandData,
    type KdDrillableItemsCommand,
    type KdDrillableItemsCommandData,
    type IKdSetSizeCommandBody,
    type KdSetSizeCommand,
    type KdSetSizeCommandData,
    type KdSetFilterContextCommandData,
    type KdSetFilterContextCommand,
    type KdRemoveFilterContextCommandData,
    type KdRemoveFilterContextCommand,
    type IKdKpiWidget,
    type IKdIdentifierInsightRef,
    type IKdUriInsightRef,
    type IKdInsightWidget,
    type IKdAddWidgetBody,
    type KdAddWidgetCommand,
    type KdAddWidgetCommandData,
    type KdAddFilterCommand,
    type KdAddFilterCommandData,
    type KdExportToPdfCommand,
    type KdExportToPdfCommandData,
    type IKdNoPermissionsBody,
    type KdNoPermissionsEventData,
    type IKdResizedBody,
    type KdResizedEventData,
    type IKdDashboardObjectMeta,
    type KdDashboardBody,
    type IKdDashboardCreatedData,
    type IKdDashboardLoadedData,
    type IKdDashboardUpdatedData,
    type IKdDashboardSavedData,
    type IKdDashboardDeletedData,
    type KdSwitchedToEditData,
    type KdSwitchedToViewData,
    type IKdPlatformBody,
    type KdPlatformData,
    type IKdInsightWidgetBody,
    type IKdAddedWidgetBody,
    type KdWidgetAddedData,
    type KdFilterAddedBody,
    type KdFilterAddedData,
    type KdExportToPdfFinishedBody,
    type KdExportToPdfFinishedData,
    type KdSetFilterContextFinishedData,
    type KdRemoveFilterContextFinishedData,
    type KdFilterContextChangedBody,
    type KdFilterContextChangedData,
    type KdDrillToUrlFilters,
    type IKdDrillToUrlStartedDataBody,
    type IKdDrillToUrlResolvedDataBody,
    type KdDrillToUrlStartedData,
    type KdDrillToUrlResolvedData,
    type IKdSetFilterParentsAttributeFilter,
    type KdSetFilterParentsItemFilter,
    type IKdSetFilterParentsItemParent,
    type IKdSetFilterParentsItem,
    type IKdSetFilterParentsDataBody,
    type KdSetFilterParentsCommand,
    type KdSetFilterParentsCommandData,
    type KdSetFilterParentsFinished,
    type KdSetFilterParentsFinishedData,
    type IKdSetFilterParentsFailedDataBody,
    type KdSetFilterParentsFailed,
    type KdSetFilterParentsFailedData,
    type IKdInsightSavedBody,
    type KdInsightSavedData,
    type KdOpenDeleteDashboardDialogCommand,
    type KdOpenDeleteDashboardDialogCommandData,
    type IKdSetApiTokenBody,
    type KdSetApiTokenCommand,
    type KdSetApiTokenCommandData,
    GdcKdCommandType,
    GdcKdEventType,
    KdSetFilterParentsErrorCode,
    isKdSaveDashboardCommandData,
    isKdSaveAsDashboardCommandData,
    isKdCancelEditCommandData,
    isKdSwitchToEditCommandData,
    isKdDrillableItemsCommandData,
    isKdSetSizeCommandData,
    isKdSetFilterContextCommandData,
    isKdRemoveFilterContextCommandData,
    isKdIdentifierInsight,
    isKdUriInsight,
    isKdAddWidgetCommandData,
    isKdAddFilterCommandData,
    isKdExportToPdfCommandData,
    isKdSetFilterParentsCommandData,
    isKdOpenDeleteDashboardDialogCommandData,
    isKdSetApiTokenCommandData,
} from "./iframe/EmbeddedKpiDashboard.js";

// legacyTypes
export {
    type ILegacyBaseExportConfig,
    type IVisualizationObjectRelativeDateFilter,
    type IVisualizationObjectAbsoluteDateFilter,
    type IVisualizationObjectPositiveAttributeFilter,
    type IVisualizationObjectNegativeAttributeFilter,
    type VisualizationObjectAttributeFilter,
    type VisualizationObjectDateFilter,
    type VisualizationObjectFilter,
    type ArithmeticMeasureOperator,
    type MeasureAggregation,
    type IPreviousPeriodDateDataSet,
    type IObjUriQualifier,
    type IObjIdentifierQualifier,
    type ObjQualifier,
    type IVisualizationObjectMeasureDefinition,
    type IVisualizationObjectArithmeticMeasureDefinition,
    type IVisualizationObjectPoPMeasureDefinition,
    type IVisualizationObjectPreviousPeriodMeasureDefinition,
    type VisualizationObjectMeasureDefinitionType,
    type IMeasureContent,
    type IVisualizationObjectMeasure,
    type IVisualizationObjectAttribute,
    type IVisualizationAttributeContent,
    type BucketItem,
    type Identifier,
    type TotalType,
    type ITotal,
    type IBucket,
    type ILocalIdentifierQualifier,
    type ComparisonConditionOperator,
    type IComparisonCondition,
    type RangeConditionOperator,
    type IRangeCondition,
    type MeasureValueFilterCondition,
    type IVisualizationObjectMeasureValueFilter,
    type RankingFilterOperator,
    type IVisualizationObjectRankingFilter,
    type VisualizationObjectExtendedFilter,
    type IReferenceItems,
    type IVisualizationObjectContent,
    type ObjectCategory,
    type Timestamp,
    type ILegacyObjectMeta,
    type IVisualizationObject,
    type IVisualization,
    isObjIdentifierQualifier,
    isObjectUriQualifier,
    isLocalIdentifierQualifier,
} from "./iframe/legacyTypes.js";

// common
export {
    type IObjectMeta,
    type IPostMessageContextPayload,
    type GdcMessageEventListener,
    type IGdcMessage,
    type IGdcMessageEnvelope,
    type IGdcMessageEvent,
    type IGdcMessageEventListenerConfig,
    type CommandFailed,
    type CommandFailedData,
    type ICommandFailedBody,
    type IDrillableItemsCommandBody,
    type ISimpleDrillableItemsCommandBody,
    GdcErrorType,
    GdcEventType,
    GdcProductName,
    isCommandFailedData,
    getEventType,
} from "./iframe/common.js";
