// (C) 2020-2025 GoodData Corporation

import { convertState } from "./state.js";
import { FeatureFlagsValues, ITigerFeatureFlags, TigerFeaturesNames } from "../uiFeatures.js";

export type FeatureDef = {
    id: string;
    key: string;
    l: boolean;
    version: string;
    type: "BOOLEAN" | "STRING" | "NUMBER" | "JSON";
    value: any;
};

export type FeaturesMap = Record<string, FeatureDef>;

export function mapFeatures(features: FeaturesMap): Partial<ITigerFeatureFlags> {
    return {
        ...loadFeature(
            features,
            TigerFeaturesNames.EnableKPIDashboardExportPDF,
            "enableKPIDashboardExportPDF",
            "BOOLEAN",
            FeatureFlagsValues.enableKPIDashboardExportPDF,
        ),
        ...loadFeature(
            features,
            TigerFeaturesNames.DashboardEditModeDevRollout,
            "dashboardEditModeDevRollout",
            "BOOLEAN",
            FeatureFlagsValues.dashboardEditModeDevRollout,
        ),
        ...loadFeature(
            features,
            TigerFeaturesNames.EnableMetricSqlAndDataExplain,
            "enableMetricSqlAndDataExplain",
            "BOOLEAN",
            FeatureFlagsValues.enableMetricSqlAndDataExplain,
        ),
        ...loadFeature(
            features,
            TigerFeaturesNames.EnableDescriptions,
            "enableDescriptions",
            "BOOLEAN",
            FeatureFlagsValues.enableDescriptions,
        ),
        ...loadFeature(
            features,
            TigerFeaturesNames.EnableFunnelChart,
            "enableFunnelChart",
            "BOOLEAN",
            FeatureFlagsValues.enableFunnelChart,
        ),
        ...loadFeature(
            features,
            TigerFeaturesNames.EnablePyramidChart,
            "enablePyramidChart",
            "BOOLEAN",
            FeatureFlagsValues.enablePyramidChart,
        ),
        ...loadFeature(
            features,
            TigerFeaturesNames.EnableSankeyChart,
            "enableSankeyChart",
            "BOOLEAN",
            FeatureFlagsValues.enableSankeyChart,
        ),
        ...loadFeature(
            features,
            TigerFeaturesNames.EnableDependencyWheelChart,
            "enableDependencyWheelChart",
            "BOOLEAN",
            FeatureFlagsValues.enableDependencyWheelChart,
        ),
        ...loadFeature(
            features,
            TigerFeaturesNames.EnableWaterfallChart,
            "enableWaterfallChart",
            "BOOLEAN",
            FeatureFlagsValues.enableWaterfallChart,
        ),
        ...loadFeature(
            features,
            TigerFeaturesNames.EnableSqlDatasets,
            "enableSqlDatasets",
            "BOOLEAN",
            FeatureFlagsValues.enableSqlDatasets,
        ),
        ...loadFeature(
            features,
            TigerFeaturesNames.EnableCompositeGrain,
            "enableCompositeGrain",
            "BOOLEAN",
            FeatureFlagsValues.enableCompositeGrain,
        ),
        ...loadFeature(
            features,
            TigerFeaturesNames.EnableTableTotalRows,
            "enableTableTotalRows",
            "BOOLEAN",
            FeatureFlagsValues.enableTableTotalRows,
        ),
        ...loadFeature(
            features,
            TigerFeaturesNames.EnablePivotTableIncreaseBucketSize,
            "enablePivotTableIncreaseBucketSize",
            "BOOLEAN",
            FeatureFlagsValues.enablePivotTableIncreaseBucketSize,
        ),
        ...loadFeature(
            features,
            TigerFeaturesNames.EnableUserManagement,
            "enableUserManagement",
            "BOOLEAN",
            FeatureFlagsValues.enableUserManagement,
        ),
        ...loadFeature(
            features,
            TigerFeaturesNames.EnableKDSavedFilters,
            "enableKDSavedFilters",
            "BOOLEAN",
            FeatureFlagsValues.enableKDSavedFilters,
        ),
        ...loadFeature(
            features,
            TigerFeaturesNames.EnableClickHouseDataSource,
            "enableClickHouseDataSource",
            "BOOLEAN",
            FeatureFlagsValues.enableClickHouseDataSource,
        ),
        ...loadFeature(
            features,
            TigerFeaturesNames.EnableKDCrossFiltering,
            "enableKDCrossFiltering",
            "BOOLEAN",
            FeatureFlagsValues.enableKDCrossFiltering,
        ),
        ...loadFeature(
            features,
            TigerFeaturesNames.EnableChangeAnalysis,
            "enableChangeAnalysis",
            "BOOLEAN",
            FeatureFlagsValues.enableChangeAnalysis,
        ),
        ...loadFeature(
            features,
            TigerFeaturesNames.EnableMultipleDateFilters,
            "enableMultipleDateFilters",
            "BOOLEAN",
            FeatureFlagsValues.enableMultipleDateFilters,
        ),
        ...loadFeature(
            features,
            TigerFeaturesNames.EnableKDRichText,
            "enableKDRichText",
            "BOOLEAN",
            FeatureFlagsValues.enableKDRichText,
        ),
        ...loadFeature(
            features,
            TigerFeaturesNames.EnableMySqlDataSource,
            "enableMySqlDataSource",
            "BOOLEAN",
            FeatureFlagsValues.enableMySqlDataSource,
        ),
        ...loadFeature(
            features,
            TigerFeaturesNames.EnableCreateUser,
            "enableCreateUser",
            "BOOLEAN",
            FeatureFlagsValues.enableCreateUser,
        ),
        ...loadFeature(
            features,
            TigerFeaturesNames.EnableMariaDbDataSource,
            "enableMariaDbDataSource",
            "BOOLEAN",
            FeatureFlagsValues.enableMariaDbDataSource,
        ),
        ...loadFeature(
            features,
            TigerFeaturesNames.EnableRepeaterChart,
            "enableRepeaterChart",
            "BOOLEAN",
            FeatureFlagsValues.enableRepeaterChart,
        ),
        ...loadFeature(
            features,
            TigerFeaturesNames.EnableKDAttributeFilterDatesValidation,
            "enableKDAttributeFilterDatesValidation",
            "BOOLEAN",
            FeatureFlagsValues.enableKDAttributeFilterDatesValidation,
        ),
        ...loadFeature(
            features,
            TigerFeaturesNames.EnableOracleDataSource,
            "enableOracleDataSource",
            "BOOLEAN",
            FeatureFlagsValues.enableOracleDataSource,
        ),
        ...loadFeature(
            features,
            TigerFeaturesNames.EnableAnalyticalCatalog,
            "enableAnalyticalCatalog",
            "BOOLEAN",
            FeatureFlagsValues.enableAnalyticalCatalog,
        ),
        ...loadFeature(
            features,
            TigerFeaturesNames.EnableAlerting,
            "enableAlerting",
            "BOOLEAN",
            FeatureFlagsValues.enableAlerting,
        ),
        ...loadFeature(
            features,
            TigerFeaturesNames.EnableAlertingAttributes,
            "enableAlertAttributes",
            "BOOLEAN",
            FeatureFlagsValues.enableAlertAttributes,
        ),
        ...loadFeature(
            features,
            TigerFeaturesNames.EnableComparisonInAlerting,
            "enableComparisonInAlerting",
            "BOOLEAN",
            FeatureFlagsValues.enableComparisonInAlerting,
        ),
        ...loadFeature(
            features,
            TigerFeaturesNames.EnableAlertingRollout,
            "enableAlertingRollout",
            "BOOLEAN",
            FeatureFlagsValues.enableAlertingRollout,
        ),
        ...loadFeature(
            features,
            TigerFeaturesNames.EnableScheduling,
            "enableScheduling",
            "BOOLEAN",
            FeatureFlagsValues.enableScheduling,
        ),
        ...loadFeature(
            features,
            TigerFeaturesNames.EnableSmtp,
            "enableSmtp",
            "BOOLEAN",
            FeatureFlagsValues.enableSmtp,
        ),
        ...loadFeature(
            features,
            TigerFeaturesNames.EnableDestinationTesting,
            "enableDestinationTesting",
            "BOOLEAN",
            FeatureFlagsValues.enableDestinationTesting,
        ),
        ...loadFeature(
            features,
            TigerFeaturesNames.EnableLabsSmartFunctions,
            "enableLabsSmartFunctions",
            "BOOLEAN",
            FeatureFlagsValues.enableLabsSmartFunctions,
        ),
        ...loadFeature(
            features,
            TigerFeaturesNames.EnableSmartFunctions,
            "enableSmartFunctions",
            "BOOLEAN",
            FeatureFlagsValues.enableSmartFunctions,
        ),
        ...loadFeature(
            features,
            TigerFeaturesNames.EnableMotherDuckDataSource,
            "enableMotherDuckDataSource",
            "BOOLEAN",
            FeatureFlagsValues.enableMotherDuckDataSource,
        ),
        ...loadFeature(
            features,
            TigerFeaturesNames.EnableMongoDbDataSource,
            "enableMongoDbDataSource",
            "BOOLEAN",
            FeatureFlagsValues.enableMongoDbDataSource,
        ),
        ...loadFeature(
            features,
            TigerFeaturesNames.EnableKeyDriverAnalysis,
            "enableKeyDriverAnalysis",
            "BOOLEAN",
            FeatureFlagsValues.enableKeyDriverAnalysis,
        ),
        ...loadFeature(
            features,
            TigerFeaturesNames.EnableDataProfiling,
            "enableDataProfiling",
            "BOOLEAN",
            FeatureFlagsValues.enableDataProfiling,
        ),
        ...loadFeature(
            features,
            TigerFeaturesNames.EnableFlexAi,
            "enableFlexAi",
            "BOOLEAN",
            FeatureFlagsValues.enableFlexAi,
        ),
        ...loadFeature(
            features,
            TigerFeaturesNames.EnableExperimentalFeaturesUI,
            "enableExperimentalFeaturesUI",
            "BOOLEAN",
            FeatureFlagsValues.enableExperimentalFeaturesUI,
        ),
        ...loadFeature(
            features,
            TigerFeaturesNames.EnableSingleStoreDataSource,
            "enableSingleStoreDataSource",
            "BOOLEAN",
            FeatureFlagsValues.enableSingleStoreDataSource,
        ),
        ...loadFeature(
            features,
            TigerFeaturesNames.EnableSnowflakeKeyPairAuthentication,
            "enableSnowflakeKeyPairAuthentication",
            "BOOLEAN",
            FeatureFlagsValues.enableSnowflakeKeyPairAuthentication,
        ),
        ...loadFeature(
            features,
            TigerFeaturesNames.EnableMultipleDataSourcesInWorkspace,
            "enableMultipleDataSourcesInWorkspace",
            "BOOLEAN",
            FeatureFlagsValues.enableMultipleDataSourcesInWorkspace,
        ),
        ...loadFeature(
            features,
            TigerFeaturesNames.EnableScatterPlotSegmentation,
            "enableScatterPlotSegmentation",
            "BOOLEAN",
            FeatureFlagsValues.enableScatterPlotSegmentation,
        ),
        ...loadFeature(
            features,
            TigerFeaturesNames.EnableScatterPlotClustering,
            "enableScatterPlotClustering",
            "BOOLEAN",
            FeatureFlagsValues.enableScatterPlotClustering,
        ),
        ...loadFeature(
            features,
            TigerFeaturesNames.EnableRichTextDescriptions,
            "enableRichTextDescriptions",
            "BOOLEAN",
            FeatureFlagsValues.enableRichTextDescriptions,
        ),
        ...loadFeature(
            features,
            TigerFeaturesNames.EnableSchedulingRollout,
            "enableSchedulingRollout",
            "BOOLEAN",
            FeatureFlagsValues.enableSchedulingRollout,
        ),
        ...loadFeature(
            features,
            TigerFeaturesNames.EnableWidgetIdentifiersRollout,
            "enableWidgetIdentifiersRollout",
            "BOOLEAN",
            FeatureFlagsValues.enableWidgetIdentifiersRollout,
        ),
        ...loadFeature(
            features,
            TigerFeaturesNames.EnableAIFunctions,
            "enableAIFunctions",
            "BOOLEAN",
            FeatureFlagsValues.enableAIFunctions,
        ),
        ...loadFeature(
            features,
            TigerFeaturesNames.EnableSemanticSearch,
            "enableSemanticSearch",
            "BOOLEAN",
            FeatureFlagsValues.enableSemanticSearch,
        ),
        ...loadFeature(
            features,
            TigerFeaturesNames.EnableSemanticSearchRollout,
            "enableSemanticSearchRollout",
            "BOOLEAN",
            FeatureFlagsValues.enableSemanticSearchRollout,
        ),
        ...loadFeature(
            features,
            TigerFeaturesNames.EnableGenAIChat,
            "enableGenAIChat",
            "BOOLEAN",
            FeatureFlagsValues.enableGenAIChat,
        ),
        ...loadFeature(
            features,
            TigerFeaturesNames.EnableGenAIChatRollout,
            "enableGenAIChatRollout",
            "BOOLEAN",
            FeatureFlagsValues.enableGenAIChatRollout,
        ),
        ...loadFeature(
            features,
            TigerFeaturesNames.EnableGenAICatalogQualityChecker,
            "enableGenAICatalogQualityChecker",
            "BOOLEAN",
            FeatureFlagsValues.enableGenAICatalogQualityChecker,
        ),
        ...loadFeature(
            features,
            TigerFeaturesNames.EnableDashboardFilterViews,
            "enableDashboardFilterViews",
            "BOOLEAN",
            FeatureFlagsValues.enableDashboardFilterViews,
        ),
        ...loadFeature(
            features,
            TigerFeaturesNames.EnableNewInsightChangedPostMessageEvent,
            "enableNewInsightChangedPostMessageEvent",
            "BOOLEAN",
            FeatureFlagsValues.enableNewInsightChangedPostMessageEvent,
        ),
        ...loadFeature(
            features,
            TigerFeaturesNames.EnableKDVisualizationSwitcher,
            "enableKDVisualizationSwitcher",
            "BOOLEAN",
            FeatureFlagsValues.enableKDVisualizationSwitcher,
        ),
        ...loadFeature(
            features,
            TigerFeaturesNames.EnableIgnoreCrossFiltering,
            "enableIgnoreCrossFiltering",
            "BOOLEAN",
            FeatureFlagsValues.enableIgnoreCrossFiltering,
        ),
        ...loadFeature(
            features,
            TigerFeaturesNames.EnableHeadlineExport,
            "enableHeadlineExport",
            "BOOLEAN",
            FeatureFlagsValues.enableHeadlineExport,
        ),
        ...loadFeature(
            features,
            TigerFeaturesNames.EarlyAccessFeatures,
            "earlyAccessFeatures",
            "JSON",
            FeatureFlagsValues.earlyAccessFeatures,
        ),
        ...loadFeature(
            features,
            TigerFeaturesNames.EnableCrossFilteringAliasTitles,
            "enableCrossFilteringAliasTitles",
            "BOOLEAN",
            FeatureFlagsValues.enableCrossFilteringAliasTitles,
        ),
        ...loadFeature(
            features,
            TigerFeaturesNames.EnableDefaultSmtp,
            "enableDefaultSmtp",
            "BOOLEAN",
            FeatureFlagsValues.enableDefaultSmtp,
        ),
        ...loadFeature(
            features,
            TigerFeaturesNames.EnableNumberSeparators,
            "enableNumberSeparators",
            "BOOLEAN",
            FeatureFlagsValues.enableNumberSeparators,
        ),
        ...loadFeature(
            features,
            TigerFeaturesNames.EnableInPlatformNotifications,
            "enableInPlatformNotifications",
            "BOOLEAN",
            FeatureFlagsValues.enableInPlatformNotifications,
        ),
        ...loadFeature(
            features,
            TigerFeaturesNames.EnableVisualizationFineTuning,
            "enableVisualizationFineTuning",
            "BOOLEAN",
            FeatureFlagsValues.enableVisualizationFineTuning,
        ),
        ...loadFeature(
            features,
            TigerFeaturesNames.EnableExternalRecipients,
            "enableExternalRecipients",
            "BOOLEAN",
            FeatureFlagsValues.enableExternalRecipients,
        ),
        ...loadFeature(
            features,
            TigerFeaturesNames.EnableDashboardTabularExport,
            "enableDashboardTabularExport",
            "BOOLEAN",
            FeatureFlagsValues.enableDashboardTabularExport,
        ),
        ...loadFeature(
            features,
            TigerFeaturesNames.EnableOrchestratedTabularExports,
            "enableOrchestratedTabularExports",
            "BOOLEAN",
            FeatureFlagsValues.enableOrchestratedTabularExports,
        ),
        ...loadFeature(
            features,
            TigerFeaturesNames.EnableDrilledTooltip,
            "enableDrilledTooltip",
            "BOOLEAN",
            FeatureFlagsValues.enableDrilledTooltip,
        ),
        ...loadFeature(
            features,
            TigerFeaturesNames.EnableDashboardDescriptionDynamicHeight,
            "enableDashboardDescriptionDynamicHeight",
            "BOOLEAN",
            FeatureFlagsValues.enableDashboardDescriptionDynamicHeight,
        ),
        ...loadFeature(
            features,
            TigerFeaturesNames.EnableAmplitudeTracker,
            "enableAmplitudeTracker",
            "BOOLEAN",
            FeatureFlagsValues.enableAmplitudeTracker,
        ),
        ...loadFeature(
            features,
            TigerFeaturesNames.EnableSlideshowExports,
            "enableSlideshowExports",
            "BOOLEAN",
            FeatureFlagsValues.enableSlideshowExports,
        ),
        ...loadFeature(
            features,
            TigerFeaturesNames.EnableRawExports,
            "enableRawExports",
            "BOOLEAN",
            FeatureFlagsValues.enableRawExports,
        ),
        ...loadFeature(
            features,
            TigerFeaturesNames.EnableChartAccessibilityFeatures,
            "enableChartAccessibilityFeatures",
            "BOOLEAN",
            FeatureFlagsValues.enableChartAccessibilityFeatures,
        ),
        ...loadFeature(
            features,
            TigerFeaturesNames.EnableDashboardFiltersApplyModes,
            "enableDashboardFiltersApplyModes",
            "BOOLEAN",
            FeatureFlagsValues.enableDashboardFiltersApplyModes,
        ),
        ...loadFeature(
            features,
            TigerFeaturesNames.EnableExecutionCancelling,
            "enableExecutionCancelling",
            "BOOLEAN",
            FeatureFlagsValues.enableExecutionCancelling,
        ),
        ...loadFeature(
            features,
            TigerFeaturesNames.EnableImmediateAttributeFilterDisplayAsLabelMigration,
            "enableImmediateAttributeFilterDisplayAsLabelMigration",
            "BOOLEAN",
            FeatureFlagsValues.enableImmediateAttributeFilterDisplayAsLabelMigration,
        ),
        ...loadFeature(
            features,
            TigerFeaturesNames.EnableRichTextDynamicReferences,
            "enableRichTextDynamicReferences",
            "BOOLEAN",
            FeatureFlagsValues.enableRichTextDynamicReferences,
        ),
        ...loadFeature(
            features,
            TigerFeaturesNames.EnableAnalyticalDesignerCatalogSideload,
            "enableAnalyticalDesignerCatalogSideload",
            "BOOLEAN",
            FeatureFlagsValues.enableAnalyticalDesignerCatalogSideload,
        ),
        ...loadFeature(
            features,
            TigerFeaturesNames.EnableDashboardShareLink,
            "enableDashboardShareLink",
            "BOOLEAN",
            FeatureFlagsValues.enableDashboardShareLink,
        ),
        ...loadFeature(
            features,
            TigerFeaturesNames.EnableHighchartsAccessibility,
            "enableHighchartsAccessibility",
            "BOOLEAN",
            FeatureFlagsValues.enableHighchartsAccessibility,
        ),
        ...loadFeature(
            features,
            TigerFeaturesNames.EnableAccessibleChartTooltip,
            "enableAccessibleChartTooltip",
            "BOOLEAN",
            FeatureFlagsValues.enableAccessibleChartTooltip,
        ),
        ...loadFeature(
            features,
            TigerFeaturesNames.EnableExecutionTimestamp,
            "enableExecutionTimestamp",
            "BOOLEAN",
            FeatureFlagsValues.enableExecutionTimestamp,
        ),
        ...loadFeature(
            features,
            TigerFeaturesNames.EnableAutomationFilterContext,
            "enableAutomationFilterContext",
            "BOOLEAN",
            FeatureFlagsValues.enableAutomationFilterContext,
        ),
        ...loadFeature(
            features,
            TigerFeaturesNames.EnableDateFilterIdentifiersRollout,
            "enableDateFilterIdentifiersRollout",
            "BOOLEAN",
            FeatureFlagsValues.enableDateFilterIdentifiersRollout,
        ),
        ...loadFeature(
            features,
            TigerFeaturesNames.EnableAlertsEvaluationFrequencySetup,
            "enableAlertsEvaluationFrequencySetup",
            "BOOLEAN",
            FeatureFlagsValues.enableAlertsEvaluationFrequencySetup,
        ),
        ...loadFeature(
            features,
            TigerFeaturesNames.EnableRichTooManyDatapointsErrors,
            "enableRichTooManyDatapointsErrors",
            "BOOLEAN",
            FeatureFlagsValues.enableRichTooManyDatapointsErrors,
        ),
        ...loadFeature(
            features,
            TigerFeaturesNames.EnableLineChartTrendThreshold,
            "enableLineChartTrendThreshold",
            "BOOLEAN",
            FeatureFlagsValues.enableLineChartTrendThreshold,
        ),
        ...loadFeature(
            features,
            TigerFeaturesNames.EnableKDRespectLegendPosition,
            "enableKDRespectLegendPosition",
            "BOOLEAN",
            FeatureFlagsValues.enableKDRespectLegendPosition,
        ),
        ...loadFeature(
            features,
            TigerFeaturesNames.EnableWorkspaceSettingsAppHeaderMenuItem,
            "enableWorkspaceSettingsAppHeaderMenuItem",
            "BOOLEAN",
            FeatureFlagsValues.enableWorkspaceSettingsAppHeaderMenuItem,
        ),
        ...loadFeature(
            features,
            TigerFeaturesNames.EnableSnapshotExportAccessibility,
            "enableSnapshotExportAccessibility",
            "BOOLEAN",
            FeatureFlagsValues.enableSnapshotExportAccessibility,
        ),
        ...loadFeature(
            features,
            TigerFeaturesNames.EnableWidgetExportPngImage,
            "enableWidgetExportPngImage",
            "BOOLEAN",
            FeatureFlagsValues.enableWidgetExportPngImage,
        ),
        ...loadFeature(
            features,
            TigerFeaturesNames.EnableExportToDocumentStorage,
            "enableExportToDocumentStorage",
            "BOOLEAN",
            FeatureFlagsValues.enableExportToDocumentStorage,
        ),
        ...loadFeature(
            features,
            TigerFeaturesNames.EnableAttributeFilterVirtualised,
            "enableAttributeFilterVirtualised",
            "BOOLEAN",
            FeatureFlagsValues.enableAttributeFilterVirtualised,
        ),
        ...loadFeature(
            features,
            TigerFeaturesNames.EnableNotificationChannelIdentifiers,
            "enableNotificationChannelIdentifiers",
            "BOOLEAN",
            FeatureFlagsValues.enableNotificationChannelIdentifiers,
        ),
        ...loadFeature(
            features,
            TigerFeaturesNames.EnableDashboardShareDialogLink,
            "enableDashboardShareDialogLink",
            "BOOLEAN",
            FeatureFlagsValues.enableDashboardShareDialogLink,
        ),
        ...loadFeature(
            features,
            TigerFeaturesNames.ProductionFeatures,
            "productionFeatures",
            "JSON",
            FeatureFlagsValues.productionFeatures,
        ),
        ...loadFeature(
            features,
            TigerFeaturesNames.EnableNewScheduledExport,
            "enableNewScheduledExport",
            "BOOLEAN",
            FeatureFlagsValues.enableNewScheduledExport,
        ),
        ...loadFeature(
            features,
            TigerFeaturesNames.EnableSeamlessIdpSwitch,
            "enableSeamlessIdpSwitch",
            "BOOLEAN",
            FeatureFlagsValues.enableSeamlessIdpSwitch,
        ),
        ...loadFeature(
            features,
            TigerFeaturesNames.EnablePreAggregationDatasets,
            "enablePreAggregationDatasets",
            "BOOLEAN",
            FeatureFlagsValues.enablePreAggregationDatasets,
        ),
        ...loadFeature(
            features,
            TigerFeaturesNames.EnableToDateFilters,
            "enableToDateFilters",
            "BOOLEAN",
            FeatureFlagsValues.enableToDateFilters,
        ),
        ...loadFeature(
            features,
            TigerFeaturesNames.EnableCyclicalToDateFilters,
            "enableCyclicalToDateFilters",
            "BOOLEAN",
            FeatureFlagsValues.enableCyclicalToDateFilters,
        ),
        ...loadFeature(
            features,
            TigerFeaturesNames.EnableNewPivotTable,
            "enableNewPivotTable",
            "BOOLEAN",
            FeatureFlagsValues.enableNewPivotTable,
        ),
        ...loadFeature(
            features,
            TigerFeaturesNames.EnableNewGeoPushpin,
            "enableNewGeoPushpin",
            "BOOLEAN",
            FeatureFlagsValues.enableNewGeoPushpin,
        ),
        ...loadFeature(
            features,
            TigerFeaturesNames.EnableAutomationManagement,
            "enableAutomationManagement",
            "BOOLEAN",
            FeatureFlagsValues.enableAutomationManagement,
        ),
        ...loadFeature(
            features,
            TigerFeaturesNames.EnableNewPdfTabularExport,
            "enableNewPdfTabularExport",
            "BOOLEAN",
            FeatureFlagsValues.enableNewPdfTabularExport,
        ),
        ...loadFeature(
            features,
            TigerFeaturesNames.EnableFilterAccessibility,
            "enableFilterAccessibility",
            "BOOLEAN",
            FeatureFlagsValues.enableFilterAccessibility,
        ),
        ...loadFeature(
            features,
            TigerFeaturesNames.EnableGenAIMemory,
            "enableGenAIMemory",
            "BOOLEAN",
            FeatureFlagsValues.enableGenAIMemory,
        ),
        ...loadFeature(
            features,
            TigerFeaturesNames.AIChatSearchLimit,
            "aiChatSearchLimit",
            "NUMBER",
            FeatureFlagsValues.aiChatSearchLimit,
        ),
        ...loadFeature(
            features,
            TigerFeaturesNames.EnableDashboardTabs,
            "enableDashboardTabs",
            "BOOLEAN",
            FeatureFlagsValues.enableDashboardTabs,
        ),
        ...loadFeature(
            features,
            TigerFeaturesNames.EnablePivotTableAutoSizeReset,
            "enablePivotTableAutoSizeReset",
            "BOOLEAN",
            FeatureFlagsValues.enablePivotTableAutoSizeReset,
        ),
        ...loadFeature(
            features,
            TigerFeaturesNames.EnablePreserveFilterSelectionDuringInit,
            "enablePreserveFilterSelectionDuringInit",
            "BOOLEAN",
            FeatureFlagsValues.enablePreserveFilterSelectionDuringInit,
        ),
    };
}

function loadFeature(
    features: FeaturesMap,
    feature: TigerFeaturesNames,
    name: keyof ITigerFeatureFlags,
    outputType: "STRING" | "BOOLEAN" | "JSON" | "NUMBER",
    possibleValues: readonly any[],
) {
    const item = features[feature];

    if (!item) {
        return {};
    }

    const val = getValueByType(item.type, item.value, outputType, possibleValues);
    return val === undefined ? {} : { [name]: val };
}

function getValueByType(
    inputType: FeatureDef["type"],
    value: FeatureDef["value"],
    outputType: "STRING" | "BOOLEAN" | "JSON" | "NUMBER",
    possibleValues: readonly any[],
) {
    switch (inputType) {
        case "BOOLEAN":
            if (value !== undefined) {
                return value;
            }
            break;
        case "NUMBER":
        case "STRING": {
            const state = convertState(outputType, possibleValues, value);
            if (state !== undefined) {
                return state;
            }
            break;
        }
        case "JSON": {
            if (value !== undefined) {
                return JSON.parse(value);
            }
            break;
        }
        default:
            break;
    }
    return undefined;
}
