// (C) 2020-2026 GoodData Corporation

import { FeatureFlagsValues, type ITigerFeatureFlags, TigerFeaturesNames } from "../uiFeatures.js";

import { convertState } from "./state.js";

export type FeatureDef = {
    id: string;
    key: string;
    l: boolean;
    version: string;
    type: "BOOLEAN" | "STRING" | "NUMBER" | "JSON";
    value: any;
};

export type FeaturesMap = Record<string, FeatureDef>;

export function mapFeatures(features: FeaturesMap): Partial<ITigerFeatureFlags> {
    return {
        ...loadFeature(
            features,
            TigerFeaturesNames.EnableMetricSqlAndDataExplain,
            "enableMetricSqlAndDataExplain",
            "BOOLEAN",
            FeatureFlagsValues.enableMetricSqlAndDataExplain,
        ),
        ...loadFeature(
            features,
            TigerFeaturesNames.EnableMetricFormatOverrides,
            "enableMetricFormatOverrides",
            "BOOLEAN",
            FeatureFlagsValues.enableMetricFormatOverrides,
        ),
        ...loadFeature(
            features,
            TigerFeaturesNames.EnableColumnLevelPermissions,
            "enableColumnLevelPermissions",
            "BOOLEAN",
            FeatureFlagsValues.enableColumnLevelPermissions,
        ),
        ...loadFeature(
            features,
            TigerFeaturesNames.EnableRadarChart,
            "enableRadarChart",
            "BOOLEAN",
            FeatureFlagsValues.enableRadarChart,
        ),
        ...loadFeature(
            features,
            TigerFeaturesNames.EnableMekkoChart,
            "enableMekkoChart",
            "BOOLEAN",
            FeatureFlagsValues.enableMekkoChart,
        ),
        ...loadFeature(
            features,
            TigerFeaturesNames.EnableSqlDatasets,
            "enableSqlDatasets",
            "BOOLEAN",
            FeatureFlagsValues.enableSqlDatasets,
        ),
        ...loadFeature(
            features,
            TigerFeaturesNames.EnableChangeAnalysis,
            "enableChangeAnalysis",
            "BOOLEAN",
            FeatureFlagsValues.enableChangeAnalysis,
        ),
        ...loadFeature(
            features,
            TigerFeaturesNames.EnableRankingWithMvf,
            "enableRankingWithMvf",
            "BOOLEAN",
            FeatureFlagsValues.enableRankingWithMvf,
        ),
        ...loadFeature(
            features,
            TigerFeaturesNames.EnableRankingStrictLimit,
            "enableRankingStrictLimit",
            "BOOLEAN",
            FeatureFlagsValues.enableRankingStrictLimit,
        ),
        ...loadFeature(
            features,
            TigerFeaturesNames.EnableImprovedRankingFilter,
            "enableImprovedRankingFilter",
            "BOOLEAN",
            FeatureFlagsValues.enableImprovedRankingFilter,
        ),
        ...loadFeature(
            features,
            TigerFeaturesNames.EnableMySqlDataSource,
            "enableMySqlDataSource",
            "BOOLEAN",
            FeatureFlagsValues.enableMySqlDataSource,
        ),
        ...loadFeature(
            features,
            TigerFeaturesNames.EnableMariaDbDataSource,
            "enableMariaDbDataSource",
            "BOOLEAN",
            FeatureFlagsValues.enableMariaDbDataSource,
        ),
        ...loadFeature(
            features,
            TigerFeaturesNames.EnableOracleDataSource,
            "enableOracleDataSource",
            "BOOLEAN",
            FeatureFlagsValues.enableOracleDataSource,
        ),
        ...loadFeature(
            features,
            TigerFeaturesNames.EnableAnalyticalCatalog,
            "enableAnalyticalCatalog",
            "BOOLEAN",
            FeatureFlagsValues.enableAnalyticalCatalog,
        ),
        ...loadFeature(
            features,
            TigerFeaturesNames.EnableParameters,
            "enableParameters",
            "BOOLEAN",
            FeatureFlagsValues.enableParameters,
        ),
        ...loadFeature(
            features,
            TigerFeaturesNames.EnableAnalyticalCatalogMetricEditor,
            "enableAnalyticalCatalogMetricEditor",
            "BOOLEAN",
            FeatureFlagsValues.enableAnalyticalCatalogMetricEditor,
        ),
        ...loadFeature(
            features,
            TigerFeaturesNames.EnableStringParameters,
            "enableStringParameters",
            "BOOLEAN",
            FeatureFlagsValues.enableStringParameters,
        ),
        ...loadFeature(
            features,
            TigerFeaturesNames.EnableLabsSmartFunctions,
            "enableLabsSmartFunctions",
            "BOOLEAN",
            FeatureFlagsValues.enableLabsSmartFunctions,
        ),
        ...loadFeature(
            features,
            TigerFeaturesNames.EnableCustomTooltip,
            "enableCustomTooltip",
            "BOOLEAN",
            FeatureFlagsValues.enableCustomTooltip,
        ),
        ...loadFeature(
            features,
            TigerFeaturesNames.EnableMotherDuckDataSource,
            "enableMotherDuckDataSource",
            "BOOLEAN",
            FeatureFlagsValues.enableMotherDuckDataSource,
        ),
        ...loadFeature(
            features,
            TigerFeaturesNames.EnableMongoDbDataSource,
            "enableMongoDbDataSource",
            "BOOLEAN",
            FeatureFlagsValues.enableMongoDbDataSource,
        ),
        ...loadFeature(
            features,
            TigerFeaturesNames.EnableStarrocksDataSource,
            "enableStarrocksDataSource",
            "BOOLEAN",
            FeatureFlagsValues.enableStarrocksDataSource,
        ),
        ...loadFeature(
            features,
            TigerFeaturesNames.EnableDataProfiling,
            "enableDataProfiling",
            "BOOLEAN",
            FeatureFlagsValues.enableDataProfiling,
        ),
        ...loadFeature(
            features,
            TigerFeaturesNames.EnableExperimentalFeaturesUI,
            "enableExperimentalFeaturesUI",
            "BOOLEAN",
            FeatureFlagsValues.enableExperimentalFeaturesUI,
        ),
        ...loadFeature(
            features,
            TigerFeaturesNames.EnableSingleStoreDataSource,
            "enableSingleStoreDataSource",
            "BOOLEAN",
            FeatureFlagsValues.enableSingleStoreDataSource,
        ),
        ...loadFeature(
            features,
            TigerFeaturesNames.EnableOidcAuth,
            "enableOidcAuth",
            "BOOLEAN",
            FeatureFlagsValues.enableOidcAuth,
        ),
        ...loadFeature(
            features,
            TigerFeaturesNames.EnableSemanticSearch,
            "enableSemanticSearch",
            "BOOLEAN",
            FeatureFlagsValues.enableSemanticSearch,
        ),
        ...loadFeature(
            features,
            TigerFeaturesNames.EnableCatalogSmartSearchResults,
            "enableCatalogSmartSearchResults",
            "BOOLEAN",
            FeatureFlagsValues.enableCatalogSmartSearchResults,
        ),
        ...loadFeature(
            features,
            TigerFeaturesNames.EnableGenAIChat,
            "enableGenAIChat",
            "BOOLEAN",
            FeatureFlagsValues.enableGenAIChat,
        ),
        ...loadFeature(
            features,
            TigerFeaturesNames.EnableGenAICatalogQualityChecker,
            "enableGenAICatalogQualityChecker",
            "BOOLEAN",
            FeatureFlagsValues.enableGenAICatalogQualityChecker,
        ),
        ...loadFeature(
            features,
            TigerFeaturesNames.EnableCatalogTrendingObjects,
            "enableCatalogTrendingObjects",
            "BOOLEAN",
            FeatureFlagsValues.enableCatalogTrendingObjects,
        ),
        ...loadFeature(
            features,
            TigerFeaturesNames.EnableCatalogLineage,
            "enableCatalogLineage",
            "BOOLEAN",
            FeatureFlagsValues.enableCatalogLineage,
        ),
        ...loadFeature(
            features,
            TigerFeaturesNames.EnableCertification,
            "enableCertification",
            "BOOLEAN",
            FeatureFlagsValues.enableCertification,
        ),
        ...loadFeature(
            features,
            TigerFeaturesNames.EnableAIDataSetting,
            "enableAIDataSetting",
            "BOOLEAN",
            FeatureFlagsValues.enableAIDataSetting,
        ),
        ...loadFeature(
            features,
            TigerFeaturesNames.EnableSystemAccountFiltering,
            "enableSystemAccountFiltering",
            "BOOLEAN",
            FeatureFlagsValues.enableSystemAccountFiltering,
        ),
        ...loadFeature(
            features,
            TigerFeaturesNames.EnableNewInsightChangedPostMessageEvent,
            "enableNewInsightChangedPostMessageEvent",
            "BOOLEAN",
            FeatureFlagsValues.enableNewInsightChangedPostMessageEvent,
        ),
        ...loadFeature(
            features,
            TigerFeaturesNames.EarlyAccessFeatures,
            "earlyAccessFeatures",
            "JSON",
            FeatureFlagsValues.earlyAccessFeatures,
        ),
        ...loadFeature(
            features,
            TigerFeaturesNames.EnableDefaultSmtp,
            "enableDefaultSmtp",
            "BOOLEAN",
            FeatureFlagsValues.enableDefaultSmtp,
        ),
        ...loadFeature(
            features,
            TigerFeaturesNames.EnableVisualizationFilteringByTags,
            "enableVisualizationFilteringByTags",
            "BOOLEAN",
            FeatureFlagsValues.enableVisualizationFilteringByTags,
        ),
        ...loadFeature(
            features,
            TigerFeaturesNames.EnableVisualizationFineTuning,
            "enableVisualizationFineTuning",
            "BOOLEAN",
            FeatureFlagsValues.enableVisualizationFineTuning,
        ),
        ...loadFeature(
            features,
            TigerFeaturesNames.EnableDashboardTabularExport,
            "enableDashboardTabularExport",
            "BOOLEAN",
            FeatureFlagsValues.enableDashboardTabularExport,
        ),
        ...loadFeature(
            features,
            TigerFeaturesNames.EnableOrchestratedTabularExports,
            "enableOrchestratedTabularExports",
            "BOOLEAN",
            FeatureFlagsValues.enableOrchestratedTabularExports,
        ),
        ...loadFeature(
            features,
            TigerFeaturesNames.EnableDashboardDescriptionDynamicHeight,
            "enableDashboardDescriptionDynamicHeight",
            "BOOLEAN",
            FeatureFlagsValues.enableDashboardDescriptionDynamicHeight,
        ),
        ...loadFeature(
            features,
            TigerFeaturesNames.EnableAmplitudeTracker,
            "enableAmplitudeTracker",
            "BOOLEAN",
            FeatureFlagsValues.enableAmplitudeTracker,
        ),
        ...loadFeature(
            features,
            TigerFeaturesNames.EnableExportTemplateSelection,
            "enableExportTemplateSelection",
            "BOOLEAN",
            FeatureFlagsValues.enableExportTemplateSelection,
        ),
        ...loadFeature(
            features,
            TigerFeaturesNames.EnableRawExports,
            "enableRawExports",
            "BOOLEAN",
            FeatureFlagsValues.enableRawExports,
        ),
        ...loadFeature(
            features,
            TigerFeaturesNames.EnableExecutionCancelling,
            "enableExecutionCancelling",
            "BOOLEAN",
            FeatureFlagsValues.enableExecutionCancelling,
        ),
        ...loadFeature(
            features,
            TigerFeaturesNames.EnableImmediateAttributeFilterDisplayAsLabelMigration,
            "enableImmediateAttributeFilterDisplayAsLabelMigration",
            "BOOLEAN",
            FeatureFlagsValues.enableImmediateAttributeFilterDisplayAsLabelMigration,
        ),
        ...loadFeature(
            features,
            TigerFeaturesNames.EnableAnalyticalDesignerCatalogSideload,
            "enableAnalyticalDesignerCatalogSideload",
            "BOOLEAN",
            FeatureFlagsValues.enableAnalyticalDesignerCatalogSideload,
        ),
        ...loadFeature(
            features,
            TigerFeaturesNames.EnableHighchartsAccessibility,
            "enableHighchartsAccessibility",
            "BOOLEAN",
            FeatureFlagsValues.enableHighchartsAccessibility,
        ),
        ...loadFeature(
            features,
            TigerFeaturesNames.EnableAccessibleChartTooltip,
            "enableAccessibleChartTooltip",
            "BOOLEAN",
            FeatureFlagsValues.enableAccessibleChartTooltip,
        ),
        ...loadFeature(
            features,
            TigerFeaturesNames.EnableWorkspaceSettingsAppHeaderMenuItem,
            "enableWorkspaceSettingsAppHeaderMenuItem",
            "BOOLEAN",
            FeatureFlagsValues.enableWorkspaceSettingsAppHeaderMenuItem,
        ),
        ...loadFeature(
            features,
            TigerFeaturesNames.EnableSnapshotExportAccessibility,
            "enableSnapshotExportAccessibility",
            "BOOLEAN",
            FeatureFlagsValues.enableSnapshotExportAccessibility,
        ),
        ...loadFeature(
            features,
            TigerFeaturesNames.EnableExportToDocumentStorage,
            "enableExportToDocumentStorage",
            "BOOLEAN",
            FeatureFlagsValues.enableExportToDocumentStorage,
        ),
        ...loadFeature(
            features,
            TigerFeaturesNames.EnableNotificationChannelIdentifiers,
            "enableNotificationChannelIdentifiers",
            "BOOLEAN",
            FeatureFlagsValues.enableNotificationChannelIdentifiers,
        ),
        ...loadFeature(
            features,
            TigerFeaturesNames.EnableDashboardShareDialogLink,
            "enableDashboardShareDialogLink",
            "BOOLEAN",
            FeatureFlagsValues.enableDashboardShareDialogLink,
        ),
        ...loadFeature(
            features,
            TigerFeaturesNames.ProductionFeatures,
            "productionFeatures",
            "JSON",
            FeatureFlagsValues.productionFeatures,
        ),
        ...loadFeature(
            features,
            TigerFeaturesNames.EnableSeamlessIdpSwitch,
            "enableSeamlessIdpSwitch",
            "BOOLEAN",
            FeatureFlagsValues.enableSeamlessIdpSwitch,
        ),
        ...loadFeature(
            features,
            TigerFeaturesNames.EnablePreAggregationDatasets,
            "enablePreAggregationDatasets",
            "BOOLEAN",
            FeatureFlagsValues.enablePreAggregationDatasets,
        ),
        ...loadFeature(
            features,
            TigerFeaturesNames.EnableNewPivotTable,
            "enableNewPivotTable",
            "BOOLEAN",
            FeatureFlagsValues.enableNewPivotTable,
        ),
        ...loadFeature(
            features,
            TigerFeaturesNames.EnableConditionalFormatting,
            "enableConditionalFormatting",
            "BOOLEAN",
            FeatureFlagsValues.enableConditionalFormatting,
        ),
        ...loadFeature(
            features,
            TigerFeaturesNames.EnableNewGeoPushpin,
            "enableNewGeoPushpin",
            "BOOLEAN",
            FeatureFlagsValues.enableNewGeoPushpin,
        ),
        ...loadFeature(
            features,
            TigerFeaturesNames.EnableGeoArea,
            "enableGeoArea",
            "BOOLEAN",
            FeatureFlagsValues.enableGeoArea,
        ),
        ...loadFeature(
            features,
            TigerFeaturesNames.EnableHLL,
            "enableHLL",
            "BOOLEAN",
            FeatureFlagsValues.enableHLL,
        ),
        ...loadFeature(
            features,
            TigerFeaturesNames.EnableGeoPushpinIcon,
            "enableGeoPushpinIcon",
            "BOOLEAN",
            FeatureFlagsValues.enableGeoPushpinIcon,
        ),
        ...loadFeature(
            features,
            TigerFeaturesNames.EnableGeoChartA11yImprovements,
            "enableGeoChartA11yImprovements",
            "BOOLEAN",
            FeatureFlagsValues.enableGeoChartA11yImprovements,
        ),
        ...loadFeature(
            features,
            TigerFeaturesNames.EnableGeoLayersExport,
            "enableGeoLayersExport",
            "BOOLEAN",
            FeatureFlagsValues.enableGeoLayersExport,
        ),
        ...loadFeature(
            features,
            TigerFeaturesNames.EnableGeoChartsViewportConfig,
            "enableGeoChartsViewportConfig",
            "BOOLEAN",
            FeatureFlagsValues.enableGeoChartsViewportConfig,
        ),
        ...loadFeature(
            features,
            TigerFeaturesNames.EnableGeoSegmentConflictRecommendation,
            "enableGeoSegmentConflictRecommendation",
            "BOOLEAN",
            FeatureFlagsValues.enableGeoSegmentConflictRecommendation,
        ),
        ...loadFeature(
            features,
            TigerFeaturesNames.EnableGeoBasemapConfig,
            "enableGeoBasemapConfig",
            "BOOLEAN",
            FeatureFlagsValues.enableGeoBasemapConfig,
        ),
        ...loadFeature(
            features,
            TigerFeaturesNames.EnableCustomGeoCollection,
            "enableCustomGeoCollection",
            "BOOLEAN",
            FeatureFlagsValues.enableCustomGeoCollection,
        ),
        ...loadFeature(
            features,
            TigerFeaturesNames.EnableGeoSatelliteBasemapOption,
            "enableGeoSatelliteBasemapOption",
            "BOOLEAN",
            FeatureFlagsValues.enableGeoSatelliteBasemapOption,
        ),
        ...loadFeature(
            features,
            TigerFeaturesNames.EnableGenAIMemory,
            "enableGenAIMemory",
            "BOOLEAN",
            FeatureFlagsValues.enableGenAIMemory,
        ),
        ...loadFeature(
            features,
            TigerFeaturesNames.EnableOrgLevelAIMemory,
            "enableOrgLevelAIMemory",
            "BOOLEAN",
            FeatureFlagsValues.enableOrgLevelAIMemory,
        ),
        ...loadFeature(
            features,
            TigerFeaturesNames.EnableAIKnowledge,
            "enableAIKnowledge",
            "BOOLEAN",
            FeatureFlagsValues.enableAIKnowledge,
        ),
        ...loadFeature(
            features,
            TigerFeaturesNames.EnableAiAgenticSuggestions,
            "enableAiAgenticSuggestions",
            "BOOLEAN",
            FeatureFlagsValues.enableAiAgenticSuggestions,
        ),
        ...loadFeature(
            features,
            TigerFeaturesNames.EnableAiAssistantEmbedding,
            "enableAiAssistantEmbedding",
            "BOOLEAN",
            FeatureFlagsValues.enableAiAssistantEmbedding,
        ),
        ...loadFeature(
            features,
            TigerFeaturesNames.EnableGenAIReasoningVisibility,
            "enableGenAIReasoningVisibility",
            "BOOLEAN",
            FeatureFlagsValues.enableGenAIReasoningVisibility,
        ),
        ...loadFeature(
            features,
            TigerFeaturesNames.EnableAiAgenticConversations,
            "enableAiAgenticConversations",
            "BOOLEAN",
            FeatureFlagsValues.enableAiAgenticConversations,
        ),
        ...loadFeature(
            features,
            TigerFeaturesNames.EnableAiContextSetup,
            "enableAiContextSetup",
            "BOOLEAN",
            FeatureFlagsValues.enableAiContextSetup,
        ),
        ...loadFeature(
            features,
            TigerFeaturesNames.EnableAiAgenticMultiConversations,
            "enableAiAgenticMultiConversations",
            "BOOLEAN",
            FeatureFlagsValues.enableAiAgenticMultiConversations,
        ),
        ...loadFeature(
            features,
            TigerFeaturesNames.EnableGenAiAgentSwitching,
            "enableGenAiAgentSwitching",
            "BOOLEAN",
            FeatureFlagsValues.enableGenAiAgentSwitching,
        ),
        ...loadFeature(
            features,
            TigerFeaturesNames.EnableGenAiObservability,
            "enableGenAiObservability",
            "BOOLEAN",
            FeatureFlagsValues.enableGenAiObservability,
        ),
        ...loadFeature(
            features,
            TigerFeaturesNames.EnableAiLlmAnthropicProvider,
            "enableAiLlmAnthropicProvider",
            "BOOLEAN",
            FeatureFlagsValues.enableAiLlmAnthropicProvider,
        ),
        ...loadFeature(
            features,
            TigerFeaturesNames.EnableGenAiVisualizationSummarySkill,
            "enableGenAiVisualizationSummarySkill",
            "BOOLEAN",
            FeatureFlagsValues.enableGenAiVisualizationSummarySkill,
        ),
        ...loadFeature(
            features,
            TigerFeaturesNames.EnableGenAiDashboardSummarySkill,
            "enableGenAiDashboardSummarySkill",
            "BOOLEAN",
            FeatureFlagsValues.enableGenAiDashboardSummarySkill,
        ),
        ...loadFeature(
            features,
            TigerFeaturesNames.EnableGenAiAgenticDataShareOptOut,
            "enableGenAiAgenticDataShareOptOut",
            "BOOLEAN",
            FeatureFlagsValues.enableGenAiAgenticDataShareOptOut,
        ),
        ...loadFeature(
            features,
            TigerFeaturesNames.AIChatSearchLimit,
            "aiChatSearchLimit",
            "NUMBER",
            FeatureFlagsValues.aiChatSearchLimit,
        ),
        ...loadFeature(
            features,
            TigerFeaturesNames.EnableRichTextWidgetFilterConfiguration,
            "enableRichTextWidgetFilterConfiguration",
            "BOOLEAN",
            FeatureFlagsValues.enableRichTextWidgetFilterConfiguration,
        ),
        ...loadFeature(
            features,
            TigerFeaturesNames.EnableDashboardSectionHeadersDateDataSet,
            "enableDashboardSectionHeadersDateDataSet",
            "BOOLEAN",
            FeatureFlagsValues.enableDashboardSectionHeadersDateDataSet,
        ),
        ...loadFeature(
            features,
            TigerFeaturesNames.EnableAnalyticalDashboardVersion3,
            "enableAnalyticalDashboardVersion3",
            "BOOLEAN",
            FeatureFlagsValues.enableAnalyticalDashboardVersion3,
        ),
        ...loadFeature(
            features,
            TigerFeaturesNames.EnableAnomalyDetectionAlert,
            "enableAnomalyDetectionAlert",
            "BOOLEAN",
            FeatureFlagsValues.enableAnomalyDetectionAlert,
        ),
        ...loadFeature(
            features,
            TigerFeaturesNames.EnableAnomalyDetectionVisualization,
            "enableAnomalyDetectionVisualization",
            "BOOLEAN",
            FeatureFlagsValues.enableAnomalyDetectionVisualization,
        ),
        ...loadFeature(
            features,
            TigerFeaturesNames.EnableAlertOncePerInterval,
            "enableAlertOncePerInterval",
            "BOOLEAN",
            FeatureFlagsValues.enableAlertOncePerInterval,
        ),
        ...loadFeature(
            features,
            TigerFeaturesNames.EnableFiscalCalendars,
            "enableFiscalCalendars",
            "BOOLEAN",
            FeatureFlagsValues.enableFiscalCalendars,
        ),
        ...loadFeature(
            features,
            TigerFeaturesNames.EnableDashboardFilterGroups,
            "enableDashboardFilterGroups",
            "BOOLEAN",
            FeatureFlagsValues.enableDashboardFilterGroups,
        ),
        ...loadFeature(
            features,
            TigerFeaturesNames.EnableMatchFilterAD,
            "enableMatchFilterAD",
            "BOOLEAN",
            FeatureFlagsValues.enableMatchFilterAD,
        ),
        ...loadFeature(
            features,
            TigerFeaturesNames.EnableArbitraryFilterAD,
            "enableArbitraryFilterAD",
            "BOOLEAN",
            FeatureFlagsValues.enableArbitraryFilterAD,
        ),
        ...loadFeature(
            features,
            TigerFeaturesNames.EnableMatchFilterKD,
            "enableMatchFilterKD",
            "BOOLEAN",
            FeatureFlagsValues.enableMatchFilterKD,
        ),
        ...loadFeature(
            features,
            TigerFeaturesNames.EnableArbitraryFilterKD,
            "enableArbitraryFilterKD",
            "BOOLEAN",
            FeatureFlagsValues.enableArbitraryFilterKD,
        ),
        ...loadFeature(
            features,
            TigerFeaturesNames.EnableMeasureValueFilterKD,
            "enableMeasureValueFilterKD",
            "BOOLEAN",
            FeatureFlagsValues.enableMeasureValueFilterKD,
        ),
        ...loadFeature(
            features,
            TigerFeaturesNames.EnableShellApplication,
            "enableShellApplication",
            "BOOLEAN",
            FeatureFlagsValues.enableShellApplication,
        ),
        ...loadFeature(
            features,
            TigerFeaturesNames.EnableShellApplicationCatalog,
            "enableShellApplication_catalog",
            "BOOLEAN",
            FeatureFlagsValues.enableShellApplication_catalog,
        ),
        ...loadFeature(
            features,
            TigerFeaturesNames.EnableShellApplicationDashboards,
            "enableShellApplication_dashboards",
            "BOOLEAN",
            FeatureFlagsValues.enableShellApplication_dashboards,
        ),
        ...loadFeature(
            features,
            TigerFeaturesNames.EnableNullableJoins,
            "enableNullableJoins",
            "BOOLEAN",
            FeatureFlagsValues.enableNullableJoins,
        ),
        ...loadFeature(
            features,
            TigerFeaturesNames.EnableDashboardDensitySetting,
            "enableDashboardDensitySetting",
            "BOOLEAN",
            FeatureFlagsValues.enableDashboardDensitySetting,
        ),
        ...loadFeature(
            features,
            TigerFeaturesNames.EnableDashboardsSearch,
            "enableDashboardsSearch",
            "BOOLEAN",
            FeatureFlagsValues.enableDashboardsSearch,
        ),
        ...loadFeature(
            features,
            TigerFeaturesNames.EnableAiHub,
            "enableAiHub",
            "BOOLEAN",
            FeatureFlagsValues.enableAiHub,
        ),
        ...loadFeature(
            features,
            TigerFeaturesNames.EnableAutomationTrigger,
            "enableAutomationTrigger",
            "BOOLEAN",
            FeatureFlagsValues.enableAutomationTrigger,
        ),
        ...loadFeature(
            features,
            TigerFeaturesNames.EnableUserDataFiltersUi,
            "enableUserDataFiltersUi",
            "BOOLEAN",
            FeatureFlagsValues.enableUserDataFiltersUi,
        ),
        ...loadFeature(
            features,
            TigerFeaturesNames.EnableEnhancedInsightPicker,
            "enableEnhancedInsightPicker",
            "BOOLEAN",
            FeatureFlagsValues.enableEnhancedInsightPicker,
        ),
        ...loadFeature(
            features,
            TigerFeaturesNames.EnableMetricEditorRemoteModule,
            "enableShellApplication_metricEditor",
            "BOOLEAN",
            FeatureFlagsValues.enableShellApplication_metricEditor,
        ),
        ...loadFeature(
            features,
            TigerFeaturesNames.EnableAnalyticalDesignerRemoteModule,
            "enableShellApplication_analyticalDesigner",
            "BOOLEAN",
            FeatureFlagsValues.enableShellApplication_analyticalDesigner,
        ),
        ...loadFeature(
            features,
            TigerFeaturesNames.EnableDashboardSidebarResize,
            "enableDashboardSidebarResize",
            "BOOLEAN",
            FeatureFlagsValues.enableDashboardSidebarResize,
        ),
        ...loadFeature(
            features,
            TigerFeaturesNames.EnableLdmModelerRemoteModule,
            "enableShellApplication_ldmModeler",
            "BOOLEAN",
            FeatureFlagsValues.enableShellApplication_ldmModeler,
        ),
        ...loadFeature(
            features,
            TigerFeaturesNames.EnableExportTimeoutFix,
            "enableExportTimeoutFix",
            "BOOLEAN",
            FeatureFlagsValues.enableExportTimeoutFix,
        ),
    };
}

function loadFeature(
    features: FeaturesMap,
    feature: TigerFeaturesNames,
    name: keyof ITigerFeatureFlags,
    outputType: "STRING" | "BOOLEAN" | "JSON" | "NUMBER",
    possibleValues: readonly any[],
) {
    const item = features[feature];

    if (!item) {
        return {};
    }

    const val = getValueByType(item.type, item.value, outputType, possibleValues);
    return val === undefined ? {} : { [name]: val };
}

function getValueByType(
    inputType: FeatureDef["type"],
    value: FeatureDef["value"],
    outputType: "STRING" | "BOOLEAN" | "JSON" | "NUMBER",
    possibleValues: readonly any[],
) {
    switch (inputType) {
        case "BOOLEAN":
            if (value !== undefined) {
                return value;
            }
            break;
        case "NUMBER":
        case "STRING": {
            const state = convertState(outputType, possibleValues, value);
            if (state !== undefined) {
                return state;
            }
            break;
        }
        case "JSON": {
            if (value !== undefined) {
                return JSON.parse(value);
            }
            break;
        }
        default:
            break;
    }
    return undefined;
}
