#!/bin/sh
# (C) 2026 GoodData Corporation
#
# Docker entrypoint wrapper that generates config.js with runtime configuration
# from environment variables, then hands off to the original nginx entrypoint.

set -e

cat > /usr/share/nginx/html/config.js <<EOF
// Runtime configuration generated by docker-entrypoint.sh
window.WORKSPACE_ID = "${WORKSPACE_ID:-}";
EOF

exec /docker-entrypoint.sh "$@"
