// (C) 2007-2026 GoodData Corporation

/**
 * This package provides the PivotTable component that you can use to visualize your data in a table-based manner.
 *
 * @remarks
 * The PivotTable component provides additional capabilities such as totals, automatic column resizing, and more.
 *
 * @packageDocumentation
 */
export { PivotTable, pivotTableMenuForCapabilities, getPivotTableDimensions } from "./PivotTable.js";
export { CorePivotTable } from "./CorePivotTable.js";

export { PivotTableNext } from "./next/index.js";
export type {
    IPivotTableNextProps,
    PivotTableNextConfig,
    PivotTableNextAccessibilityConfig,
    PivotTableNextTranspositionConfig,
    PivotTableNextTextWrappingConfig,
    PivotTableNextColumnsSizingConfig,
    PivotTableNextMenuConfig,
    PivotTableNextFormattingConfig,
    PivotTableNextExecutionCancellingConfig,
    PivotTableNextDrillMenuPositioningConfig,
    PivotTableNextLayoutConfig,
    PivotTableNextGrandTotalsPositionConfig,
    PivotTableNextCellSelectionConfig,
    PivotTableNextAgGridLicenseConfig,
    PivotTableNextPaginationConfig,
    PivotTableNextExperimentalConfig,
    ColumnResizedCallback as ColumnResizedCallbackNext,
    IColumnSizing as IColumnSizingNext,
    IMenu as IMenuNext,
    IPagination,
    ITextWrapping,
    IColumnTextWrappingItem,
    MeasureGroupDimension as MeasureGroupDimensionNext,
    ColumnHeadersPosition as ColumnHeadersPositionNext,
    GrandTotalsPosition as GrandTotalsPositionNext,
    ColumnWidthItem as ColumnWidthItemNext,
    DefaultColumnWidth as DefaultColumnWidthNext,
    IAttributeColumnWidthItem as IAttributeColumnWidthItemNext,
    IMeasureColumnWidthItem as IMeasureColumnWidthItemNext,
    ISliceMeasureColumnWidthItem as ISliceMeasureColumnWidthItemNext,
    IMixedValuesColumnWidthItem as IMixedValuesColumnWidthItemNext,
    IAllMeasureColumnWidthItem as IAllMeasureColumnWidthItemNext,
    IWeakMeasureColumnWidthItem as IWeakMeasureColumnWidthItemNext,
    ColumnLocator as ColumnLocatorNext,
    IAttributeColumnLocator as IAttributeColumnLocatorNext,
    IMeasureColumnLocator as IMeasureColumnLocatorNext,
    ITotalColumnLocator as ITotalColumnLocatorNext,
    IAttributeColumnLocatorBody as IAttributeColumnLocatorBodyNext,
    IMeasureColumnLocatorBody as IMeasureColumnLocatorBodyNext,
    ITotalColumnLocatorBody as ITotalColumnLocatorBodyNext,
    IAttributeColumnWidthItemBody as IAttributeColumnWidthItemBodyNext,
    IMeasureColumnWidthItemBody as IMeasureColumnWidthItemBodyNext,
    ISliceMeasureColumnWidthItemBody as ISliceMeasureColumnWidthItemBodyNext,
    IMixedValuesColumnWidthItemBody as IMixedValuesColumnWidthItemBodyNext,
    IAllMeasureColumnWidthItemBody as IAllMeasureColumnWidthItemBodyNext,
    IWeakMeasureColumnWidthItemBody as IWeakMeasureColumnWidthItemBodyNext,
    ColumnWidth as ColumnWidthNext,
    IAbsoluteColumnWidth as IAbsoluteColumnWidthNext,
    IAutoColumnWidth as IAutoColumnWidthNext,
} from "./next/index.js";

export type {
    IPivotTableBucketProps,
    IPivotTableBaseProps,
    IPivotTableProps,
    IPivotTableConfig,
    IColumnSizing,
    DefaultColumnWidth,
    ICorePivotTableProps,
    ColumnResizedCallback,
    IMenu,
    MeasureGroupDimension,
    ColumnHeadersPosition,
    GrandTotalsPosition,
} from "./publicTypes.js";

export type {
    IWeakMeasureColumnWidthItem,
    IWeakMeasureColumnWidthItemBody,
    ColumnWidthItem,
    ColumnWidth,
    IAttributeColumnWidthItem,
    IAttributeColumnWidthItemBody,
    IMeasureColumnWidthItem,
    IMeasureColumnWidthItemBody,
    ISliceMeasureColumnWidthItem,
    ISliceMeasureColumnWidthItemBody,
    IMixedValuesColumnWidthItem,
    IMixedValuesColumnWidthItemBody,
    IAbsoluteColumnWidth,
    IAllMeasureColumnWidthItem,
    IAllMeasureColumnWidthItemBody,
    IAutoColumnWidth,
    ColumnLocator,
    IAttributeColumnLocator,
    IAttributeColumnLocatorBody,
    ITotalColumnLocator,
    ITotalColumnLocatorBody,
    IMeasureColumnLocator,
    IMeasureColumnLocatorBody,
} from "./columnWidths.js";
export {
    isWeakMeasureColumnWidthItem,
    isAttributeColumnWidthItem,
    isMeasureColumnWidthItem,
    isSliceMeasureColumnWidthItem,
    isMixedValuesColumnWidthItem,
    isAbsoluteColumnWidth,
    isAllMeasureColumnWidthItem,
    isMeasureColumnLocator,
    isAttributeColumnLocator,
    isTotalColumnLocator,
    newAttributeColumnLocator,
    newWidthForAllColumnsForMeasure,
    newWidthForAllMeasureColumns,
    newWidthForAttributeColumn,
    newWidthForSelectedColumns,
    setNewWidthForSelectedColumns,
    newTotalColumnLocator,
} from "./columnWidths.js";
