// (C) 2007-2026 GoodData Corporation

/* oxlint-disable no-barrel-files/no-barrel-files */

/**
 * This package provides the PivotTable component that you can use to visualize your data in a table-based manner.
 *
 * @remarks
 * The PivotTable component provides additional capabilities such as totals, automatic column resizing, and more.
 *
 * @packageDocumentation
 */
export { PivotTable, pivotTableMenuForCapabilities, getPivotTableDimensions } from "./PivotTable.js";
export { CorePivotTable } from "./CorePivotTable.js";

export {
    PivotTableNext,
    type IPivotTableNextProps,
    type PivotTableNextConfig,
    type PivotTableNextAccessibilityConfig,
    type PivotTableNextTranspositionConfig,
    type PivotTableNextTextWrappingConfig,
    type PivotTableNextColumnsSizingConfig,
    type PivotTableNextMenuConfig,
    type PivotTableNextFormattingConfig,
    type PivotTableNextExecutionCancellingConfig,
    type PivotTableNextLayoutConfig,
    type PivotTableNextGrandTotalsPositionConfig,
    type PivotTableNextCellSelectionConfig,
    type PivotTableNextAgGridLicenseConfig,
    type PivotTableNextPaginationConfig,
    type PivotTableNextExperimentalConfig,
    type ColumnResizedCallback as ColumnResizedCallbackNext,
    type IColumnSizing as IColumnSizingNext,
    type IMenu as IMenuNext,
    type IPagination,
    type ITextWrapping,
    type IColumnTextWrappingItem,
    type MeasureGroupDimension as MeasureGroupDimensionNext,
    type ColumnHeadersPosition as ColumnHeadersPositionNext,
    type GrandTotalsPosition as GrandTotalsPositionNext,
    type ColumnWidthItem as ColumnWidthItemNext,
    type DefaultColumnWidth as DefaultColumnWidthNext,
    type IAttributeColumnWidthItem as IAttributeColumnWidthItemNext,
    type IMeasureColumnWidthItem as IMeasureColumnWidthItemNext,
    type ISliceMeasureColumnWidthItem as ISliceMeasureColumnWidthItemNext,
    type IMixedValuesColumnWidthItem as IMixedValuesColumnWidthItemNext,
    type IAllMeasureColumnWidthItem as IAllMeasureColumnWidthItemNext,
    type IWeakMeasureColumnWidthItem as IWeakMeasureColumnWidthItemNext,
    type ColumnLocator as ColumnLocatorNext,
    type IAttributeColumnLocator as IAttributeColumnLocatorNext,
    type IMeasureColumnLocator as IMeasureColumnLocatorNext,
    type ITotalColumnLocator as ITotalColumnLocatorNext,
    type IAttributeColumnLocatorBody as IAttributeColumnLocatorBodyNext,
    type IMeasureColumnLocatorBody as IMeasureColumnLocatorBodyNext,
    type ITotalColumnLocatorBody as ITotalColumnLocatorBodyNext,
    type IAttributeColumnWidthItemBody as IAttributeColumnWidthItemBodyNext,
    type IMeasureColumnWidthItemBody as IMeasureColumnWidthItemBodyNext,
    type ISliceMeasureColumnWidthItemBody as ISliceMeasureColumnWidthItemBodyNext,
    type IMixedValuesColumnWidthItemBody as IMixedValuesColumnWidthItemBodyNext,
    type IAllMeasureColumnWidthItemBody as IAllMeasureColumnWidthItemBodyNext,
    type IWeakMeasureColumnWidthItemBody as IWeakMeasureColumnWidthItemBodyNext,
    type ColumnWidth as ColumnWidthNext,
    type IAbsoluteColumnWidth as IAbsoluteColumnWidthNext,
    type IAutoColumnWidth as IAutoColumnWidthNext,
} from "./next/index.js";

export type {
    IPivotTableBucketProps,
    IPivotTableBaseProps,
    IPivotTableProps,
    IPivotTableConfig,
    IColumnSizing,
    DefaultColumnWidth,
    ICorePivotTableProps,
    ColumnResizedCallback,
    IMenu,
    MeasureGroupDimension,
    ColumnHeadersPosition,
    GrandTotalsPosition,
} from "./publicTypes.js";

export {
    type IWeakMeasureColumnWidthItem,
    type IWeakMeasureColumnWidthItemBody,
    type ColumnWidthItem,
    type ColumnWidth,
    type IAttributeColumnWidthItem,
    type IAttributeColumnWidthItemBody,
    type IMeasureColumnWidthItem,
    type IMeasureColumnWidthItemBody,
    type ISliceMeasureColumnWidthItem,
    type ISliceMeasureColumnWidthItemBody,
    type IMixedValuesColumnWidthItem,
    type IMixedValuesColumnWidthItemBody,
    type IAbsoluteColumnWidth,
    type IAllMeasureColumnWidthItem,
    type IAllMeasureColumnWidthItemBody,
    type IAutoColumnWidth,
    type ColumnLocator,
    type IAttributeColumnLocator,
    type IAttributeColumnLocatorBody,
    type ITotalColumnLocator,
    type ITotalColumnLocatorBody,
    type IMeasureColumnLocator,
    type IMeasureColumnLocatorBody,
    isWeakMeasureColumnWidthItem,
    isAttributeColumnWidthItem,
    isMeasureColumnWidthItem,
    isSliceMeasureColumnWidthItem,
    isMixedValuesColumnWidthItem,
    isAbsoluteColumnWidth,
    isAllMeasureColumnWidthItem,
    isMeasureColumnLocator,
    isAttributeColumnLocator,
    isTotalColumnLocator,
    newAttributeColumnLocator,
    newWidthForAllColumnsForMeasure,
    newWidthForAllMeasureColumns,
    newWidthForAttributeColumn,
    newWidthForSelectedColumns,
    setNewWidthForSelectedColumns,
    newTotalColumnLocator,
} from "./columnWidths.js";
