name: Set up node
description: This action restore node installation from cache and install it. Node version is hardcoded to version 22.13.0

runs:
  using: 'composite'
  steps:
    - name: Check if Node.js is installed
      id: check-node
      uses: ./.github/actions/node/check-node-version
      with:
        node-version: 22.13.0

    # restore s3 cache for node installation
    - name: Restore Node.js from cache
      if: ${{ steps.check-node.outputs.node-installed == 'false' }}
      uses: runs-on/cache/restore@v4
      id: node-cache
      env:
        RUNS_ON_S3_BUCKET_CACHE: gdc-github-cache
      with:
          path: /home/runner/_work/_tool/node/22.13.0/
          key: node-22.13.0-cache

    # Prepare node
    - name: Install Node.js
      if: ${{ steps.check-node.outputs.node-installed == 'false' }}
      uses: actions/setup-node@v4
      with:
        node-version: 22.13.0

    # Print node location and version
    - name: print node location
      run: |
        node -v
        which node
      shell: bash
