// (C) 2021-2025 GoodData Corporation

/**
 * All available command types.
 *
 * @remarks
 * Note: while this type is marked as public most of the command types are currently an alpha-level API that
 * we reserve to change in the following releases.
 *
 * At this moment, we only consider the GDC.DASH/CMD.SAVEAS as stable
 *
 * @public
 */
export type DashboardCommandType =
    | "GDC.DASH/CMD.INITIALIZE"
    | "GDC.DASH/CMD.SAVE"
    | "GDC.DASH/CMD.SAVEAS"
    | "GDC.DASH/CMD.RESET"
    | "GDC.DASH/CMD.RENAME"
    | "GDC.DASH/CMD.DELETE"
    | "GDC.DASH/CMD.CHANGE_RENDER_MODE"
    | "GDC.DASH/CMD.SHARING.CHANGE"
    | "GDC.DASH/CMD.EXPORT.PDF"
    | "GDC.DASH/CMD.EXPORT.EXCEL"
    | "GDC.DASH/CMD.EXPORT.PDF_PRESENTATION"
    | "GDC.DASH/CMD.EXPORT.PPT_PRESENTATION"
    | "GDC.DASH/CMD.EVENT.TRIGGER"
    | "GDC.DASH/CMD.EXECUTION_RESULT.UPSERT"
    | "GDC.DASH/CMD.FILTER_CONTEXT.CHANGE_SELECTION"
    | "GDC.DASH/CMD.FILTER_CONTEXT.DATE_FILTER.CHANGE_SELECTION"
    | "GDC.DASH/CMD.FILTER_CONTEXT.ATTRIBUTE_FILTER.ADD"
    | "GDC.DASH/CMD.FILTER_CONTEXT.ATTRIBUTE_FILTER.REMOVE"
    | "GDC.DASH/CMD.FILTER_CONTEXT.ATTRIBUTE_FILTER.MOVE"
    | "GDC.DASH/CMD.FILTER_CONTEXT.ATTRIBUTE_FILTER.CHANGE_SELECTION"
    | "GDC.DASH/CMD.FILTER_CONTEXT.ATTRIBUTE_FILTER.SET_PARENTS"
    | "GDC.DASH/CMD.FILTER_CONTEXT.ATTRIBUTE_FILTER.SET_DISPLAY_FORM"
    | "GDC.DASH/CMD.FILTER_CONTEXT.ATTRIBUTE_FILTER.SET_TITLE"
    | "GDC.DASH/CMD.FILTER_CONTEXT.ATTRIBUTE_FILTER.SET_SELECTION_MODE"
    | "GDC.DASH/CMD.FILTER_CONTEXT.ATTRIBUTE_FILTER.SET_DEPENDENT_DATE_FILTERS"
    | "GDC.DASH/CMD.FILTER_CONTEXT.DATE_FILTER.ADD"
    | "GDC.DASH/CMD.FILTER_CONTEXT.DATE_FILTER.REMOVE"
    | "GDC.DASH/CMD.FILTER_CONTEXT.DATE_FILTER.MOVE"
    | "GDC.DASH/CMD.ATTRIBUTE_FILTER_CONFIG.SET_MODE"
    | "GDC.DASH/CMD.ATTRIBUTE_FILTER_CONFIG.SET_LIMITING_ITEMS"
    | "GDC.DASH/CMD.ATTRIBUTE_FILTER_CONFIG.SET_DISPLAY_AS_LABEL"
    | "GDC.DASH/CMD.DATE_FILTER_CONFIG.SET_MODE"
    | "GDC.DASH/CMD.DATE_FILTER_WITH_DIMENSION_CONFIG.SET_MODE"
    | "GDC.DASH/CMD.DATE_FILTER_CONFIG.SET_TITLE"
    | "GDC.DASH/CMD.FLUID_LAYOUT.ADD_SECTION"
    | "GDC.DASH/CMD.FLUID_LAYOUT.MOVE_SECTION"
    | "GDC.DASH/CMD.FLUID_LAYOUT.MOVE_ITEM_TO_NEW_SECTION"
    | "GDC.DASH/CMD.FLUID_LAYOUT.REMOVE_SECTION"
    | "GDC.DASH/CMD.FLUID_LAYOUT.CHANGE_SECTION_HEADER"
    | "GDC.DASH/CMD.FLUID_LAYOUT.ADD_ITEMS"
    | "GDC.DASH/CMD.FLUID_LAYOUT.REPLACE_ITEM"
    | "GDC.DASH/CMD.FLUID_LAYOUT.MOVE_ITEM"
    | "GDC.DASH/CMD.FLUID_LAYOUT.REMOVE_ITEM"
    | "GDC.DASH/CMD.FLUID_LAYOUT.REMOVE_ITEM_BY_WIDGET_REF"
    | "GDC.DASH/CMD.FLUID_LAYOUT.UNDO"
    | "GDC.DASH/CMD.FLUID_LAYOUT.RESIZE_HEIGHT"
    | "GDC.DASH/CMD.FLUID_LAYOUT.RESIZE_WIDTH"
    | "GDC.DASH/CMD.FLUID_LAYOUT.SET_SCREEN_SIZE"
    | "GDC.DASH/CMD.FLEXIBLE_LAYOUT.TOGGLE_LAYOUT_SECTION_HEADERS"
    | "GDC.DASH/CMD.FLEXIBLE_LAYOUT.TOGGLE_LAYOUT_DIRECTION"
    | "GDC.DASH/CMD.KPI_WIDGET.CHANGE_HEADER"
    | "GDC.DASH/CMD.KPI_WIDGET.CHANGE_MEASURE"
    | "GDC.DASH/CMD.KPI_WIDGET.CHANGE_FILTER_SETTINGS"
    | "GDC.DASH/CMD.KPI_WIDGET.CHANGE_COMPARISON"
    | "GDC.DASH/CMD.KPI_WIDGET.REFRESH"
    | "GDC.DASH/CMD.KPI_WIDGET.SET_DRILL"
    | "GDC.DASH/CMD.KPI_WIDGET.REMOVE_DRILL"
    | "GDC.DASH/CMD.KPI_WIDGET.CHANGE_DESCRIPTION"
    | "GDC.DASH/CMD.KPI_WIDGET.CHANGE_CONFIGURATION"
    | "GDC.DASH/CMD.INSIGHT_WIDGET.CHANGE_HEADER"
    | "GDC.DASH/CMD.INSIGHT_WIDGET.CHANGE_DESCRIPTION"
    | "GDC.DASH/CMD.INSIGHT_WIDGET.CHANGE_FILTER_SETTINGS"
    | "GDC.DASH/CMD.INSIGHT_WIDGET.CHANGE_PROPERTIES"
    | "GDC.DASH/CMD.INSIGHT_WIDGET.CHANGE_CONFIGURATION"
    | "GDC.DASH/CMD.INSIGHT_WIDGET.CHANGE_INSIGHT"
    | "GDC.DASH/CMD.INSIGHT_WIDGET.CHANGE_IGNORE_CROSS_FILTERING"
    | "GDC.DASH/CMD.INSIGHT_WIDGET.EXPORT"
    | "GDC.DASH/CMD.INSIGHT_WIDGET.MODIFY_DRILLS"
    | "GDC.DASH/CMD.INSIGHT_WIDGET.REMOVE_DRILLS"
    | "GDC.DASH/CMD.INSIGHT_WIDGET.REMOVE_DRILL_DOWN"
    | "GDC.DASH/CMD.INSIGHT_WIDGET.REMOVE_DRILL_TO_URL"
    | "GDC.DASH/CMD.INSIGHT_WIDGET.ADD_DRILL_DOWN"
    | "GDC.DASH/CMD.INSIGHT_WIDGET.MODIFY_DRILL_DOWN"
    | "GDC.DASH/CMD.INSIGHT_WIDGET.REFRESH"
    | "GDC.DASH/CMD.RICH_TEXT_WIDGET.CHANGE_CONTENT"
    | "GDC.DASH/CMD.RICH_TEXT_WIDGET.CHANGE_FILTER_SETTINGS"
    | "GDC.DASH/CMD.VISUALIZATION_SWITCHER_WIDGET.ADD_VISUALIZATION"
    | "GDC.DASH/CMD.VISUALIZATION_SWITCHER_WIDGET.UPDATE_VISUALIZATIONS"
    | "GDC.DASH/CMD.ALERT.CREATE"
    | "GDC.DASH/CMD.ALERT.SAVE"
    | "GDC.DASH/CMD.SCHEDULED_EMAIL.CREATE"
    | "GDC.DASH/CMD.SCHEDULED_EMAIL.SAVE"
    | "GDC.DASH/CMD.DRILL"
    | "GDC.DASH/CMD.DRILL.DRILL_DOWN"
    | "GDC.DASH/CMD.DRILL.DRILL_TO_INSIGHT"
    | "GDC.DASH/CMD.DRILL.DRILL_TO_DASHBOARD"
    | "GDC.DASH/CMD.DRILL.DRILL_TO_ATTRIBUTE_URL"
    | "GDC.DASH/CMD.DRILL.DRILL_TO_CUSTOM_URL"
    | "GDC.DASH/CMD.DRILL.DRILL_TO_LEGACY_DASHBOARD"
    | "GDC.DASH/CMD.DRILL.DRILLABLE_ITEMS.CHANGE"
    | "GDC.DASH/CMD.DRILL.CROSS_FILTERING"
    | "GDC.DASH/CMD.DRILL.KEY_DRIVER_ANALYSIS"
    | "GDC.DASH/CMD.DRILL_TARGETS.ADD"
    | "GDC.DASH/CMD.RENDER.ASYNC.REQUEST"
    | "GDC.DASH/CMD.RENDER.ASYNC.RESOLVE"
    | "GDC.DASH/CMD.ATTRIBUTE_HIERARCHY_MODIFIED"
    | "GDC.DASH/CMD.AUTOMATIONS.INITIALIZE"
    | "GDC.DASH/CMD.AUTOMATIONS.REFRESH"
    | "GDC.DASH/CMD.FILTER_CONTEXT.FILTER_VIEW.SAVE"
    | "GDC.DASH/CMD.FILTER_CONTEXT.FILTER_VIEW.DELETE"
    | "GDC.DASH/CMD.FILTER_CONTEXT.FILTER_VIEW.APPLY"
    | "GDC.DASH/CMD.FILTER_CONTEXT.FILTER_VIEW.CHANGE_DEFAULT_STATUS"
    | "GDC.DASH/CMD.FILTER_CONTEXT.FILTER_VIEW.RELOAD"
    | "GDC.DASH/CMD.FILTER_CONTEXT.APPLY_WORKING_SELECTION"
    | "GDC.DASH/CMD.FILTER_CONTEXT.RESET_WORKING_SELECTION"
    | "GDC.DASH/CMD.CHANGE_IGNORE_EXECUTION_TIMESTAMP"
    | "GDC.DASH/CMD.TAB.SWITCH"
    | "GDC.DASH/CMD.TAB.REPOSITION"
    | "GDC.DASH/CMD.TAB.CREATE"
    | "GDC.DASH/CMD.TAB.CONVERT_FROM_DEFAULT"
    | "GDC.DASH/CMD.TAB.DELETE"
    | "GDC.DASH/CMD.TAB.RENAME_MODE.START"
    | "GDC.DASH/CMD.TAB.RENAME_MODE.CANCEL"
    | "GDC.DASH/CMD.TAB.RENAME"
    // @internal
    | "GDC.DASH/CMD.USERS.LOAD_ALL"
    | "GDC.DASH/CMD.INSIGHT_WIDGET.EXPORT_RAW"
    | "GDC.DASH/CMD.INSIGHT_WIDGET.EXPORT_SLIDES"
    | "GDC.DASH/CMD.INSIGHT_WIDGET.EXPORT_IMAGE"
    | "GDC.DASH/CMD.SHOW_WIDGET_AS_TABLE.SET";

/**
 * @public
 */
export interface CommandProcessingMeta {
    /**
     * Unique identifier assigned at the time command was submitted for processing.
     */
    readonly uuid: string;
}

/**
 * Base type for all commands.
 *
 * @remarks
 * Commands are dispatched using dispatcher obtained by useDashboardDispatcher(). All the dispatchers are 'contextual' -
 * they target backend, workspace and dashboard in depending on the Dashboard component tree from which the dispatch
 * is done.
 *
 * @public
 */
export interface IDashboardCommand {
    /**
     * Command type. Always starts with "GDC.DASH/CMD"
     */
    readonly type: DashboardCommandType;

    /**
     * Correlation ID can be provided when creating a command.
     *
     * @remarks
     * All events emitted during the command processing will contain the same correlation ID.
     *
     * If the correlation ID is not specified, a random string will be assigned.
     */
    readonly correlationId?: string;

    /**
     * Metadata related to processing of the command by the dashboard component.
     *
     * @remarks
     * Note: this metadata is added by the dashboard component. It will be added dynamically to command
     * right after its dispatch.
     */
    readonly meta?: CommandProcessingMeta;
}
