# (C) 2021 GoodData Corporation
# Used as a temporary solution to serve KD app via Nginx
# Uses locally build KD in the `dist` directory

FROM nginxinc/nginx-unprivileged:1.17.2-alpine

COPY ./../../examples/sdk-examples/dist /usr/share/nginx/html/gooddata-ui-sdk/
COPY nginx/nginx.conf /etc/nginx/nginx.conf

ARG GIT_COMMIT=unspecified
LABEL image_name="GOODDATA UI SDK - development"
LABEL maintainer="RAIL <rail@gooddata.com>"
LABEL git_repository_url="https://github.com/gooddata/gdc-dashboards"
LABEL parent_image="nginxinc/nginx-unprivileged:1.17.2-alpine"
LABEL git_commit=$GIT_COMMIT
