# (C) 2021 GoodData Corporation

FROM nginxinc/nginx-unprivileged:1.21.6-alpine

RUN ls -l

COPY scenarios/build /usr/share/nginx/html/gooddata-ui-sdk/
COPY nginx/nginx.conf /etc/nginx/nginx.conf

ARG GIT_COMMIT=unspecified
LABEL image_name="GOODDATA UI SDK - development"
LABEL maintainer="RAIL <rail@gooddata.com>"
LABEL git_repository_url="https://github.com/gooddata/gooddata-ui-sdk"
LABEL parent_image="nginxinc/nginx-unprivileged:1.21.6-alpine"
LABEL git_commit=$GIT_COMMIT
