// (C) 2022-2025 GoodData Corporation
import { resolve } from "path";
import { existsSync, writeFileSync } from "fs";
import { describe, it, expect } from "vitest";
import { toBackstopJson } from "../stories/_infra/toBackstop";

const targetFile = resolve(__dirname, "stories.json");

/**
 * This makes use of the autogenerated stories barrel file to create BackstopJS config.
 * It has to be done in vitest because vitest provides a way to mock svg and css imports which we do
 * on several places in the SDK, and it is hard to mock using plain typescript or ts-node.
 * Alternative would be a full-blown webpack setup or something similar.
 */
describe("story-extractor", () => {
    it("dumps stories into a file", { timeout: 30000 }, async () => {
        const fileContents = await toBackstopJson();
        writeFileSync(targetFile, fileContents, { encoding: "utf8" });
        expect(existsSync(targetFile)).toBe(true);
    });
});
