// (C) 2025-2026 GoodData Corporation

import type { IConfiguration } from "../types.js";

export const sonarjs: IConfiguration<"sonarjs"> = {
    packages: [
        {
            name: "eslint-plugin-sonarjs",
            version: "3.0.6",
        },
    ],
    plugins: ["sonarjs"],
    extends: ["plugin:sonarjs/recommended-legacy"],
    rules: {
        // we don't mind duplicate string most of the time as they are often checked by TypeScript unions
        "sonarjs/no-duplicate-string": "off",
        // some of these findings are not actionable in a reasonable time
        "sonarjs/cognitive-complexity": "warn",

        "sonarjs/todo-tag": "warn",

        // todo: turn these back on and fix them globally
        "sonarjs/no-hardcoded-passwords": "off",
        "sonarjs/no-alphabetical-sort": "off",
        "sonarjs/no-os-command-from-path": "off",
        "sonarjs/os-command": "off",
        "sonarjs/prefer-regexp-exec": "off",
        "sonarjs/no-clear-text-protocols": "off",
        "sonarjs/deprecation": "off",
        "sonarjs/no-nested-conditional": "off",
        "sonarjs/no-ignored-exceptions": "off",
        "sonarjs/slow-regex": "off",
        "sonarjs/prefer-read-only-props": "off",
        "sonarjs/no-skipped-tests": "off",
        "sonarjs/no-commented-code": "off",
        "sonarjs/no-ignored-return": "off",
        "sonarjs/array-callback-without-return": "off",
        "sonarjs/pseudo-random": "off",
        "sonarjs/no-nested-functions": "off",
        "sonarjs/no-async-constructor": "off",
        "sonarjs/assertions-in-tests": "off",
        "sonarjs/function-return-type": "off",
        "sonarjs/no-unused-vars": "off",
        "sonarjs/no-invariant-returns": "off",
        "sonarjs/different-types-comparison": "off",
        "sonarjs/no-selector-parameter": "off",
        "sonarjs/anchor-precedence": "off",
        "sonarjs/redundant-type-aliases": "off",
        "sonarjs/no-redundant-optional": "off",
        "sonarjs/reduce-initial-value": "off",
        "sonarjs/no-globals-shadowing": "off",
        "sonarjs/use-type-alias": "off",
        "sonarjs/void-use": "off",
        "sonarjs/no-undefined-argument": "off",
        "sonarjs/no-useless-react-setstate": "off",
        "sonarjs/no-inverted-boolean-check": "off",
        "sonarjs/concise-regex": "off",
        "sonarjs/no-dead-store": "off",
        "sonarjs/public-static-readonly": "off",
        "sonarjs/code-eval": "off",
        "sonarjs/no-misleading-array-reverse": "off",
        "sonarjs/fixme-tag": "off",
        "sonarjs/argument-type": "off",
        "sonarjs/constructor-for-side-effects": "off",
        "sonarjs/no-useless-intersection": "off",
        "sonarjs/no-empty-test-file": "off",
        "sonarjs/prefer-default-last": "off",
        "sonarjs/prefer-promise-shorthand": "off",
        "sonarjs/no-unsafe-unzip": "off",
        "sonarjs/no-nested-assignment": "off",
        "sonarjs/generator-without-yield": "off",
        "sonarjs/no-try-promise": "off",
        "sonarjs/single-character-alternation": "off",
        "sonarjs/class-name": "off",
        "sonarjs/no-hardcoded-secrets": "off",
        "sonarjs/regex-complexity": "off",
        "sonarjs/post-message": "off",
        "sonarjs/link-with-target-blank": "off",
        "sonarjs/duplicates-in-character-class": "off",
        "sonarjs/arguments-order": "off",
        "sonarjs/empty-string-repetition": "off",
        "sonarjs/table-header": "off",
        "sonarjs/no-implicit-global": "off",
        "sonarjs/no-control-regex": "off",
    },
    overrides: [
        {
            files: ["*.test.ts", "*.test.tsx", "*.spec.ts"],
            rules: {
                // we do not care about duplicate functions in test files, they often make sense (e.g. in different describe blocks)
                "sonarjs/no-identical-functions": "off",
            },
        },
    ],
};
