#!/bin/sh
# Called by "git commit" with no arguments.  The hook should
# exit with non-zero status after issuing an appropriate message if
# it wants to stop the commit.

# Invoke the "rush lint-staged-files" custom command to lint files whenever they
# are committed. The command is defined in common/config/rush/command-line.json
# and uses the "lint-staged" autoinstaller.
node common/scripts/install-run-rush.js lint-staged-files || exit $?
