// (C) 2026 GoodData Corporation

import { cpSync, mkdirSync, readFileSync, readdirSync, writeFileSync } from "fs";
import { join } from "path";

import type { TokenReplacements } from "../types.js";

/**
 * Directories that should never be copied. Tooling output (`node_modules`,
 * `esm`, `dist`, `.rush`, etc.) gets regenerated by the consumer's package
 * manager once the new module is installed, and including them would balloon
 * the published tarball and risk shipping stale .tsbuildinfo / .vite caches.
 */
const SKIP_DIRS = new Set(["node_modules", "esm", "dist", ".rush", "rush-logs", ".__mf__temp", ".vite"]);

const SKIP_SUFFIXES = [".tsbuildinfo"];

/**
 * Files for which token-substitution-in-text would corrupt the byte stream.
 * Binary files must be copied verbatim.
 */
const BINARY_EXTENSIONS = new Set([
    ".ico",
    ".png",
    ".jpg",
    ".jpeg",
    ".gif",
    ".woff",
    ".woff2",
    ".ttf",
    ".eot",
]);

export interface ICopyResult {
    /** Absolute paths of every file written. Used for the package.json transform pass. */
    written: string[];
}

/**
 * Recursively copies srcDir → destDir applying ordered string replacement to
 * every non-binary file. Returns the list of files written so the caller can
 * post-process specific paths (e.g. transformPackageJson).
 */
export function copyTemplate(srcDir: string, destDir: string, replacements: TokenReplacements): ICopyResult {
    const written: string[] = [];
    copyRecursive(srcDir, destDir, replacements, written);
    return { written };
}

function copyRecursive(
    srcDir: string,
    destDir: string,
    replacements: TokenReplacements,
    written: string[],
): void {
    mkdirSync(destDir, { recursive: true });

    for (const entry of readdirSync(srcDir, { withFileTypes: true })) {
        const srcPath = join(srcDir, entry.name);
        const destPath = join(destDir, entry.name);

        // Symlinks and rush-style packages-link dirs would not survive npm-pack anyway —
        // and copying them in client repos would yank in unrelated workspace state.
        if (entry.isSymbolicLink() || entry.name === "packages-link") continue;

        if (entry.isDirectory()) {
            if (SKIP_DIRS.has(entry.name)) continue;
            copyRecursive(srcPath, destPath, replacements, written);
            continue;
        }

        if (SKIP_SUFFIXES.some((s) => entry.name.endsWith(s))) continue;

        copyFile(srcPath, destPath, entry.name, replacements, written);
    }
}

function copyFile(
    srcPath: string,
    destPath: string,
    name: string,
    replacements: TokenReplacements,
    written: string[],
): void {
    const ext = name.slice(name.lastIndexOf(".")).toLowerCase();
    if (BINARY_EXTENSIONS.has(ext)) {
        cpSync(srcPath, destPath);
        written.push(destPath);
        return;
    }

    let content = readFileSync(srcPath, "utf-8");
    for (const [token, value] of replacements) {
        content = content.replaceAll(token, value);
    }
    writeFileSync(destPath, content, "utf-8");
    written.push(destPath);
}
