// (C) 2019-2023 GoodData Corporation
/**
 * This package provides domain models for GoodData.UI.
 *
 * @remarks
 * These domain models are backend-agnostic. This makes them reusable across different Analytical Backend implementations.
 * The package includes TypeScript type definitions, factory functions, functions to get or set certain
 * properties of the objects in an immutable way, and more.
 * These are used in both the `@gooddata/sdk-backend-*` and `@gooddata/sdk-ui*` packages.
 *
 * @packageDocumentation
 */
export { DateAttributeGranularity, DateGranularity, AllTimeGranularity } from "./base/dateGranularities.js";
export { IAuditable, IAuditableDates, IAuditableUsers } from "./base/metadata.js";
export { ComparatorDirection, IComparator } from "./base/comparators.js";

export {
    IAttribute,
    IAttributeBody,
    isAttribute,
    attributeLocalId,
    AttributePredicate,
    anyAttribute,
    idMatchAttribute,
    attributesFind,
    attributeUri,
    attributeIdentifier,
    attributeAlias,
    attributeShowAllValues,
    attributeDisplayFormRef,
} from "./execution/attribute/index.js";

export {
    newAttribute,
    modifyAttribute,
    AttributeBuilder,
    AttributeModifications,
    AttributeBuilderInput,
} from "./execution/attribute/factory.js";

export {
    ObjectType,
    Identifier,
    Uri,
    UriRef,
    IdentifierRef,
    LocalIdRef,
    ObjRef,
    ObjRefInScope,
    isUriRef,
    isIdentifierRef,
    objRefToString,
    isLocalIdRef,
    areObjRefsEqual,
    isObjRef,
    serializeObjRef,
    deserializeObjRef,
} from "./objRef/index.js";

export {
    IDimension,
    isDimension,
    dimensionTotals,
    DimensionItem,
    newTwoDimensional,
    newDimension,
    MeasureGroupIdentifier,
    dimensionSetTotals,
    dimensionsFindItem,
    ItemInDimension,
} from "./execution/base/dimension.js";

export { idRef, uriRef, localIdRef } from "./objRef/factory.js";

export { TotalType, ITotal, isTotal, newTotal, totalIsNative } from "./execution/base/totals.js";

export {
    SortDirection,
    ISortDirection,
    IAttributeSortItem,
    IAttributeSortTarget,
    IAttributeSortType,
    ISortItem,
    IMeasureSortItem,
    IMeasureSortTarget,
    ILocatorItem,
    IAttributeLocatorItem,
    IAttributeLocatorItemBody,
    IMeasureLocatorItem,
    IMeasureLocatorItemBody,
    ITotalLocatorItem,
    ITotalLocatorItemBody,
    isMeasureLocator,
    isAttributeLocator,
    isTotalLocator,
    isMeasureSort,
    isAttributeSort,
    isAttributeAreaSort,
    isAttributeValueSort,
    newMeasureSort,
    newMeasureSortFromLocators,
    newAttributeSort,
    newAttributeAreaSort,
    newAttributeLocator,
    SortEntityIds,
    sortEntityIds,
    sortDirection,
    sortMeasureLocators,
    attributeLocatorElement,
    attributeLocatorIdentifier,
    measureLocatorIdentifier,
} from "./execution/base/sort.js";

export {
    IAttributeElementsByRef,
    IAttributeElementsByValue,
    IAttributeElements,
    IPositiveAttributeFilter,
    IPositiveAttributeFilterBody,
    INegativeAttributeFilter,
    INegativeAttributeFilterBody,
    IAbsoluteDateFilter,
    IRelativeDateFilter,
    IMeasureValueFilter,
    IMeasureValueFilterBody,
    IRankingFilter,
    IRankingFilterBody,
    RankingFilterOperator,
    isRankingFilter,
    IFilter,
    INullableFilter,
    IMeasureFilter,
    IDateFilter,
    IAttributeFilter,
    isAbsoluteDateFilter,
    isRelativeDateFilter,
    isAllTimeDateFilter,
    attributeElementsIsEmpty,
    attributeElementsCount,
    updateAttributeElementsItems,
    getAttributeElementsItems,
    isPositiveAttributeFilter,
    isNegativeAttributeFilter,
    isDateFilter,
    isMeasureValueFilter,
    ComparisonConditionOperator,
    IComparisonCondition,
    IComparisonConditionBody,
    IRangeCondition,
    IRangeConditionBody,
    MeasureValueFilterCondition,
    RangeConditionOperator,
    isAttributeFilter,
    isAttributeElementsByRef,
    isAttributeElementsByValue,
    isComparisonCondition,
    isComparisonConditionOperator,
    isFilter,
    isRangeCondition,
    isRangeConditionOperator,
    filterIsEmpty,
    filterAttributeElements,
    filterMeasureRef,
    filterObjRef,
    IAbsoluteDateFilterValues,
    IRelativeDateFilterValues,
    absoluteDateFilterValues,
    relativeDateFilterValues,
    measureValueFilterCondition,
    measureValueFilterMeasure,
    measureValueFilterOperator,
} from "./execution/filter/index.js";

export {
    newAbsoluteDateFilter,
    newNegativeAttributeFilter,
    newPositiveAttributeFilter,
    newRelativeDateFilter,
    newAllTimeFilter,
    newMeasureValueFilter,
    newRankingFilter,
} from "./execution/filter/factory.js";

export { mergeFilters } from "./execution/filter/filterMerge.js";

export {
    IMeasureTitle,
    IMeasureTitleBody,
    IMeasureDefinitionType,
    IMeasureDefinition,
    IMeasureDefinitionBody,
    ArithmeticMeasureOperator,
    IArithmeticMeasureDefinition,
    IPoPMeasureDefinition,
    IPoPMeasureDefinitionBody,
    IMeasure,
    IMeasureBody,
    MeasureAggregation,
    IInlineMeasureDefinition,
    IPreviousPeriodMeasureDefinition,
    IPreviousPeriodMeasureDefinitionBody,
    IPreviousPeriodDateDataSet,
    isMeasure,
    isSimpleMeasure,
    isInlineMeasure,
    isAdhocMeasure,
    isPoPMeasure,
    isPreviousPeriodMeasure,
    isArithmeticMeasure,
    isMeasureDefinition,
    isPoPMeasureDefinition,
    isPreviousPeriodMeasureDefinition,
    isArithmeticMeasureDefinition,
    isInlineMeasureDefinition,
    measureLocalId,
    MeasurePredicate,
    anyMeasure,
    idMatchMeasure,
    measureDoesComputeRatio,
    measureItem,
    measureUri,
    measureIdentifier,
    measureMasterIdentifier,
    measureArithmeticOperands,
    measureAlias,
    measureTitle,
    measureArithmeticOperator,
    measureFormat,
    isMeasureFormatInPercent,
    measureAggregation,
    measureFilters,
    measurePopAttribute,
    measurePreviousPeriodDateDataSets,
    MeasureOrLocalId,
} from "./execution/measure/index.js";

export {
    IPreviousPeriodDateDataSetSimple,
    ArithmeticMeasureBuilder,
    MeasureBuilder,
    MeasureModifications,
    PoPMeasureBuilder,
    PreviousPeriodMeasureBuilder,
    InlineMeasureBuilder,
    MeasureBuilderBase,
    newMeasure,
    modifyMeasure,
    modifySimpleMeasure,
    modifyPopMeasure,
    modifyPreviousPeriodMeasure,
    modifyInlineMeasure,
    newArithmeticMeasure,
    newPopMeasure,
    newPreviousPeriodMeasure,
    newInlineMeasure,
    MeasureEnvelope,
    InlineMeasureBuilderInput,
    ArithmeticMeasureBuilderInput,
    PoPMeasureBuilderInput,
    PreviousPeriodMeasureBuilderInput,
} from "./execution/measure/factory.js";

export {
    IAttributeOrMeasure,
    IBucket,
    isBucket,
    idMatchBucket,
    anyBucket,
    MeasureInBucket,
    AttributeInBucket,
    newBucket,
    bucketIsEmpty,
    bucketAttributes,
    bucketAttribute,
    bucketAttributeIndex,
    bucketMeasure,
    bucketMeasureIndex,
    bucketMeasures,
    bucketTotals,
    bucketSetTotals,
    bucketItems,
    BucketPredicate,
    applyRatioRule,
    ComputeRatioRule,
    disableComputeRatio,
    BucketItemModifications,
    BucketItemReducer,
    bucketModifyItems,
    bucketItemReduce,
} from "./execution/buckets/index.js";

export {
    bucketsFind,
    bucketsMeasures,
    bucketsIsEmpty,
    bucketsAttributes,
    bucketsFindMeasure,
    bucketsById,
    bucketsFindAttribute,
    bucketsItems,
    bucketsTotals,
    bucketsModifyItem,
    bucketsReduceItem,
} from "./execution/buckets/bucketArray.js";

export { bucketItemLocalId } from "./execution/buckets/bucketItem.js";

export {
    IExecutionDefinition,
    IExecutionConfig,
    DimensionGenerator,
    defWithFilters,
    defFingerprint,
    defSetDimensions,
    defSetSorts,
    defTotals,
    defSetExecConfig,
    IPostProcessing,
    defSetPostProcessing,
} from "./execution/executionDefinition/index.js";

export {
    newDefForItems,
    newDefForBuckets,
    newDefForInsight,
    defWithDimensions,
    defWithSorting,
    defWithPostProcessing,
    defWithDateFormat,
    defWithExecConfig,
    defaultDimensionsGenerator,
    emptyDef,
} from "./execution/executionDefinition/factory.js";

export {
    GuidType,
    RgbType,
    IRgbColorValue,
    IColor,
    IColorPalette,
    IColorPaletteItem,
    IColorFromPalette,
    IRgbColor,
    isColorFromPalette,
    isRgbColor,
    isColorPaletteItem,
    colorPaletteItemToRgb,
    colorPaletteToColors,
    IColorPaletteMetadataObject,
    IColorPaletteDefinition,
} from "./colors/index.js";

export {
    IInsight,
    IInsightDefinition,
    IVisualizationClass,
    IVisualizationClassBody,
    VisualizationProperties,
    IColorMappingItem,
    isInsight,
    isColorMappingItem,
    insightRef,
    insightId,
    insightItems,
    insightMeasures,
    insightHasMeasures,
    insightAttributes,
    insightHasAttributes,
    insightHasDataDefined,
    insightProperties,
    insightBuckets,
    insightSorts,
    insightBucket,
    insightTags,
    insightSummary,
    insightTitle,
    insightUri,
    insightIsLocked,
    insightCreated,
    insightCreatedBy,
    insightUpdated,
    insightUpdatedBy,
    insightTotals,
    insightFilters,
    insightVisualizationUrl,
    insightVisualizationType,
    insightSetFilters,
    insightSetBuckets,
    insightSetProperties,
    insightSetSorts,
    insightModifyItems,
    insightReduceItems,
    InsightDisplayFormUsage,
    insightDisplayFormUsage,
    visClassUrl,
    visClassId,
    visClassUri,
} from "./insight/index.js";

export {
    insightCreatedComparator,
    insightCreatedByComparator,
    insightTitleComparator,
    insightUpdatedComparator,
    insightUpdatedByComparator,
} from "./insight/comparators.js";

export { newInsightDefinition, InsightDefinitionBuilder, InsightModifications } from "./insight/factory.js";

export { insightSanitize, sanitizeBucketTotals } from "./insight/sanitization.js";

export { factoryNotationFor } from "./execution/objectFactoryNotation/index.js";

export {
    DateFilterOptionAbsoluteFormType,
    DateFilterOptionAbsolutePresetType,
    DateFilterOptionAllTimeType,
    DateFilterOptionType,
    DateFilterOptionRelativeFormType,
    DateFilterOptionRelativePresetType,
    RelativeDateFilterGranularityOffset,
    DateFilterGranularity,
    DateString,
    IAbsoluteDateFilterForm,
    IAbsoluteDateFilterPreset,
    IAllTimeDateFilterOption,
    IDateFilterConfig,
    IDateFilterOption,
    IRelativeDateFilterForm,
    IRelativeDateFilterPreset,
    IRelativeDateFilterPresetOfGranularity,
    isAbsoluteDateFilterForm,
    isAbsoluteDateFilterPreset,
    isAllTimeDateFilterOption,
    isDateFilterGranularity,
    isRelativeDateFilterForm,
    isRelativeDateFilterPreset,
} from "./dateFilterConfig/index.js";

export { IDashboardObjectIdentity } from "./dashboard/common.js";

export {
    DateFilterAbsoluteType,
    DateFilterRelativeType,
    DateFilterType,
    FilterContextItem,
    IDashboardAttributeFilter,
    DashboardAttributeFilterSelectionMode,
    IDashboardAttributeFilterParent,
    IDashboardAttributeFilterReference,
    IDashboardDateFilter,
    IDashboardDateFilterReference,
    IDashboardFilterReference,
    IFilterContext,
    IFilterContextBase,
    IFilterContextDefinition,
    ITempFilterContext,
    dashboardFilterReferenceObjRef,
    isAllTimeDashboardDateFilter,
    isDashboardAttributeFilter,
    isSingleSelectionFilter,
    isNegativeAttributeFilter as isNegativeDashboardAttributeFilter,
    getSelectedElementsCount,
    isDashboardAttributeFilterReference,
    isDashboardDateFilter,
    isRelativeDashboardDateFilter,
    isAbsoluteDashboardDateFilter,
    isDashboardDateFilterReference,
    isFilterContext,
    isFilterContextDefinition,
    isTempFilterContext,
    newAbsoluteDashboardDateFilter,
    newAllTimeDashboardDateFilter,
    newRelativeDashboardDateFilter,
} from "./dashboard/filterContext.js";

export {
    IWidgetAlert,
    IWidgetAlertBase,
    IWidgetAlertDefinition,
    isWidgetAlert,
    isWidgetAlertDefinition,
} from "./dashboard/alert.js";

export {
    DrillDefinition,
    DrillOrigin,
    DrillOriginType,
    DrillTransition,
    DrillType,
    IDrill,
    IDrillFromAttribute,
    IDrillFromMeasure,
    IDrillOrigin,
    IDrillTarget,
    IDrillToAttributeUrl,
    IDrillToAttributeUrlTarget,
    IDrillToCustomUrl,
    IDrillToCustomUrlTarget,
    IDrillToDashboard,
    IDrillToInsight,
    IDrillToLegacyDashboard,
    InsightDrillDefinition,
    KpiDrillDefinition,
    isDrillFromAttribute,
    isDrillFromMeasure,
    isDrillToAttributeUrl,
    isDrillToCustomUrl,
    isDrillToDashboard,
    isDrillToInsight,
    isDrillToLegacyDashboard,
} from "./dashboard/drill.js";

export {
    BuiltInWidgetTypes,
    IBaseWidget,
    IDrillableWidget,
    IFilterableWidget,
    IWidgetDescription,
} from "./dashboard/baseWidget.js";

export {
    IKpi,
    IKpiBase,
    IKpiComparisonDirection,
    IKpiComparisonTypeComparison,
    IKpiWithPopComparison,
    IKpiWithPreviousPeriodComparison,
    IKpiWithComparison,
    IKpiWithoutComparison,
    isKpiWithComparison,
    isKpiWithoutComparison,
    isKpi,
} from "./dashboard/kpi.js";

export {
    AnalyticalWidgetType,
    IAnalyticalWidget,
    IKpiWidget,
    IKpiWidgetBase,
    IKpiWidgetDefinition,
    IKpiWidgetConfiguration,
    IKpiWidgetDescriptionConfiguration,
    KpiWidgetDescriptionSourceType,
    IInsightWidget,
    IInsightWidgetBase,
    IInsightWidgetDefinition,
    IInsightWidgetConfiguration,
    IInsightWidgetDescriptionConfiguration,
    InsightWidgetDescriptionSourceType,
} from "./dashboard/analyticalWidgets.js";

export {
    CatalogItemType,
    CatalogItem,
    ICatalogGroup,
    ICatalogAttribute,
    ICatalogFact,
    ICatalogMeasure,
    ICatalogDateDataset,
    ICatalogDateAttribute,
    isCatalogAttribute,
    isCatalogFact,
    isCatalogMeasure,
    isCatalogDateDataset,
    ICatalogItemBase,
    IGroupableCatalogItemBase,
    GroupableCatalogItem,
    catalogItemMetadataObject,
} from "./ldm/catalog/index.js";

export {
    IAttributeDisplayFormMetadataObject,
    isAttributeDisplayFormMetadataObject,
    AttributeDisplayFormType,
    IAttributeMetadataObject,
    isAttributeMetadataObject,
    IDataSetMetadataObject,
    isDataSetMetadataObject,
    IVariableMetadataObject,
    isVariableMetadataObject,
    IFactMetadataObject,
    isFactMetadataObject,
    IMetadataObjectDefinition,
    IMeasureMetadataObject,
    IMeasureMetadataObjectBase,
    isMeasureMetadataObject,
    IMeasureMetadataObjectDefinition,
    isMeasureMetadataObjectDefinition,
    IMetadataObject,
    IMetadataObjectBase,
    IMetadataObjectIdentity,
    isMetadataObject,
    MetadataObject,
    metadataObjectId,
    IDashboardMetadataObject,
    isDashboardMetadataObject,
    attributeDisplayFormMetadataObjectAttributeRef,
    attributeDisplayFormMetadataObjectRef,
    attributeDisplayFormMetadataObjectTitle,
} from "./ldm/metadata/index.js";

export {
    DataColumnType,
    DatasetLoadStatus,
    IDataColumnBody,
    IDataColumn,
    IDataHeader,
    IDatasetLoadInfo,
    IDatasetUser,
    IDataset,
    IDatasetBody,
} from "./ldm/datasets/index.js";

export { IAttributeElement } from "./ldm/attributeElement.js";

export {
    IWidget,
    IWidgetDefinition,
    isWidget,
    isWidgetDefinition,
    widgetUri,
    widgetId,
    widgetRef,
    widgetTitle,
    widgetType,
    isKpiWidgetDefinition,
    isKpiWidget,
    isInsightWidgetDefinition,
    isInsightWidget,
} from "./dashboard/widget.js";

export {
    IDashboardAttachment,
    isDashboardAttachment,
    IWidgetAttachment,
    isWidgetAttachment,
    IExportOptions,
    IScheduledMail,
    IScheduledMailDefinition,
    ScheduledMailAttachment,
    IScheduledMailBase,
} from "./dashboard/scheduledMail.js";

export { IUser, IWorkspaceUser, userFullName } from "./user/index.js";

export {
    IDashboardLayout,
    IDashboardWidget,
    IDashboardLayoutSection,
    IDashboardLayoutSectionHeader,
    IDashboardLayoutSize,
    IDashboardLayoutSizeByScreenSize,
    IDashboardLayoutItem,
    ScreenSize,
    isDashboardLayout,
    isDashboardLayoutSection,
    isDashboardLayoutItem,
    isDashboardWidget,
} from "./dashboard/layout.js";

export {
    IDashboard,
    IDashboardDefinition,
    IListedDashboard,
    ListedDashboardAvailability,
    IDashboardBase,
    IDashboardDateFilterConfig,
    DashboardDateFilterConfigMode,
    IDashboardDateFilterAddedPresets,
    IDashboardPluginBase,
    IDashboardPlugin,
    IDashboardPluginDefinition,
    IDashboardPluginLink,
    isDashboard,
    isDashboardDefinition,
    IAccessControlAware,
    ShareStatus,
    IDashboardPermissions,
    IExistingDashboard,
} from "./dashboard/dashboard.js";

export { ISeparators, ISettings, PlatformEdition, IWhiteLabeling, WeekStart } from "./settings/index.js";

export { IWorkspaceUserGroup } from "./userGroup/index.js";

export {
    ThemeFontUri,
    ThemeColor,
    IThemeColorFamily,
    IThemeComplementaryPalette,
    IThemeWidgetTitle,
    IThemeTypography,
    IThemePalette,
    IThemeKpi,
    IThemeKpiValue,
    IThemeChart,
    IThemeTable,
    ITheme,
    IThemeAnalyticalDesigner,
    IThemeAnalyticalDesignerTitle,
    IThemeButton,
    IThemeDashboard,
    IThemeDashboardContent,
    IThemeDashboardContentKpi,
    IThemeDashboardContentWidget,
    IThemeDashboardEditPanel,
    IThemeDashboardFilterBar,
    IThemeDashboardFilterBarButton,
    IThemeDashboardNavigation,
    IThemeDashboardNavigationItem,
    IThemeDashboardNavigationTitle,
    IThemeDashboardSection,
    IThemeDashboardSectionDescription,
    IThemeDashboardSectionTitle,
    IThemeDashboardTitle,
    IThemeMetadataObject,
    IThemeDefinition,
    IThemeModal,
    IThemeModalTitle,
    IThemeTooltip,
} from "./theme/index.js";

export { IWorkspacePermissions, WorkspacePermission } from "./permissions/index.js";

export {
    DataValue,
    IMeasureDescriptor,
    IMeasureDescriptorObject,
    IMeasureDescriptorItem,
    IDimensionItemDescriptor,
    IDimensionDescriptor,
    IAttributeHeaderFormOf,
    IAttributeDescriptorBody,
    IAttributeDescriptor,
    IMeasureGroupDescriptor,
    IResultAttributeHeader,
    IResultHeader,
    IResultMeasureHeader,
    IResultAttributeHeaderItem,
    IResultMeasureHeaderItem,
    IResultTotalHeader,
    IResultTotalHeaderItem,
    ITotalDescriptor,
    ITotalDescriptorItem,
    IResultWarning,
    IColorDescriptor,
    IColorDescriptorItem,
    isColorDescriptor,
    isAttributeDescriptor,
    isMeasureGroupDescriptor,
    isTotalDescriptor,
    isMeasureDescriptor,
    isResultAttributeHeader,
    isResultMeasureHeader,
    isResultTotalHeader,
    resultHeaderName,
    attributeDescriptorLocalId,
    attributeDescriptorName,
} from "./execution/results/index.js";

export {
    AccessGranteeDetail,
    IAccessGrantee,
    IUserAccess,
    IUserAccessGrantee,
    IUserGroupAccess,
    IUserGroupAccessGrantee,
    isUserAccess,
    isUserAccessGrantee,
    isUserGroupAccess,
    isUserGroupAccessGrantee,
    IGranularAccessGrantee,
    AccessGranularPermission,
    IGranteeGranularity,
    IAvailableAccessGrantee,
    IAvailableUserAccessGrantee,
    IAvailableUserGroupAccessGrantee,
    IGranularUserAccess,
    IGranularUserGroupAccess,
    IGranularUserAccessGrantee,
    IGranularUserGroupAccessGrantee,
    isGranularAccess,
    isAvailableUserGroupAccessGrantee,
    isAvailableUserAccessGrantee,
    isGranularAccessGrantee,
    isGranularUserAccessGrantee,
    isGranularUserGroupAccessGrantee,
    isGranularUserAccess,
    isGranularUserGroupAccess,
} from "./accessControl/index.js";

export { IOrganizationDescriptor } from "./organization/index.js";
export { IEntitlementsName, IEntitlementDescriptor } from "./entitlements/index.js";
