// (C) 2019-2026 GoodData Corporation

/* oxlint-disable no-barrel-files/no-barrel-files */

/**
 * This package provides domain models for GoodData.UI.
 *
 * @remarks
 * These domain models are backend-agnostic. This makes them reusable across different Analytical Backend implementations.
 * The package includes TypeScript type definitions, factory functions, functions to get or set certain
 * properties of the objects in an immutable way, and more.
 * These are used in both the `@gooddata/sdk-backend-*` and `@gooddata/sdk-ui*` packages.
 *
 * @packageDocumentation
 */
export {
    type DateAttributeGranularity,
    type AllTimeGranularity,
    DateGranularity,
} from "./base/dateGranularities.js";
export type { IAuditable, IAuditableDates, IAuditableUsers } from "./base/metadata.js";
export type { ComparatorDirection, IComparator } from "./base/comparators.js";
export { assertNever } from "./base/typeUtils.js";

export {
    type IAttribute,
    type IAttributeBody,
    type AttributePredicate,
    isAttribute,
    attributeLocalId,
    anyAttribute,
    idMatchAttribute,
    attributesFind,
    attributeUri,
    attributeIdentifier,
    attributeAlias,
    attributeShowAllValues,
    attributeDisplayFormRef,
} from "./execution/attribute/index.js";

export {
    type AttributeModifications,
    type AttributeBuilderInput,
    newAttribute,
    modifyAttribute,
    AttributeBuilder,
} from "./execution/attribute/factory.js";

export {
    type INotificationChannelMetadataObjectBase,
    type ICustomSmtpDestinationConfiguration,
    type IDefaultSmtpDestinationConfiguration,
    type IInPlatformNotificationChannelMetadataObject,
    type IInPlatformNotificationChannelMetadataObjectDefinition,
    type ISmtpDestinationConfiguration,
    type ISmtpNotificationChannelMetadataObject,
    type ISmtpNotificationChannelMetadataObjectDefinition,
    type IWebhookDestinationConfiguration,
    type IWebhookNotificationChannelMetadataObject,
    type IWebhookNotificationChannelMetadataObjectDefinition,
    type NotificationChannelAllowedRecipients,
    type NotificationChannelDestinationType,
    type INotificationChannelMetadataObject,
    type INotificationChannelMetadataObjectDefinition,
    type NotificationChannelDashboardLinkVisibility,
    type INotificationChannelTestResponse,
    type ToNotificationChannelMetadataObject,
    type INotificationChannelIdentifier,
    type INotificationChannelExternalRecipient,
    isNotificationChannelMetadataObject,
    isNotificationChannelMetadataObjectDefinition,
} from "./notificationChannels/index.js";
export {
    type AlertDescriptionStatus,
    type AutomationNotificationType,
    type IAlertDescription,
    type IAlertEvaluationRow,
    type IAlertEvaluationRowMetric,
    type IAlertNotification,
    type IAlertNotificationDetails,
    type IAutomationNotificationDetailsBase,
    type INotification,
    type INotificationBase,
    type IScheduleNotification,
    type IScheduleNotificationDetails,
    type ITestNotification,
    type ITestNotificationDetails,
    type IWebhookAutomationInfo,
    type IWebhookMessageDataAlert,
    type IWebhookMessageDataBase,
    type IWebhookMessageDataSchedule,
    type NotificationType,
    type WebhookRecipient,
    type AlertFilters,
    isAlertNotification,
    isScheduleNotification,
    isTestNotification,
    isNotification,
} from "./notifications/index.js";

export {
    type ObjectType,
    type ObjectOrigin,
    type Identifier,
    type Uri,
    type UriRef,
    type IdentifierRef,
    type LocalIdRef,
    type ObjRef,
    type ObjRefInScope,
    isUriRef,
    isIdentifierRef,
    objRefToString,
    isLocalIdRef,
    areObjRefsEqual,
    isObjRef,
    serializeObjRef,
    deserializeObjRef,
} from "./objRef/index.js";

export {
    type IDimension,
    type DimensionItem,
    type ItemInDimension,
    isDimension,
    dimensionTotals,
    newTwoDimensional,
    newDimension,
    MeasureGroupIdentifier,
    dimensionSetTotals,
    dimensionsFindItem,
    isMeasureGroupIdentifier,
} from "./execution/base/dimension.js";

export { idRef, uriRef, localIdRef } from "./objRef/factory.js";

export { type TotalType, type ITotal, isTotal, newTotal, totalIsNative } from "./execution/base/totals.js";

export {
    type SortDirection,
    type ISortDirection,
    type IAttributeSortItem,
    type IAttributeSortTarget,
    type IAttributeSortType,
    type ISortItem,
    type IMeasureSortItem,
    type IMeasureSortTarget,
    type ILocatorItem,
    type IAttributeLocatorItem,
    type IAttributeLocatorItemBody,
    type IMeasureLocatorItem,
    type IMeasureLocatorItemBody,
    type ITotalLocatorItem,
    type ITotalLocatorItemBody,
    type SortEntityIds,
    isMeasureLocator,
    isAttributeLocator,
    isTotalLocator,
    isMeasureSort,
    isAttributeSort,
    isAttributeAreaSort,
    isAttributeValueSort,
    newMeasureSort,
    newMeasureSortFromLocators,
    newAttributeSort,
    newAttributeAreaSort,
    newAttributeLocator,
    newAttributeLocatorWithNullElement,
    sortEntityIds,
    sortDirection,
    sortMeasureLocators,
    attributeLocatorElement,
    attributeLocatorIdentifier,
    measureLocatorIdentifier,
} from "./execution/base/sort.js";

export {
    type IAttributeElementsByRef,
    type IAttributeElementsByValue,
    type IAttributeElements,
    type IPositiveAttributeFilter,
    type IPositiveAttributeFilterBody,
    type INegativeAttributeFilter,
    type INegativeAttributeFilterBody,
    type IAbsoluteDateFilter,
    type IRelativeDateFilter,
    type IMeasureValueFilter,
    type IMeasureValueFilterBody,
    type IRankingFilter,
    type IRankingFilterBody,
    type RankingFilterOperator,
    type IFilter,
    type IIdentifiableFilter,
    type INullableFilter,
    type IMeasureFilter,
    type IDateFilter,
    type IAttributeFilter,
    type ComparisonConditionOperator,
    type IComparisonCondition,
    type IComparisonConditionBody,
    type IRangeCondition,
    type IRangeConditionBody,
    type MeasureValueFilterCondition,
    type RangeConditionOperator,
    type IAbsoluteDateFilterValues,
    type IRelativeDateFilterValues,
    type IAbsoluteDateFilterBody,
    type IRelativeDateFilterBody,
    type IRelativeDateFilterAllTimeBody,
    type IRelativeBoundedDateFilterBody,
    type IUpperBoundedFilter,
    type ILowerBoundedFilter,
    type EmptyValues,
    isRankingFilter,
    isAbsoluteDateFilter,
    isRelativeDateFilter,
    isAllTimeDateFilter,
    attributeElementsIsEmpty,
    attributeElementsCount,
    updateAttributeElementsItems,
    getAttributeElementsItems,
    isSimpleMeasureFilter,
    isPositiveAttributeFilter,
    isNegativeAttributeFilter,
    isDateFilter,
    isMeasureValueFilter,
    isAttributeFilter,
    isAttributeElementsByRef,
    isAttributeElementsByValue,
    isComparisonCondition,
    isComparisonConditionOperator,
    isFilter,
    isRangeCondition,
    isRangeConditionOperator,
    filterIsEmpty,
    filterAttributeElements,
    filterMeasureRef,
    filterObjRef,
    filterLocalIdentifier,
    absoluteDateFilterValues,
    relativeDateFilterValues,
    measureValueFilterCondition,
    measureValueFilterConditions,
    hasMeasureValueFilterConditions,
    measureValueFilterDimensionality,
    measureValueFilterMeasure,
    measureValueFilterOperator,
    measureValueFilterOperators,
    isRelativeBoundedDateFilterBody,
    isRelativeUpperBoundedDateFilterBody,
    isRelativeLowerBoundedDateFilterBody,
    isRelativeBoundedDateFilter,
    isRelativeUpperBoundedDateFilter,
    isRelativeLowerBoundedDateFilter,
    isAllTimeDateFilterWithEmptyValueHandling,
    isNoopAllTimeDateFilter,
    isDateFilterWithEmptyValueHandling,
    isLowerBound,
    isUpperBound,
} from "./execution/filter/index.js";

export {
    type IMeasureValueFilterComparisonOptions,
    type IMeasureValueFilterRangeOptions,
    type IMeasureValueFilterOptions,
    type IMeasureValueFilterAllOptions,
    type IMeasureValueFilterConditionsOptions,
    type OptionsCondition,
    type IOptionsComparisonCondition,
    type IOptionsRangeCondition,
    type IOptionsAllCondition,
    newAbsoluteDateFilter,
    newNegativeAttributeFilter,
    newPositiveAttributeFilter,
    newRelativeDateFilter,
    newAllTimeFilter,
    newMeasureValueFilter,
    newMeasureValueFilterWithOptions,
    newRankingFilter,
} from "./execution/filter/factory.js";

export { mergeFilters } from "./execution/filter/filterMerge.js";

export {
    type IMeasureTitle,
    type IMeasureTitleBody,
    type IMeasureDefinitionType,
    type IMeasureDefinition,
    type IMeasureDefinitionBody,
    type ArithmeticMeasureOperator,
    type IArithmeticMeasureDefinition,
    type IVirtualArithmeticMeasureDefinition,
    type IPoPMeasureDefinition,
    type IPoPMeasureDefinitionBody,
    type IMeasure,
    type IMeasureBody,
    type MeasureAggregation,
    type IInlineMeasureDefinition,
    type IPreviousPeriodMeasureDefinition,
    type IPreviousPeriodMeasureDefinitionBody,
    type IPreviousPeriodDateDataSet,
    type MeasurePredicate,
    type MeasureOrLocalId,
    isMeasure,
    isSimpleMeasure,
    isInlineMeasure,
    isAdhocMeasure,
    isPoPMeasure,
    isPreviousPeriodMeasure,
    isArithmeticMeasure,
    isVirtualArithmeticMeasure,
    isMeasureDefinition,
    isPoPMeasureDefinition,
    isPreviousPeriodMeasureDefinition,
    isArithmeticMeasureDefinition,
    isVirtualArithmeticMeasureDefinition,
    isInlineMeasureDefinition,
    measureLocalId,
    anyMeasure,
    idMatchMeasure,
    measureDoesComputeRatio,
    measureItem,
    measureUri,
    measureIdentifier,
    measureMasterIdentifier,
    measureArithmeticOperands,
    measureAlias,
    measureTitle,
    measureArithmeticOperator,
    measureFormat,
    isMeasureFormatInPercent,
    measureAggregation,
    measureFilters,
    measurePopAttribute,
    measurePreviousPeriodDateDataSets,
} from "./execution/measure/index.js";

export {
    type IPreviousPeriodDateDataSetSimple,
    type MeasureModifications,
    type MeasureEnvelope,
    type InlineMeasureBuilderInput,
    type ArithmeticMeasureBuilderInput,
    type PoPMeasureBuilderInput,
    type PreviousPeriodMeasureBuilderInput,
    ArithmeticMeasureBuilder,
    VirtualArithmeticMeasureBuilder,
    MeasureBuilder,
    PoPMeasureBuilder,
    PreviousPeriodMeasureBuilder,
    InlineMeasureBuilder,
    MeasureBuilderBase,
    newMeasure,
    modifyMeasure,
    modifySimpleMeasure,
    modifyPopMeasure,
    modifyPreviousPeriodMeasure,
    modifyInlineMeasure,
    newArithmeticMeasure,
    newVirtualArithmeticMeasure,
    newPopMeasure,
    newPreviousPeriodMeasure,
    newInlineMeasure,
} from "./execution/measure/factory.js";

export {
    type IAttributeOrMeasure,
    type IBucket,
    type MeasureInBucket,
    type AttributeInBucket,
    type BucketPredicate,
    type BucketItemModifications,
    type BucketItemReducer,
    isBucket,
    idMatchBucket,
    anyBucket,
    newBucket,
    bucketIsEmpty,
    bucketAttributes,
    bucketAttribute,
    bucketAttributeIndex,
    bucketMeasure,
    bucketMeasureIndex,
    bucketMeasures,
    bucketTotals,
    bucketSetTotals,
    bucketItems,
    applyRatioRule,
    ComputeRatioRule,
    disableComputeRatio,
    bucketModifyItems,
    bucketItemReduce,
} from "./execution/buckets/index.js";

export {
    bucketsFind,
    bucketsMeasures,
    bucketsIsEmpty,
    bucketsAttributes,
    bucketsFindMeasure,
    bucketsById,
    bucketsFindAttribute,
    bucketsItems,
    bucketsTotals,
    bucketsModifyItem,
    bucketsReduceItem,
} from "./execution/buckets/bucketArray.js";

export { bucketItemLocalId } from "./execution/buckets/bucketItem.js";

export {
    type IExecutionDefinition,
    type IExecutionConfig,
    type IMeasureDefinitionOverride,
    type DimensionGenerator,
    type IPostProcessing,
    defWithFilters,
    defFingerprint,
    defSetDimensions,
    defSetSorts,
    defSetBuckets,
    defTotals,
    defSetExecConfig,
    defSetPostProcessing,
} from "./execution/executionDefinition/index.js";

export {
    newDefForItems,
    newDefForBuckets,
    newDefForInsight,
    defWithDimensions,
    defWithSorting,
    defWithPostProcessing,
    defWithBuckets,
    defWithDateFormat,
    defWithExecConfig,
    defaultDimensionsGenerator,
    emptyDef,
} from "./execution/executionDefinition/factory.js";

export {
    type GuidType,
    type RgbType,
    type IRgbColorValue,
    type IColor,
    type IColorPalette,
    type IColorPaletteItem,
    type IColorFromPalette,
    type IRgbColor,
    type IColorPaletteMetadataObject,
    type IColorPaletteDefinition,
    isColorFromPalette,
    isRgbColor,
    isColorPaletteItem,
    colorPaletteItemToRgb,
    colorPaletteToColors,
} from "./colors/index.js";

export {
    type IInsight,
    type IInsightDefinition,
    type IVisualizationClass,
    type IVisualizationClassBody,
    type VisualizationProperties,
    type IAttributeFilterConfigs,
    type IAttributeFilterConfig,
    type IColorMappingItem,
    type InsightDisplayFormUsage,
    type IInsightLayerDefinition,
    isInsight,
    isColorMappingItem,
    insightRef,
    insightId,
    insightItems,
    insightMeasures,
    insightHasMeasures,
    insightAttributes,
    insightHasAttributes,
    insightHasDataDefined,
    insightProperties,
    insightBuckets,
    insightSorts,
    insightBucket,
    insightTags,
    insightSummary,
    insightTitle,
    insightUri,
    insightIsLocked,
    insightCreated,
    insightCreatedBy,
    insightUpdated,
    insightUpdatedBy,
    insightTotals,
    insightFilters,
    insightAttributeFilterConfigs,
    insightVisualizationUrl,
    insightVisualizationType,
    insightSetFilters,
    insightSetBuckets,
    insightSetProperties,
    insightSetSorts,
    insightModifyItems,
    insightReduceItems,
    insightDisplayFormUsage,
    insightLayers,
    insightSetLayers,
    visClassUrl,
    visClassId,
    visClassUri,
    isInsightLayerDefinition,
} from "./insight/index.js";

export {
    insightCreatedComparator,
    insightCreatedByComparator,
    insightTitleComparator,
    insightUpdatedComparator,
    insightUpdatedByComparator,
} from "./insight/comparators.js";

export {
    type InsightModifications,
    newInsightDefinition,
    InsightDefinitionBuilder,
} from "./insight/factory.js";

export { insightSanitize, sanitizeBucketTotals } from "./insight/sanitization.js";

export { factoryNotationFor } from "./execution/objectFactoryNotation/index.js";

export {
    type DateFilterOptionAbsoluteFormType,
    type DateFilterOptionAbsolutePresetType,
    type DateFilterOptionAllTimeType,
    type DateFilterOptionType,
    type DateFilterOptionEmptyValuesType,
    type DateFilterOptionRelativeFormType,
    type DateFilterOptionRelativePresetType,
    type RelativeDateFilterGranularityOffset,
    type DateFilterGranularity,
    type DateString,
    type IAbsoluteDateFilterForm,
    type IAbsoluteDateFilterPreset,
    type IAllTimeDateFilterOption,
    type IDateFilterConfig,
    type IDateFilterOption,
    type IEmptyValuesDateFilterOption,
    type IRelativeDateFilterForm,
    type IRelativeDateFilterPreset,
    type IRelativeDateFilterPresetOfGranularity,
    isAbsoluteDateFilterForm,
    isAbsoluteDateFilterPreset,
    isAllTimeDateFilterOption,
    isEmptyValuesDateFilterOption,
    isDateFilterGranularity,
    isRelativeDateFilterForm,
    isRelativeDateFilterPreset,
} from "./dateFilterConfig/index.js";

export type { IDashboardObjectIdentity } from "./dashboard/common.js";

export {
    type DateFilterAbsoluteType,
    type DateFilterRelativeType,
    type DateFilterType,
    type FilterContextItem,
    type IDashboardAttributeFilter,
    type DashboardAttributeFilterSelectionMode,
    type IDashboardAttributeFilterParent,
    type IDashboardAttributeFilterReference,
    type IDashboardAttributeFilterByDate,
    type IDashboardDateFilter,
    type IDashboardDateFilterReference,
    type IDashboardFilterReference,
    type IFilterContext,
    type IFilterContextBase,
    type IFilterContextDefinition,
    type ITempFilterContext,
    type IDashboardFilterView,
    type IDashboardFilterViewSaveRequest,
    dashboardFilterReferenceObjRef,
    isAllTimeDashboardDateFilter,
    isAllTimeDashboardDateFilterWithEmptyValueHandling,
    isNoopAllTimeDashboardDateFilter,
    isAllValuesDashboardAttributeFilter,
    isDashboardAttributeFilter,
    isSingleSelectionFilter,
    isNegativeAttributeFilter as isNegativeDashboardAttributeFilter,
    getSelectedElementsCount,
    isDashboardAttributeFilterReference,
    isDashboardDateFilter,
    isDashboardDateFilterWithDimension,
    isDashboardCommonDateFilter,
    isRelativeDashboardDateFilter,
    isAbsoluteDashboardDateFilter,
    isDashboardDateFilterReference,
    isFilterContext,
    isFilterContextDefinition,
    isTempFilterContext,
    newAbsoluteDashboardDateFilter,
    newAllTimeDashboardDateFilter,
    newRelativeDashboardDateFilter,
    isFilterContextItem,
    dashboardFilterLocalIdentifier,
    dashboardFilterObjRef,
} from "./dashboard/filterContext.js";

export {
    type IWidgetAlert,
    type IWidgetAlertBase,
    type IWidgetAlertDefinition,
    isWidgetAlert,
    isWidgetAlertDefinition,
} from "./dashboard/alert.js";

export {
    type DrillDefinition,
    type DrillOrigin,
    type DrillOriginType,
    type DrillTransition,
    type DrillType,
    type IDrill,
    type IDrillDownReference,
    type IDateHierarchyReference,
    type IAttributeHierarchyReference,
    type IDrillFromAttribute,
    type IDrillFromMeasure,
    type IDrillOrigin,
    type IDrillTarget,
    type IDrillToAttributeUrl,
    type IDrillToAttributeUrlTarget,
    type IDrillToCustomUrl,
    type IDrillToCustomUrlTarget,
    type IDrillToDashboard,
    type IDrillToInsight,
    type IDrillToLegacyDashboard,
    type InsightDrillDefinition,
    type KpiDrillDefinition,
    type ICrossFiltering,
    type IKeyDriveAnalysis,
    isDrillFromAttribute,
    isDrillFromMeasure,
    isDrillToAttributeUrl,
    isDrillToCustomUrl,
    isDrillToDashboard,
    isDrillToInsight,
    isDrillToLegacyDashboard,
    isAttributeHierarchyReference,
    isDateHierarchyReference,
    isCrossFiltering,
    isKeyDriveAnalysis,
    drillDownReferenceHierarchyRef,
    drillDownReferenceAttributeRef,
} from "./dashboard/drill.js";

export {
    type IBaseWidget,
    type IDrillableWidget,
    type IFilterableWidget,
    type IWidgetDescription,
    type IDrillDownIntersectionIgnoredAttributes,
    BuiltInWidgetTypes,
} from "./dashboard/baseWidget.js";

export {
    type IKpi,
    type IKpiBase,
    type IKpiComparisonDirection,
    type IKpiComparisonTypeComparison,
    type IKpiWithPopComparison,
    type IKpiWithPreviousPeriodComparison,
    type IKpiWithComparison,
    type IKpiWithoutComparison,
    isKpiWithComparison,
    isKpiWithoutComparison,
    isKpi,
} from "./dashboard/kpi.js";

export type {
    AnalyticalWidgetType,
    IAnalyticalWidget,
    IKpiWidget,
    IKpiWidgetBase,
    IKpiWidgetDefinition,
    IKpiWidgetConfiguration,
    IKpiWidgetDescriptionConfiguration,
    KpiWidgetDescriptionSourceType,
    IInsightWidget,
    IInsightWidgetBase,
    IInsightWidgetDefinition,
    IInsightWidgetConfiguration,
    IInsightWidgetDescriptionConfiguration,
    InsightWidgetDescriptionSourceType,
    IRichTextWidget,
    IRichTextWidgetBase,
    IRichTextWidgetDefinition,
    IVisualizationSwitcherWidget,
    IVisualizationSwitcherWidgetBase,
    IVisualizationSwitcherWidgetDefinition,
} from "./dashboard/analyticalWidgets.js";

export {
    type ICatalogAttributeHierarchy,
    type ICatalogDateAttributeHierarchy,
    isCatalogAttributeHierarchy,
    isCatalogDateAttributeHierarchy,
    getHierarchyRef,
    getHierarchyTitle,
    getHierarchyAttributes,
} from "./ldm/catalog/attributeHierarchy/index.js";

export {
    type ICatalogDateDataset,
    type ICatalogDateAttribute,
    isCatalogDateDataset,
    isCatalogDateAttribute,
} from "./ldm/catalog/dateDataset/index.js";

export type { CatalogItemType, ICatalogItemBase } from "./ldm/catalog/types.js";

export type { ICatalogGroup, IGroupableCatalogItemBase } from "./ldm/catalog/group/index.js";

export { type ICatalogAttribute, isCatalogAttribute } from "./ldm/catalog/attribute/index.js";

export { type ICatalogFact, isCatalogFact } from "./ldm/catalog/fact/index.js";

export { type ICatalogMeasure, isCatalogMeasure } from "./ldm/catalog/measure/index.js";

export {
    type CatalogItem,
    type GroupableCatalogItem,
    catalogItemMetadataObject,
} from "./ldm/catalog/index.js";

export { type IAttributeMetadataObject, isAttributeMetadataObject } from "./ldm/metadata/attribute/index.js";
export {
    type AttributeDisplayFormType,
    type GeoCollectionKind,
    type IAttributeDisplayFormGeoAreaConfig,
    type IAttributeDisplayFormMetadataObject,
    attributeDisplayFormMetadataObjectAttributeRef,
    attributeDisplayFormMetadataObjectRef,
    attributeDisplayFormMetadataObjectTitle,
    isAttributeDisplayFormMetadataObject,
} from "./ldm/metadata/attributeDisplayForm/index.js";
export {
    type IAttributeHierarchyMetadataObject,
    type IDateHierarchyTemplate,
    isAttributeHierarchyMetadataObject,
} from "./ldm/metadata/attributeHierarchy/index.js";
export { type IDashboardMetadataObject, isDashboardMetadataObject } from "./ldm/metadata/dashboard/index.js";
export {
    type IDataSetAttributeMetadataObject,
    type IDataSetMetadataObject,
    isDataSetMetadataObject,
} from "./ldm/metadata/dataSet/index.js";
export { type IFactMetadataObject, isFactMetadataObject } from "./ldm/metadata/fact/index.js";
export {
    type IMeasureMetadataObject,
    type IMeasureMetadataObjectBase,
    type IMeasureMetadataObjectDefinition,
    type MetricType,
    isMeasureMetadataObject,
    isMeasureMetadataObjectDefinition,
} from "./ldm/metadata/measure/index.js";
export {
    type IMemoryItemDefinition,
    type IMemoryItemMetadataObject,
    type MemoryItemStrategy,
} from "./ldm/metadata/memoryItem/index.js";
export {
    type IMetadataObject,
    type IMetadataObjectBase,
    type IMetadataObjectDefinition,
    type IMetadataObjectIdentity,
    isMetadataObject,
} from "./ldm/metadata/types.js";
export {
    type IMdObjectBase,
    type IMdObjectIdentity,
    type IMdObject,
    type IMdObjectDefinition,
    type ToMdObjectDefinition,
    isMdObject,
    isMdObjectDefinition,
} from "./ldm/metadata/next.js";
export { type IVariableMetadataObject, isVariableMetadataObject } from "./ldm/metadata/variable/index.js";

export { type MetadataObject, metadataObjectId } from "./ldm/metadata/index.js";

export type {
    DataColumnType,
    DatasetLoadStatus,
    IDataColumnBody,
    IDataColumn,
    IDataHeader,
    IDatasetLoadInfo,
    IDatasetUser,
    IDataset,
    IDatasetBody,
} from "./ldm/datasets/index.js";

export type { IAttributeElement } from "./ldm/attributeElement.js";

export {
    type IWidget,
    type IWidgetDefinition,
    isWidget,
    isWidgetDefinition,
    widgetUri,
    widgetId,
    widgetRef,
    widgetTitle,
    widgetType,
    isKpiWidgetDefinition,
    isKpiWidget,
    isInsightWidgetDefinition,
    isInsightWidget,
    isRichTextWidget,
    isRichTextWidgetDefinition,
    isVisualizationSwitcherWidget,
    isVisualizationSwitcherWidgetDefinition,
} from "./dashboard/widget.js";

export {
    type IDashboardAttachment,
    type IWidgetAttachment,
    type IExportOptions,
    type IScheduledMail,
    type IScheduledMailDefinition,
    type ScheduledMailAttachment,
    type IScheduledMailBase,
    isDashboardAttachment,
    isWidgetAttachment,
} from "./dashboard/scheduledMail.js";

export {
    type IUser,
    type IUserGroup,
    type IWorkspaceUser,
    type IOrganizationUser,
    type IOrganizationUserGroup,
    userFullName,
    isIOrganizationUser,
    isIOrganizationUserGroup,
} from "./user/index.js";

export {
    type IDashboardLayout,
    type IDashboardWidget,
    type IDashboardLayoutSection,
    type IDashboardLayoutSectionHeader,
    type IDashboardLayoutSize,
    type IDashboardLayoutSizeByScreenSize,
    type IDashboardLayoutItem,
    type IDashboardLayoutWidget,
    type IDashboardLayoutConfiguration,
    type IDashboardLayoutSectionsConfiguration,
    type IDashboardLayoutContainerDirection,
    type ScreenSize,
    isDashboardLayout,
    isDashboardLayoutSection,
    isDashboardLayoutItem,
    isDashboardWidget,
} from "./dashboard/layout.js";

export {
    type IDashboard,
    type IDashboardDefinition,
    type IListedDashboard,
    type ListedDashboardAvailability,
    type IDashboardBase,
    type IDashboardDateFilterConfig,
    type DashboardDateFilterConfigMode,
    type IDashboardAttributeFilterConfig,
    type IDashboardDateFilterConfigItem,
    type DashboardAttributeFilterConfigMode,
    type IDashboardDateFilterAddedPresets,
    type IDashboardPluginBase,
    type IDashboardPlugin,
    type IDashboardPluginDefinition,
    type IDashboardPluginLink,
    type IAccessControlAware,
    type ShareStatus,
    type SharePermission,
    type IDashboardPermissions,
    type IExistingDashboard,
    type IDashboardTab,
    type IDashboardFilterGroup,
    type IDashboardFilterGroupItem,
    type IDashboardFilterGroupsConfig,
    DashboardDateFilterConfigModeValues,
    DashboardAttributeFilterConfigModeValues,
    isDashboard,
    isDashboardDefinition,
    isListedDashboard,
    isDashboardTab,
} from "./dashboard/dashboard.js";

export {
    type ISeparators,
    type ISettings,
    type PlatformEdition,
    type IWhiteLabeling,
    type IAlertDefault,
    type WeekStart,
    type IFiscalYear,
    type IActiveCalendars,
    type CalendarType,
    type IOpenAiConfig,
    type ILlmEndpoint,
    type DashboardFiltersApplyMode,
    type EarlyAccessFeatureContext,
    type EarlyAccessFeatureStatus,
    type IEarlyAccessFeatureConfig,
    type IEarlyAccessFeaturesConfig,
    type IProductionFeatureConfig,
    type IProductionFeaturesConfig,
    type IMetricFormatOverrideSetting,
    isSeparators,
} from "./settings/index.js";

export type { IWorkspaceUserGroup } from "./userGroup/index.js";

export type {
    ThemeFontUri,
    ThemeColor,
    IThemeColorFamily,
    IThemeComplementaryPalette,
    IThemeWidgetTitle,
    IThemeTypography,
    IThemeFontsDef,
    IThemePalette,
    IThemeKpi,
    IThemeKpiValue,
    IThemeChart,
    IThemeTable,
    ITheme,
    IThemeAnalyticalDesigner,
    IThemeAnalyticalDesignerTitle,
    IThemeButton,
    IThemeDashboard,
    IThemeDashboardContent,
    IThemeDashboardContentKpi,
    IThemeDashboardContentWidget,
    IThemeDashboardEditPanel,
    IThemeDashboardFilterBar,
    IThemeDashboardFilterBarButton,
    IThemeDashboardNavigation,
    IThemeDashboardNavigationItem,
    IThemeDashboardNavigationTitle,
    IThemeDashboardSection,
    IThemeDashboardSectionDescription,
    IThemeDashboardSectionTitle,
    IThemeDashboardTitle,
    IThemeMetadataObject,
    IThemeDefinition,
    IThemeModal,
    IThemeModalTitle,
    IThemeTooltip,
    IThemeImages,
    IThemeMessage,
    IThemeMessageVariant,
    IThemeToastMessage,
    IThemeToastMessageVariant,
    ImageUri,
    IThemeAxis,
    IThemeChartTooltip,
    IThemeDataLabel,
} from "./theme/index.js";

export type { IWorkspacePermissions, WorkspacePermission } from "./permissions/index.js";

export {
    type DataValue,
    type ForecastDataValue,
    type IGeoJsonFeature,
    type IMeasureDescriptor,
    type IMeasureDescriptorObject,
    type IMeasureDescriptorItem,
    type IDimensionItemDescriptor,
    type IDimensionDescriptor,
    type IAttributeHeaderFormOf,
    type IAttributeDescriptorBody,
    type IAttributeDescriptor,
    type IMeasureGroupDescriptor,
    type IResultAttributeHeader,
    type IResultHeader,
    type IResultMeasureHeader,
    type IResultAttributeHeaderItem,
    type IResultMeasureHeaderItem,
    type IResultTotalHeader,
    type IResultTotalHeaderItem,
    type ITotalDescriptor,
    type ITotalDescriptorItem,
    type IResultWarning,
    type IColorDescriptor,
    type IColorDescriptorItem,
    isColorDescriptor,
    isAttributeDescriptor,
    isMeasureGroupDescriptor,
    isTotalDescriptor,
    isMeasureDescriptor,
    isResultAttributeHeader,
    isResultMeasureHeader,
    isResultTotalHeader,
    resultHeaderName,
    attributeDescriptorLocalId,
    attributeDescriptorName,
    geoFeatureId,
} from "./execution/results/index.js";

export {
    type AccessGranteeDetail,
    type IAccessGrantee,
    type IUserAccess,
    type IUserAccessGrantee,
    type IUserGroupAccess,
    type IUserGroupAccessGrantee,
    type IGranularAccessGrantee,
    type AccessGranularPermission,
    type IGranteeGranularity,
    type IAvailableAccessGrantee,
    type IAvailableUserAccessGrantee,
    type IAvailableUserGroupAccessGrantee,
    type IGranularUserAccess,
    type IGranularUserGroupAccess,
    type IGranularRulesAccess,
    type IGranularUserAccessGrantee,
    type IGranularUserGroupAccessGrantee,
    type IGranularRulesAccessGrantee,
    type WorkspaceAccessPermission,
    type IWorkspaceAccess,
    type IUserWorkspaceAccessGrantee,
    type IUserGroupWorkspaceAccessGrantee,
    isUserAccess,
    isUserAccessGrantee,
    isUserGroupAccess,
    isUserGroupAccessGrantee,
    isGranularAccess,
    isAvailableUserGroupAccessGrantee,
    isAvailableUserAccessGrantee,
    isGranularAccessGrantee,
    isGranularUserAccessGrantee,
    isGranularUserGroupAccessGrantee,
    isGranularUserAccess,
    isGranularUserGroupAccess,
    isGranularRulesAccessGrantee,
    isUserWorkspaceAccessGrantee,
    isUserGroupWorkspaceAccessGrantee,
} from "./accessControl/index.js";

export {
    type IOrganizationDescriptor,
    type IOrganizationDescriptorUpdate,
    type IWorkspacePermissionAssignment,
    type IAssignedWorkspace,
    type AssignedWorkspacePermission,
    type IOrganizationPermissionAssignment,
    type OrganizationPermissionAssignment,
    type IOrganizationAssignee,
    type AssignedDataSourcePermission,
    type IAssignedDataSource,
    type IDataSourcePermissionAssignment,
    AssignedWorkspacePermissionValue,
    OrganizationPermissionAssignmentValue,
    AssignedDataSourcePermissionValue,
    isAssignedWorkspacePermission,
} from "./organization/index.js";
export type { IEntitlementsName, IEntitlementDescriptor } from "./entitlements/index.js";
export type { DataSourceType, IDataSourceIdentifierDescriptor } from "./dataSources/index.js";

export {
    type IExportDefinitionMetadataObject,
    type IExportDefinitionBase,
    type IExportDefinitionDashboardSettings,
    type IExportDefinitionDashboardRequestPayload,
    type IExportDefinitionVisualizationObjectSettings,
    type IExportDefinitionVisualizationObjectRequestPayload,
    type IExportDefinitionRequestPayload,
    type IExportDefinitionDashboardContent,
    type IExportDefinitionVisualizationObjectContent,
    type IExportDefinitionMetadataObjectDefinition,
    type IExportResult,
    type IExportResultStatus,
    type DashboardAttachmentType,
    type WidgetAttachmentType,
    exportDefinitionTitle,
    exportDefinitionCreated,
    exportDefinitionUpdated,
    isExportDefinitionDashboardRequestPayload,
    isExportDefinitionVisualizationObjectRequestPayload,
} from "./exports/index.js";

export type {
    IWorkspaceDataFilter,
    IWorkspaceDataFilterDefinition,
    IWorkspaceDataFilterSetting,
} from "./dataFilter/index.js";
export {
    type IAutomationMetadataObjectBase,
    type IAutomationMetadataObject,
    type IAutomationMetadataObjectDefinition,
    type IAutomationSchedule,
    type IAutomationRecipient,
    type IAutomationRecipientBase,
    type IAutomationRecipientType,
    type IAutomationUserGroupRecipient,
    type IAutomationUserRecipient,
    type IAutomationLastRunStatus,
    type IAutomationState,
    type IAutomationExternalRecipient,
    type IAutomationUnknownRecipient,
    type IAutomationAlert,
    type IAutomationAlertCondition,
    type IAutomationAlertExecutionDefinition,
    type IAlertComparisonOperator,
    type IAlertTriggerMode,
    type IAlertTriggerInterval,
    type IAlertTriggerState,
    type IAutomationAlertTrigger,
    type IAutomationAlertComparisonCondition,
    type IAlertRelativeOperator,
    type IAlertRelativeArithmeticOperator,
    type IAutomationAlertRelativeCondition,
    type IAutomationDetails,
    type IAutomationVisibleFilter,
    type AutomationEvaluationMode,
    type IAlertAnomalyDetectionSensitivity,
    type IAlertAnomalyDetectionGranularity,
    type IAutomationAnomalyDetectionCondition,
    isAutomationMetadataObject,
    isAutomationMetadataObjectDefinition,
    isAutomationUserGroupRecipient,
    isAutomationUserRecipient,
    isAutomationExternalUserRecipient,
    isAutomationUnknownUserRecipient,
} from "./automations/index.js";

export {
    type IAllowedRelationshipType,
    type ISemanticSearchResult,
    type ISemanticSearchResultItem,
    type ISemanticSearchRelationship,
    isSemanticSearchResultItem,
    isSemanticSearchRelationship,
} from "./genAI/semanticSearch.js";

export type {
    IGenAIChatInteraction,
    IGenAIUserContext,
    IGenAIChatRouting,
    IGenAIChatReasoning,
    IGenAIChatReasoningStep,
    IGenAIChatReasoningThought,
    IGenAICreatedVisualizations,
    IGenAIFoundObjects,
    IGenAIVisualization,
    IGenAIVisualizationConfig,
    IGenAIForecastConfig,
    IGenAIVisualizationDimension,
    IGenAIVisualizationMetric,
    IGenAIActiveObject,
    IGenAISuggestion,
    IGenAIChangeAnalysisParams,
    GenAIChatRoutingUseCase,
    GenAIChatInteractionUserFeedback,
    GenAIChatInteractionUserVisualisation,
    GenAIChatRole,
    GenAIVisualizationType,
    GenAIMetricAggregation,
    GenAIMetricType,
    GenAIFilter,
    GenAIPositiveAttributeFilter,
    GenAINegativeAttributeFilter,
    GenAIAbsoluteDateFilter,
    GenAIRelativeDateFilter,
    GenAIDateGranularity,
    GenAIRankingFilter,
} from "./genAI/chat.js";

export type { GenAIObjectType } from "./genAI/common.js";

export type {
    ILlmEndpointBase,
    ILlmEndpointOpenAI,
    LlmEndpointOpenAIPatch,
    LlmEndpointTestResults,
} from "./llmEndpoints/index.js";

export {
    type ISemanticQualityReport,
    type ISemanticQualityIssue,
    type ISemanticQualityIssueObject,
    type ISemanticQualityIssueDetail,
    type ISemanticQualityIssuesCalculation,
    type SemanticQualityIssueAttributeName,
    type SemanticQualityIssueSeverity,
    type SemanticQualityIssueCode,
    type SemanticQualityIssuesCalculationStatus,
    SemanticQualityIssueCodeValues,
    SemanticQualityIssueSeverityOrder,
} from "./genAI/quality.js";
