name: "Detect zstd"
description: "Checks if zstd is installed and saves its directory to env"
runs:
  using: "composite"
  steps:
    - name: Check for zstd installation
      shell: bash
      run: |
        ZSTD_PATH=$(which zstd || true)
        if [ -z "$ZSTD_PATH" ]; then
          echo "zstd not found"
          echo "exists=false" >> $GITHUB_OUTPUT
        else
          echo "Found zstd at: $ZSTD_PATH"
          echo "ZSTD_DIR=$ZSTD_PATH" >> $GITHUB_ENV
        fi
