// (C) 2007-2018 GoodData Corporation
export const MEASURES = 'measures';
export const SECONDARY_MEASURES = 'secondary_measures';
export const TERTIARY_MEASURES = 'tertiary_measures';
export const ATTRIBUTE = 'attribute';
export const ATTRIBUTES = 'attributes';
export const VIEW = 'view';
export const STACK = 'stack';
export const TREND = 'trend';
export const SEGMENT = 'segment';
export const ROWS = 'rows';
export const COLUMNS = 'columns';
