export enum ErrorStates {
    OK = 'OK',
    BAD_REQUEST = 'BAD_REQUEST',
    DATA_TOO_LARGE_DISPLAY = 'DATA_TOO_LARGE_DISPLAY',
    DATA_TOO_LARGE_TO_COMPUTE = 'DATA_TOO_LARGE_TO_COMPUTE',
    NEGATIVE_VALUES = 'NEGATIVE_VALUES',
    NO_DATA = 'NO_DATA',
    UNKNOWN_ERROR = 'UNKNOWN_ERROR',
    NOT_FOUND = 'NOT_FOUND',
    PROMISE_CANCELLED = 'PROMISE_CANCELLED'
}

export enum ErrorCodes {
    HTTP_TOO_LARGE = 413,
    HTTP_BAD_REQUEST = 400,
    APP_NO_DATA = 1001
}

