// (C) 2024 GoodData Corporation
import { ThemeInconsistentCssVariable } from "../types.js";

export const inconsistentVariables: ThemeInconsistentCssVariable[] = [
    {
        type: "inconsistent",
        variableName: "--gd-chart-tooltipLabelColor-from-theme",
        inconsistentDefaults: ["var(--gd-palette-complementary-7, #6d7680)"],
    },
    {
        type: "inconsistent",
        variableName: "--gd-dashboards-content-backgroundColor-from-theme",
        inconsistentDefaults: ["var(--gd-palette-complementary-0-from-theme, rgba(255, 255, 255, 0.95))"],
    },
    {
        type: "inconsistent",
        variableName: "--gd-dashboards-content-kpiWidget-kpi-primaryMeasureColor-from-theme",
        inconsistentDefaults: [
            "var(--gd-palette-complementary-8, #464e56)",
            "var(--gd-palette-complementary-7, #6d7680)",
            "var(--gd-palette-complementary-9, #000)",
        ],
    },
    {
        type: "inconsistent",
        variableName: "--gd-dashboards-content-kpiWidget-kpi-secondaryInfoColor-from-theme",
        inconsistentDefaults: [
            "var(--gd-palette-complementary-3-from-theme, rgba(176, 190, 202, 0.5))",
            "var(--gd-palette-complementary-6-from-theme, inherit)",
        ],
    },
    {
        type: "inconsistent",
        variableName: "--gd-dashboards-navigation-backgroundColor-from-theme",
        inconsistentDefaults: ["var(--gd-palette-complementary-8-from-theme, #313441)"],
    },
    {
        type: "inconsistent",
        variableName: "--gd-dashboards-navigation-borderColor-from-theme",
        inconsistentDefaults: ["var(--gd-palette-complementary-3-from-theme, #6e7582)"],
    },
    {
        type: "inconsistent",
        variableName: "--gd-dashboards-title-borderColor-from-theme",
        inconsistentDefaults: ["var(--gd-palette-complementary-2, #ebeff4)"],
    },
    {
        type: "inconsistent",
        variableName: "--gd-kpi-secondaryInfoColor-from-theme",
        inconsistentDefaults: [
            "var(--gd-palette-complementary-6-from-theme, #b0beca)",
            "var(--gd-palette-complementary-6, #94a1ad)",
        ],
    },
    {
        type: "inconsistent",
        variableName: "--gd-palette-complementary-0-from-theme",
        inconsistentDefaults: [
            "#fcfcfd",
            "#f8fafb",
            "#f3f6f7",
            "#131c28",
            "rgba(255, 255, 255, 0.95)",
            "inherit",
            "var(--gd-palette-complementary-0-from-theme, #fcfcfd)",
            "rgba(252, 252, 253, 0.98)",
        ],
    },
    {
        type: "inconsistent",
        variableName: "--gd-palette-complementary-1-from-theme",
        inconsistentDefaults: [
            "rgba(109, 118, 128, 0.1)",
            "#fcfcfd",
            "#eff2f4",
            "#f5f7f9",
            "#2c343f",
            "#303442",
            "var(--gd-palette-primary-dimmed, #e8f7fc)",
            "rgba(176, 190, 202, 0.1)",
            "rgba(238, 238, 238, 0.5)",
            "rgba(176, 190, 202, 0.15)",
            "rgba(176, 190, 202, 0.3)",
            "rgba(176, 190, 202, 0.4)",
            "rgba(201, 213, 224, 0.05)",
            "#b0beca",
            "rgba(235, 239, 244, 0.5)",
            "inherit",
            "initial",
        ],
    },
    {
        type: "inconsistent",
        variableName: "--gd-palette-complementary-2-from-theme",
        inconsistentDefaults: [
            "#ecf0f5",
            "#dee6ef",
            "#eff1f3",
            "rgba(221, 228, 235, 0.2)",
            "rgba(176, 190, 202, 0.2)",
            "#eee",
            "#eceff3",
            "#e3e9f0",
            "var(--gd-palette-complementary-2, #ebeff4)",
            "#dee6ef 0%",
            "#ecf0f5 100%",
            "#dee6ef0",
        ],
    },
    {
        type: "inconsistent",
        variableName: "--gd-palette-complementary-3-from-theme",
        inconsistentDefaults: [
            "#c9d5e0",
            "rgba(204, 216, 226, 0.7)",
            "#d7dfe5",
            "rgba(204, 216, 226, 0.5)",
            "rgba(201, 213, 224, 0.7)",
            "rgba(176, 190, 202, 0.5)",
            "rgba(201, 213, 224, 0.5)",
            "rgba(176, 190, 202, 0.45)",
            "#ccd8e2",
            "var(--gd-palette-primary-dimmed-from-theme, rgba(142, 220, 244, 0.2))",
            "#848484",
            "#6e7582",
            "initial",
            "#ebebeb",
        ],
    },
    {
        type: "inconsistent",
        variableName: "--gd-palette-complementary-3-from-theme-from-theme",
        inconsistentDefaults: ["var(--gd-palette-primary-dimmed-from-theme, rgba(142, 220, 244, 0.2))"],
    },
    {
        type: "inconsistent",
        variableName: "--gd-palette-complementary-4-from-theme",
        inconsistentDefaults: [
            "rgba(31, 52, 73, 0.2)",
            "#c9d5e0",
            "rgba(148, 161, 173, 0.2)",
            "rgba(176, 190, 202, 0.5)",
            "rgba(177, 193, 209, 0.5)",
            "#e0e2e4",
            "#ccc",
            "#ccd6eb",
        ],
    },
    {
        type: "inconsistent",
        variableName: "--gd-palette-complementary-5-from-theme",
        inconsistentDefaults: [
            "#b1c1d1",
            "#94a1ad",
            "var(--gd-palette-complementary-4-from-theme, rgba(31, 52, 73, 0.2))",
            "transparent",
            "#b3b3b3",
            "rgba(201, 213, 224, 0.5)",
            "rgba(176, 190, 202, 0.85)",
            "#999",
            "#bbb",
            "inherit",
            "#ccd8e2",
        ],
    },
    {
        type: "inconsistent",
        variableName: "--gd-palette-complementary-6-from-theme",
        inconsistentDefaults: [
            "rgba(109, 118, 128, 0.75)",
            "#b0beca",
            "#bbb",
            "inherit",
            "var(--gd-palette-complementary-9, #000)",
            "rgba(255, 255, 255, 0.5)",
            "#909293",
            "#acaeae",
            "#808080",
            "#6d7680",
        ],
    },
    {
        type: "inconsistent",
        variableName: "--gd-palette-complementary-7-from-theme",
        inconsistentDefaults: [
            "#778491",
            "#687581",
            "var(--gd-palette-complementary-8, #464e56)",
            "#000",
            "#b4c0cf",
            "var(--gd-palette-complementary-5, #b0beca)",
            "inherit",
            "#454e56",
            "#ccd8e2",
            "#808080",
        ],
    },
    {
        type: "inconsistent",
        variableName: "--gd-palette-complementary-8-from-theme",
        inconsistentDefaults: [
            "rgba(70, 78, 86, 0.95)",
            "#000",
            "var(--gd-palette-complementary-9, #000)",
            "#94a1ad",
            "initial",
            "#687581",
            "#6d7680",
            "inherit",
            "#454e56",
            "#313441",
            "#333",
            "#464e56",
        ],
    },
    {
        type: "inconsistent",
        variableName: "--gd-palette-complementary-9-from-theme",
        inconsistentDefaults: ["#fff", "initial", "inherit", "#6d7680", "#464e56"],
    },
    {
        type: "inconsistent",
        variableName: "--gd-palette-primary-base-t10-from-theme",
        inconsistentDefaults: ["rgba(241, 134, 0, 0.9)"],
    },
    {
        type: "inconsistent",
        variableName: "--gd-palette-primary-dimmed-from-theme",
        inconsistentDefaults: ["rgba(142, 220, 244, 0.2)"],
    },
    {
        type: "inconsistent",
        variableName: "--gd-palette-primary-dimmed50-from-theme",
        inconsistentDefaults: ["#b9e8f6"],
    },
    {
        type: "inconsistent",
        variableName: "--gd-palette-warning-base-from-theme",
        inconsistentDefaults: ["#f18600"],
    },
    {
        type: "inconsistent",
        variableName: "--gd-shadow-color-from-theme",
        inconsistentDefaults: [
            "rgba(20, 56, 93, 0.15)",
            "rgba(20, 56, 93, 0.1)",
            "rgba(20, 56, 93, 0.2)",
            "rgba(177, 193, 209, 0.6)",
            "rgba(177, 193, 209, 0.65)",
            "rgba(20, 56, 93, 0.09)",
            "rgba(31, 53, 74, 0.15)",
            "rgba(20, 57, 93, 0.05)",
            "rgba(20, 57, 93, 0.1)",
            "rgba(31, 53, 74, 0.2)",
        ],
    },
    {
        type: "inconsistent",
        variableName: "--gd-table-subtotalBackgroundColor-from-theme",
        inconsistentDefaults: ["var(--gd-palette-complementary-1-from-theme, rgba(176, 190, 202, 0.15))"],
    },
    {
        type: "inconsistent",
        variableName: "--gd-table-totalBackgroundColor-from-theme",
        inconsistentDefaults: [
            "var(--gd-palette-complementary-1-from-theme, rgba(176, 190, 202, 0.3))",
            "var(--gd-palette-complementary-1-from-theme, rgba(176, 190, 202, 0.4))",
        ],
    },
    {
        // Generate primary base from theme -> see Header.tsx .gd-header-menu-item.active
        type: "inconsistent",
        variableName: "--gd-palette-primary-base-from-theme",
        // it's not in scss but js only, so we don't need to set defaults here
        inconsistentDefaults: [],
    },
];
