# (C) 2025 GoodData Corporation
FROM 020413372491.dkr.ecr.us-east-1.amazonaws.com/pullthrough/docker.io/gooddata/gooddata-neobackstop:0.21.2
COPY config.json /usr/neobackstop/config.json
COPY scenarios.json /usr/neobackstop/scenarios.json
