# (C) 2025 GoodData Corporation
FROM 020413372491.dkr.ecr.us-east-1.amazonaws.com/pullthrough/docker.io/gooddata/gooddata-neobackstop:0.21.2@sha256:09fc80097baa1218c54fc0e77b7aa9f1ebb7e2b6a38b1b794e9cdf1e80862259
COPY config.json /usr/neobackstop/config.json
COPY scenarios.json /usr/neobackstop/scenarios.json
