// (C) 2025-2026 GoodData Corporation

/* oxlint-disable no-barrel-files/no-barrel-files */

import type { AxiosInstance, AxiosPromise, AxiosRequestConfig } from "axios";

import {
    type ActionsApiAiChatHistoryRequest,
    type ActionsApiAiChatRequest,
    type ActionsApiAiChatStreamRequest,
    type ActionsApiAiSearchRequest,
    type ActionsApiCreatedByRequest,
    type ActionsApiGetQualityIssuesRequest,
    type ActionsApiListLlmProviderModelsByIdRequest,
    type ActionsApiListLlmProviderModelsRequest,
    type ActionsApiMemoryCreatedByUsersRequest,
    type ActionsApiTagsRequest,
    type ActionsApiTestLlmProviderByIdRequest,
    type ActionsApiTestLlmProviderRequest,
    type ActionsApiTriggerQualityIssuesCalculationRequest,
    type ActionsApiValidateLLMEndpointByIdRequest,
    type ActionsApiValidateLLMEndpointRequest,
    ActionsApi_AiChat,
    ActionsApi_AiChatHistory,
    ActionsApi_AiChatStream,
    ActionsApi_AiSearch,
    ActionsApi_CreatedBy,
    ActionsApi_GetQualityIssues,
    ActionsApi_GetQualityIssuesCalculationStatus,
    ActionsApi_ListLlmProviderModels,
    ActionsApi_ListLlmProviderModelsById,
    ActionsApi_MemoryCreatedByUsers,
    ActionsApi_Tags,
    ActionsApi_TestLlmProvider,
    ActionsApi_TestLlmProviderById,
    ActionsApi_TriggerQualityIssuesCalculation,
    ActionsApi_ValidateLLMEndpoint,
    ActionsApi_ValidateLLMEndpointById,
    type TrendingObjectsResult,
} from "../../generated/afm-rest-api/index.js";
import {
    type AiPatchDocumentRequest,
    type ConversationsAiDeleteConversationApiV1AiWorkspacesWorkspaceIdChatConversationsConversationIdDeleteRequest,
    type ConversationsAiGetConversationApiV1AiWorkspacesWorkspaceIdChatConversationsConversationIdGetRequest,
    type ConversationsAiGetConversationsApiV1AiWorkspacesWorkspaceIdChatConversationsGetRequest,
    type ConversationsAiPostConversationsApiV1AiWorkspacesWorkspaceIdChatConversationsPostRequest,
    ConversationsAi_DeleteConversationApiV1AiWorkspacesWorkspaceIdChatConversationsConversationIdDelete,
    ConversationsAi_GetConversationApiV1AiWorkspacesWorkspaceIdChatConversationsConversationIdGet,
    ConversationsAi_GetConversationsApiV1AiWorkspacesWorkspaceIdChatConversationsGet,
    ConversationsAi_PostConversationsApiV1AiWorkspacesWorkspaceIdChatConversationsPost,
    type ItemsAiGetConversationItemsApiV1AiWorkspacesWorkspaceIdChatConversationsConversationIdItemsGetRequest,
    ItemsAi_GetConversationItemsApiV1AiWorkspacesWorkspaceIdChatConversationsConversationIdItemsGet,
    type KnowledgeAiCreateDocumentRequest,
    type KnowledgeAiDeleteDocumentRequest,
    type KnowledgeAiGetDocumentRequest,
    type KnowledgeAiListDocumentsRequest,
    type KnowledgeAiPatchDocumentRequest,
    type KnowledgeAiSearchKnowledgeRequest,
    type KnowledgeAiUpsertDocumentRequest,
    KnowledgeAi_CreateDocument,
    KnowledgeAi_DeleteDocument,
    KnowledgeAi_GetDocument,
    KnowledgeAi_ListDocuments,
    KnowledgeAi_PatchDocument,
    KnowledgeAi_SearchKnowledge,
    KnowledgeAi_UpsertDocument,
    type MessagesAiPostMessagesApiV1AiWorkspacesWorkspaceIdChatConversationsConversationIdMessagesPostRequest,
    MessagesAi_PostMessagesApiV1AiWorkspacesWorkspaceIdChatConversationsConversationIdMessagesPost,
    type ResponsesAiGetConversationResponsesApiV1AiWorkspacesWorkspaceIdChatConversationsConversationIdResponsesGetRequest,
    type ResponsesAiPatchResponseApiV1AiWorkspacesWorkspaceIdChatConversationsConversationIdResponsesResponseIdPatchRequest,
    ResponsesAi_GetConversationResponsesApiV1AiWorkspacesWorkspaceIdChatConversationsConversationIdResponsesGet,
    ResponsesAi_PatchResponseApiV1AiWorkspacesWorkspaceIdChatConversationsConversationIdResponsesResponseIdPatch,
    type VisualizationsAiPatchVisualizationApiV1AiWorkspacesWorkspaceIdChatConversationsConversationIdVisualizationsVisualizationIdPatchRequest,
    VisualizationsAi_PatchVisualizationApiV1AiWorkspacesWorkspaceIdChatConversationsConversationIdVisualizationsVisualizationIdPatch,
} from "../../generated/ai-json-api/index.js";

// GenAI API - Export GenAI-related ActionsApi functions with GenAiApi_ prefix
export {
    ActionsApi_AiSearch as GenAiApi_AiSearch,
    type ActionsApiAiSearchRequest as GenAiApiAiSearchRequest,
    ActionsApi_AiChat as GenAiApi_AiChat,
    type ActionsApiAiChatRequest as GenAiApiAiChatRequest,
    ActionsApi_AiChatHistory as GenAiApi_AiChatHistory,
    type ActionsApiAiChatHistoryRequest as GenAiApiAiChatHistoryRequest,
    ActionsApi_AiChatStream as GenAiApi_AiChatStream,
    type ActionsApiAiChatStreamRequest as GenAiApiAiChatStreamRequest,
    ActionsApi_ValidateLLMEndpoint as GenAiApi_ValidateLLMEndpoint,
    type ActionsApiValidateLLMEndpointRequest as GenAiApiValidateLLMEndpointRequest,
    ActionsApi_ValidateLLMEndpointById as GenAiApi_ValidateLLMEndpointById,
    type ActionsApiValidateLLMEndpointByIdRequest as GenAiApiValidateLLMEndpointByIdRequest,
    ActionsApi_GetQualityIssues as GenAiApi_GetQualityIssues,
    type ActionsApiGetQualityIssuesRequest as GenAiApiGetQualityIssuesRequest,
    ActionsApi_GetQualityIssuesCalculationStatus as GenAiApi_GetQualityIssuesCalculationStatus,
    ActionsApi_TriggerQualityIssuesCalculation as GenAiApi_TriggerQualityIssuesCalculation,
    type ActionsApiTriggerQualityIssuesCalculationRequest as GenAiApiTriggerQualityIssuesCalculationRequest,
    ActionsApi_Tags as GenAiApi_Tags,
    type ActionsApiTagsRequest as GenAiApiTagsRequest,
    ActionsApi_CreatedBy as GenAiApi_CreatedBy,
    type ActionsApiCreatedByRequest as GenAiApiCreatedByRequest,
    ActionsApi_MemoryCreatedByUsers as GenAiApi_MemoryCreatedByUsers,
    type ActionsApiMemoryCreatedByUsersRequest as GenAiApiMemoryCreatedByUsersRequest,
    ActionsApi_TestLlmProvider as GenAiApi_TestLlmProvider,
    type ActionsApiTestLlmProviderRequest as GenAiApiTestLlmProviderRequest,
    ActionsApi_TestLlmProviderById as GenAiApi_TestLlmProviderById,
    type ActionsApiTestLlmProviderByIdRequest as GenAiApiTestLlmProviderByIdRequest,
    ActionsApi_ListLlmProviderModels,
    type ActionsApiListLlmProviderModelsRequest,
    ActionsApi_ListLlmProviderModelsById,
    type ActionsApiListLlmProviderModelsByIdRequest,
    ConversationsAi_DeleteConversationApiV1AiWorkspacesWorkspaceIdChatConversationsConversationIdDelete as GenAiApi_DeleteConversation,
    type ConversationsAiDeleteConversationApiV1AiWorkspacesWorkspaceIdChatConversationsConversationIdDeleteRequest as GenAiApiDeleteConversationRequest,
    ConversationsAi_GetConversationApiV1AiWorkspacesWorkspaceIdChatConversationsConversationIdGet as GenAiApi_GetConversation,
    type ConversationsAiGetConversationApiV1AiWorkspacesWorkspaceIdChatConversationsConversationIdGetRequest as GenAiApiGetConversationRequest,
    ConversationsAi_GetConversationsApiV1AiWorkspacesWorkspaceIdChatConversationsGet as GenAiApi_GetConversations,
    type ConversationsAiGetConversationsApiV1AiWorkspacesWorkspaceIdChatConversationsGetRequest as GenAiApiGetConversationsRequest,
    ConversationsAi_PostConversationsApiV1AiWorkspacesWorkspaceIdChatConversationsPost as GenAiApi_PostConversations,
    type ConversationsAiPostConversationsApiV1AiWorkspacesWorkspaceIdChatConversationsPostRequest as GenAiApiPostConversationsRequest,
    ItemsAi_GetConversationItemsApiV1AiWorkspacesWorkspaceIdChatConversationsConversationIdItemsGet as GenAiApi_GetConversationItems,
    type ItemsAiGetConversationItemsApiV1AiWorkspacesWorkspaceIdChatConversationsConversationIdItemsGetRequest as GenAiApiGetConversationItemsRequest,
    MessagesAi_PostMessagesApiV1AiWorkspacesWorkspaceIdChatConversationsConversationIdMessagesPost as GenAiApi_PostMessages,
    type MessagesAiPostMessagesApiV1AiWorkspacesWorkspaceIdChatConversationsConversationIdMessagesPostRequest as GenAiApiPostMessagesRequest,
    ResponsesAi_GetConversationResponsesApiV1AiWorkspacesWorkspaceIdChatConversationsConversationIdResponsesGet as GenAiApi_GetConversationResponses,
    type ResponsesAiGetConversationResponsesApiV1AiWorkspacesWorkspaceIdChatConversationsConversationIdResponsesGetRequest as GenAiApiGetConversationResponsesRequest,
    ResponsesAi_PatchResponseApiV1AiWorkspacesWorkspaceIdChatConversationsConversationIdResponsesResponseIdPatch as GenAiApi_PatchConversationResponse,
    type ResponsesAiPatchResponseApiV1AiWorkspacesWorkspaceIdChatConversationsConversationIdResponsesResponseIdPatchRequest as GenAiApiPatchConversationResponseRequest,
    VisualizationsAi_PatchVisualizationApiV1AiWorkspacesWorkspaceIdChatConversationsConversationIdVisualizationsVisualizationIdPatch as GenAiApi_PatchVisualization,
    type VisualizationsAiPatchVisualizationApiV1AiWorkspacesWorkspaceIdChatConversationsConversationIdVisualizationsVisualizationIdPatchRequest as GenAiApiPatchVisualizationRequest,
    // Knowledge Documents
    KnowledgeAi_CreateDocument as GenAiApi_CreateKnowledgeDocument,
    type KnowledgeAiCreateDocumentRequest as GenAiApiCreateKnowledgeDocumentRequest,
    KnowledgeAi_UpsertDocument as GenAiApi_UpsertKnowledgeDocument,
    type KnowledgeAiUpsertDocumentRequest as GenAiApiUpsertKnowledgeDocumentRequest,
    KnowledgeAi_ListDocuments as GenAiApi_ListKnowledgeDocuments,
    type KnowledgeAiListDocumentsRequest as GenAiApiListKnowledgeDocumentsRequest,
    KnowledgeAi_GetDocument as GenAiApi_GetKnowledgeDocument,
    type KnowledgeAiGetDocumentRequest as GenAiApiGetKnowledgeDocumentRequest,
    KnowledgeAi_DeleteDocument as GenAiApi_DeleteKnowledgeDocument,
    type KnowledgeAiDeleteDocumentRequest as GenAiApiDeleteKnowledgeDocumentRequest,
    KnowledgeAi_PatchDocument as GenAiApi_PatchKnowledgeDocument,
    type KnowledgeAiPatchDocumentRequest as GenAiApiPatchKnowledgeDocumentRequest,
    KnowledgeAi_SearchKnowledge as GenAiApi_SearchKnowledge,
    type KnowledgeAiSearchKnowledgeRequest as GenAiApiSearchKnowledgeRequest,
    type AiPatchDocumentRequest as GenAiApiPatchDocumentRequestBody,
};

export type GenAiApiTrendingObjectsRequest = {
    readonly workspaceId: string;
};

export async function GenAiApi_TrendingObjects(
    axios: AxiosInstance,
    basePath: string,
    requestParameters: GenAiApiTrendingObjectsRequest,
    options: AxiosRequestConfig = {},
): Promise<AxiosPromise<TrendingObjectsResult>> {
    const workspaceId = encodeURIComponent(String(requestParameters.workspaceId));
    const url = `${basePath}/api/v1/actions/workspaces/${workspaceId}/ai/analyticsCatalog/trendingObjects`;

    return axios.request<TrendingObjectsResult>({
        ...options,
        method: "GET",
        url,
    });
}
