// (C) 2021-2026 GoodData Corporation

import { type IDateFilterConfig, idRef } from "@gooddata/sdk-model";

/**
 * Default date filter preset for standard calendar.
 */
export const DEFAULT_DATE_FILTER_PRESET = "THIS_MONTH";

/**
 * Default date filter preset for fiscal calendar.
 * Used when fiscal calendar is set as the default calendar type.
 */
export const DEFAULT_FISCAL_DATE_FILTER_PRESET = "THIS_FISCAL_MONTH";

export const defaultDateFilterConfig: IDateFilterConfig = {
    ref: idRef("defaultDateFilterProjectConfig"),
    selectedOption: DEFAULT_DATE_FILTER_PRESET,
    allTime: {
        localIdentifier: "ALL_TIME",
        type: "allTime",
        name: "",
        visible: true,
    },
    absoluteForm: {
        localIdentifier: "ABSOLUTE_FORM",
        type: "absoluteForm",
        name: "",
        visible: true,
    },
    relativeForm: {
        type: "relativeForm",
        // month has to be the first as it should be the default selected option
        availableGranularities: [
            "GDC.time.month",
            "GDC.time.fiscal_month",
            "GDC.time.minute",
            "GDC.time.hour",
            "GDC.time.date",
            "GDC.time.week_us",
            "GDC.time.quarter",
            "GDC.time.fiscal_quarter",
            "GDC.time.year",
            "GDC.time.fiscal_year",
        ],
        localIdentifier: "RELATIVE_FORM",
        name: "",
        visible: true,
    },
    relativePresets: [
        {
            from: -14,
            to: 0,
            granularity: "GDC.time.minute",
            localIdentifier: "LAST_15_MINUTES",
            type: "relativePreset",
            visible: true,
            name: "",
        },
        {
            from: -29,
            to: 0,
            granularity: "GDC.time.minute",
            localIdentifier: "LAST_30_MINUTES",
            type: "relativePreset",
            visible: true,
            name: "",
        },
        {
            from: -44,
            to: 0,
            granularity: "GDC.time.minute",
            localIdentifier: "LAST_45_MINUTES",
            type: "relativePreset",
            visible: true,
            name: "",
        },
        {
            from: -59,
            to: 0,
            granularity: "GDC.time.minute",
            localIdentifier: "LAST_60_MINUTES",
            type: "relativePreset",
            visible: true,
            name: "",
        },
        {
            from: -1,
            to: -1,
            granularity: "GDC.time.hour",
            localIdentifier: "LAST_HOUR",
            type: "relativePreset",
            visible: true,
            name: "",
        },
        {
            from: -7,
            to: 0,
            granularity: "GDC.time.hour",
            localIdentifier: "LAST_8_HOURS",
            type: "relativePreset",
            visible: true,
            name: "",
        },
        {
            from: -11,
            to: 0,
            granularity: "GDC.time.hour",
            localIdentifier: "LAST_12_HOURS",
            type: "relativePreset",
            visible: true,
            name: "",
        },
        {
            from: -23,
            to: 0,
            granularity: "GDC.time.hour",
            localIdentifier: "LAST_24_HOURS",
            type: "relativePreset",
            visible: true,
            name: "",
        },
        {
            from: 0,
            to: 0,
            granularity: "GDC.time.week_us",
            localIdentifier: "THIS_WEEK",
            type: "relativePreset",
            visible: true,
            name: "",
        },
        {
            from: 0,
            to: 0,
            granularity: "GDC.time.week_us",
            localIdentifier: "THIS_WEEK_TO_DATE",
            type: "relativePreset",
            visible: true,
            name: "",
            boundedFilter: {
                granularity: "GDC.time.date",
                to: 0,
            },
        },
        {
            from: -1,
            to: -1,
            granularity: "GDC.time.week_us",
            localIdentifier: "LAST_WEEK",
            type: "relativePreset",
            visible: true,
            name: "",
        },
        {
            from: -1,
            to: 0,
            granularity: "GDC.time.week_us",
            localIdentifier: "LAST_2_WEEKS",
            type: "relativePreset",
            visible: true,
            name: "",
        },
        {
            from: 0,
            to: 0,
            granularity: "GDC.time.date",
            localIdentifier: "TODAY",
            type: "relativePreset",
            visible: true,
            name: "",
        },
        {
            from: -1,
            to: -1,
            granularity: "GDC.time.date",
            localIdentifier: "YESTERDAY",
            type: "relativePreset",
            visible: true,
            name: "",
        },
        {
            from: -6,
            to: 0,
            granularity: "GDC.time.date",
            localIdentifier: "LAST_7_DAYS",
            type: "relativePreset",
            visible: true,
            name: "",
        },
        {
            from: -29,
            to: 0,
            granularity: "GDC.time.date",
            localIdentifier: "LAST_30_DAYS",
            type: "relativePreset",
            visible: true,
            name: "",
        },
        {
            from: -89,
            to: 0,
            granularity: "GDC.time.date",
            localIdentifier: "LAST_90_DAYS",
            type: "relativePreset",
            visible: true,
            name: "",
        },
        {
            from: 0,
            to: 0,
            granularity: "GDC.time.month",
            localIdentifier: "THIS_MONTH_TO_DATE",
            type: "relativePreset",
            visible: true,
            name: "",
            boundedFilter: {
                granularity: "GDC.time.date",
                to: 0,
            },
        },
        {
            from: 0,
            to: 0,
            granularity: "GDC.time.month",
            localIdentifier: "THIS_MONTH",
            type: "relativePreset",
            visible: true,
            name: "",
        },
        {
            from: -1,
            to: -1,
            granularity: "GDC.time.month",
            localIdentifier: "LAST_MONTH",
            type: "relativePreset",
            visible: true,
            name: "",
        },
        {
            from: -11,
            to: 0,
            granularity: "GDC.time.month",
            localIdentifier: "LAST_12_MONTHS",
            type: "relativePreset",
            visible: true,
            name: "",
        },
        {
            from: 0,
            to: 0,
            granularity: "GDC.time.quarter",
            localIdentifier: "THIS_QUARTER_TO_DATE",
            type: "relativePreset",
            visible: true,
            name: "",
            boundedFilter: {
                granularity: "GDC.time.date",
                to: 0,
            },
        },
        {
            from: 0,
            to: 0,
            granularity: "GDC.time.quarter",
            localIdentifier: "THIS_QUARTER",
            type: "relativePreset",
            visible: true,
            name: "",
        },
        {
            from: -1,
            to: -1,
            granularity: "GDC.time.quarter",
            localIdentifier: "LAST_QUARTER",
            type: "relativePreset",
            visible: true,
            name: "",
        },
        {
            from: -3,
            to: 0,
            granularity: "GDC.time.quarter",
            localIdentifier: "LAST_4_QUARTERS",
            type: "relativePreset",
            visible: true,
            name: "",
        },
        {
            from: 0,
            to: 0,
            granularity: "GDC.time.year",
            localIdentifier: "THIS_YEAR_TO_DATE",
            type: "relativePreset",
            visible: true,
            name: "",
            boundedFilter: {
                granularity: "GDC.time.date",
                to: 0,
            },
        },
        {
            from: 0,
            to: 0,
            granularity: "GDC.time.year",
            localIdentifier: "THIS_YEAR",
            type: "relativePreset",
            visible: true,
            name: "",
        },
        {
            from: -1,
            to: -1,
            granularity: "GDC.time.year",
            localIdentifier: "LAST_YEAR",
            type: "relativePreset",
            visible: true,
            name: "",
        },
        // Fiscal Year presets
        {
            from: 0,
            to: 0,
            granularity: "GDC.time.fiscal_year",
            localIdentifier: "THIS_FISCAL_YEAR_TO_DATE",
            type: "relativePreset",
            visible: true,
            name: "",
            boundedFilter: {
                granularity: "GDC.time.date",
                to: 0,
            },
        },
        {
            from: 0,
            to: 0,
            granularity: "GDC.time.fiscal_year",
            localIdentifier: "THIS_FISCAL_YEAR",
            type: "relativePreset",
            visible: true,
            name: "",
        },
        {
            from: -1,
            to: -1,
            granularity: "GDC.time.fiscal_year",
            localIdentifier: "LAST_FISCAL_YEAR",
            type: "relativePreset",
            visible: true,
            name: "",
        },
        // Fiscal Quarter presets
        {
            from: 0,
            to: 0,
            granularity: "GDC.time.fiscal_quarter",
            localIdentifier: "THIS_FISCAL_QUARTER_TO_DATE",
            type: "relativePreset",
            visible: true,
            name: "",
            boundedFilter: {
                granularity: "GDC.time.date",
                to: 0,
            },
        },
        {
            from: 0,
            to: 0,
            granularity: "GDC.time.fiscal_quarter",
            localIdentifier: "THIS_FISCAL_QUARTER",
            type: "relativePreset",
            visible: true,
            name: "",
        },
        {
            from: -1,
            to: -1,
            granularity: "GDC.time.fiscal_quarter",
            localIdentifier: "LAST_FISCAL_QUARTER",
            type: "relativePreset",
            visible: true,
            name: "",
        },
        {
            from: -3,
            to: 0,
            granularity: "GDC.time.fiscal_quarter",
            localIdentifier: "LAST_4_FISCAL_QUARTERS",
            type: "relativePreset",
            visible: true,
            name: "",
        },
        // Fiscal Month (Period) presets
        {
            from: 0,
            to: 0,
            granularity: "GDC.time.fiscal_month",
            localIdentifier: "THIS_FISCAL_MONTH_TO_DATE",
            type: "relativePreset",
            visible: true,
            name: "",
            boundedFilter: {
                granularity: "GDC.time.date",
                to: 0,
            },
        },
        {
            from: 0,
            to: 0,
            granularity: "GDC.time.fiscal_month",
            localIdentifier: "THIS_FISCAL_MONTH",
            type: "relativePreset",
            visible: true,
            name: "",
        },
        {
            from: -1,
            to: -1,
            granularity: "GDC.time.fiscal_month",
            localIdentifier: "LAST_FISCAL_MONTH",
            type: "relativePreset",
            visible: true,
            name: "",
        },
        {
            from: -11,
            to: 0,
            granularity: "GDC.time.fiscal_month",
            localIdentifier: "LAST_12_FISCAL_MONTHS",
            type: "relativePreset",
            visible: true,
            name: "",
        },
    ],
    absolutePresets: [],
};
