// (C) 2020 GoodData Corporation

/*
 * In some cases, it is still valid to reference data elements by their URI - because URI is
 * essentially the primary key to identify particular entity (yes, bear's URI have some drawbacks).
 *
 * This is essential when sorting pivot table or doing color mapping for charts.
 *
 * NOTE: these values figure in test scenario insight converters; if you change this it
 *  is essential to run 'populate-ref' script to make sure insights created in the
 *  reference workspace are up-to-date.
 *
 * TODO Ideally, a map like this should instead be included in recording index and be auto-generated by the
 *  mock tooling and be part of the reference workspace; good starting task for someone interested in typescript
 *  code-gen done in mock-handling tool.
 */

export const Region = {
    EastCoast: "/gdc/md/l32xdyl4bjuzgf9kkqr2avl55gtuyjwf/obj/1086/elements?id=460488",
    WestCoast: "/gdc/md/l32xdyl4bjuzgf9kkqr2avl55gtuyjwf/obj/1086/elements?id=460489",
};

export const Product = {
    Explorer: "/gdc/md/l32xdyl4bjuzgf9kkqr2avl55gtuyjwf/obj/1054/elements?id=342345",
    WonderKid: "/gdc/md/l32xdyl4bjuzgf9kkqr2avl55gtuyjwf/obj/1054/elements?id=166497",
};
