name: Set up rush with cache
description: This action sets up rush with cache

runs:
  using: 'composite'
  steps:
    # init node and warmup node cache installation
    - name: Warmup cache Node.js
      uses: ./.github/actions/node/warm-up-node
      id: node-cache

    # Set up caching for global rush installation
    - name: Cache Rush
      uses: runs-on/cache@v4
      env:
        RUNS_ON_S3_BUCKET_CACHE: gdc-github-cache
      with:
        path: |
          common/temp/install-run
          ~/.rush
        key: Rush-cache-${{ hashFiles('rush.json') }}

    # Perform a lookup to check if the cache for pnpm exists
    - name: Cache pnpm lookup
      id: cache-pnpm-lookup
      uses: runs-on/cache@v4
      env:
        RUNS_ON_S3_BUCKET_CACHE: gdc-github-cache
      with:
        lookup-only: true
        path: |
          common/temp/pnpm-store
        key: pnpm-cache-${{ runner.os }}-${{ hashFiles('common/config/rush/pnpm-lock.yaml') }}


    - name: Cache pnpm
      # we skip cache fetch if we are warming up the cache and cache hit
      if: ${{ steps.cache-pnpm-lookup.outputs.cache-hit != 'true' }}
      id: cache-pnpm
      uses: runs-on/cache@v4
      env:
        RUNS_ON_S3_BUCKET_CACHE: gdc-github-cache
      with:
        path: |
          common/temp/pnpm-store
        key: pnpm-cache-${{ runner.os }}-${{ hashFiles('common/config/rush/pnpm-lock.yaml') }}

    - name: Install rush
      # we skip instal if we are warming up the cache and cache hit
      if: ${{ steps.cache-pnpm-lookup.outputs.cache-hit != 'true' }}
      env:
        NPM_AUTH_TOKEN: ${{ env.NPM_AUTH_TOKEN }}
      run: |
        node common/scripts/install-run-rush.js install
      shell: bash
