# (C) 2022 GoodData Corporation

name: "Action to update hugo version param in parmas.toml"
description: "Action add new version to hugo version config set it latest and remove old one"

inputs:
    path-to-version-config:
        description: "Path to hugo version config"
        required: true
    version:
        description: "New version to be set"
        required: true

runs:
    using: "node20"
    main: "action-build/index.js"
