// (C) 2007-2022 GoodData Corporation
/**
 * @public
 * @deprecated catalog helper is deprecated in favor of code-based catalog that can be generated by catalog-export tool
 */
export interface IIdentifierWithTags {
    identifier: string;
    tags: string;
}

/**
 * @public
 * @deprecated catalog helper is deprecated in favor of code-based catalog that can be generated by catalog-export tool
 */
export interface IDisplayForms {
    [key: string]: IIdentifierWithTags;
}

/**
 * @public
 * @deprecated catalog helper is deprecated in favor of code-based catalog that can be generated by catalog-export tool
 */
export interface IAttrItem {
    identifier: string;
    tags: string;
    displayForms: IDisplayForms;
    defaultDisplayForm: IIdentifierWithTags;
}

/**
 * @public
 * @deprecated catalog helper is deprecated in favor of code-based catalog that can be generated by catalog-export tool
 */
export interface IAttrs {
    [key: string]: IAttrItem;
}

/**
 * @public
 * @deprecated catalog helper is deprecated in favor of code-based catalog that can be generated by catalog-export tool
 */
export interface IDataSet {
    identifier: string;
    tags: string;
    attributes: IAttrs;
}

/**
 * @public
 * @deprecated catalog helper is deprecated in favor of code-based catalog that can be generated by catalog-export tool
 */
export interface ICatalog {
    measures?: { [key: string]: IIdentifierWithTags };
    visualizations: { [key: string]: IIdentifierWithTags };
    attributes: IAttrs;
    dateDataSets: { [key: string]: IDataSet };
}

function getDisplayFormFromAttr(
    attrs: IAttrs,
    attributeName: string,
    displayFormName: string | undefined,
    property: string,
): string {
    if (!displayFormName) {
        return attrs?.[attributeName]?.defaultDisplayForm?.[property];
    }
    return attrs?.[attributeName]?.displayForms?.[displayFormName]?.[property];
}

/**
 * Tool that exposes API that to look up measures, attributes, visualizations and other metadata elements
 *
 * @example
 * ```
 *  import catalog from './catalog.json';
 *  const C = new CatalogHelper(catalog);
 * ```
 *
 * @deprecated catalog helper is deprecated in favor of code-based catalog that can be generated by catalog-export tool
 * @public
 */
export class CatalogHelper {
    public measures: { [key: string]: IIdentifierWithTags };
    public visualizations: { [key: string]: IIdentifierWithTags };
    public attributes: { [key: string]: IAttrItem };
    public dateDataSets: { [key: string]: IDataSet };

    constructor(catalog: ICatalog) {
        this.measures = catalog.measures ?? {};
        this.visualizations = catalog.visualizations;
        this.attributes = catalog.attributes;
        this.dateDataSets = catalog.dateDataSets;
    }

    public measure(name: string): string {
        return this.measures?.[name]?.identifier;
    }

    public measureTags(name: string): string {
        return this.measures?.[name]?.tags;
    }

    public visualization(name: string): string {
        return this.visualizations?.[name]?.identifier;
    }

    public visualizationTags(name: string): string {
        return this.visualizations?.[name]?.tags;
    }

    public attribute(attributeName: string): string {
        return this.attributes?.[attributeName]?.identifier;
    }

    public attributeTags(attributeName: string): string {
        return this.attributes?.[attributeName]?.tags;
    }

    public attributeDisplayForm(attributeName: string, displayFormName?: string): string {
        return getDisplayFormFromAttr(this.attributes, attributeName, displayFormName, "identifier");
    }

    public attributeDisplayFormTags(attributeName: string, displayFormName?: string): string {
        return getDisplayFormFromAttr(this.attributes, attributeName, displayFormName, "tags");
    }

    public dateDataSet(dataSetName: string): string {
        return this.dateDataSets?.[dataSetName]?.identifier;
    }

    public dateDataSetTags(dataSetName: string): string {
        return this.dateDataSets?.[dataSetName]?.tags;
    }

    public dateDataSetAttribute(dataSetName: string, attrName: string): string {
        return this.dateDataSets?.[dataSetName]?.attributes?.[attrName]?.identifier;
    }

    public dateDataSetAttributeTags(dataSetName: string, attrName: string): string {
        return this.dateDataSets?.[dataSetName]?.attributes?.[attrName]?.tags;
    }

    public dateDataSetDisplayForm(
        dataSetName: string,
        attributeName: string,
        displayFormName?: string,
    ): string {
        const attrs = this.dateDataSets?.[dataSetName]?.attributes;
        return getDisplayFormFromAttr(attrs, attributeName, displayFormName, "identifier");
    }

    public dateDataSetDisplayFormTags(
        dataSetName: string,
        attributeName: string,
        displayFormName?: string,
    ): string {
        const attrs = this.dateDataSets?.[dataSetName]?.attributes;
        return getDisplayFormFromAttr(attrs, attributeName, displayFormName, "tags");
    }
}
