// (C) 2020-2025 GoodData Corporation

import { IWorkspaceDashboardsService, IWorkspaceInsightsService } from "@gooddata/sdk-backend-spi";

export const noopWorkspaceInsightsService: IWorkspaceInsightsService = {
    createInsight: (() => {}) as any,
    deleteInsight: (() => {}) as any,
    getInsight: (() => {}) as any,
    getInsightReferencedObjects: (() => {}) as any,
    getInsightReferencingObjects: (() => {}) as any,
    getInsightWithAddedFilters: (() => {}) as any,
    getInsights: (() => {}) as any,
    getInsightsQuery: (() => {}) as any,
    getVisualizationClass: (() => {}) as any,
    getVisualizationClasses: (() => {}) as any,
    updateInsight: (() => {}) as any,
} as IWorkspaceInsightsService;

export const noopWorkspaceDashboardsService: IWorkspaceDashboardsService = {
    createDashboard: (() => {}) as any,
    createScheduledMail: (() => {}) as any,
    updateScheduledMail: (() => {}) as any,
    createWidgetAlert: (() => {}) as any,
    deleteDashboard: (() => {}) as any,
    deleteWidgetAlert: (() => {}) as any,
    deleteWidgetAlerts: (() => {}) as any,
    deleteScheduledMail: (() => {}) as any,
    exportDashboardToPdf: (() => {}) as any,
    exportDashboardToPresentation: (() => {}) as any,
    getDashboard: (() => {}) as any,
    getDashboardWidgetAlertsForCurrentUser: (() => {}) as any,
    getDashboardWithReferences: (() => {}) as any,
    getDashboardReferencedObjects: (() => {}) as any,
    getAllWidgetAlertsForCurrentUser: (() => {}) as any,
    getDashboards: (() => {}) as any,
    getDashboardsQuery: (() => {}) as any,
    getResolvedFiltersForWidget: (() => {}) as any,
    getScheduledMailsForDashboard: (() => {}) as any,
    getScheduledMailsCountForDashboard: (() => {}) as any,
    getWidgetAlertsCountForWidgets: (() => {}) as any,
    getWidgetReferencedObjects: (() => {}) as any,
    updateDashboard: (() => {}) as any,
    updateWidgetAlert: (() => {}) as any,
    createDashboardPlugin: (() => {}) as any,
    deleteDashboardPlugin: (() => {}) as any,
    getDashboardPlugin: (() => {}) as any,
    getDashboardPlugins: (() => {}) as any,
    getDashboardPermissions: (() => {}) as any,
    validateDashboardsExistence: (() => {}) as any,
    getResolvedFiltersForWidgetWithMultipleDateFilters: (() => {}) as any,
    getFilterViewsForCurrentUser: (() => {}) as any,
    createFilterView: (() => {}) as any,
    deleteFilterView: (() => {}) as any,
    setFilterViewAsDefault: (() => {}) as any,
    workspace: "workspace",
} as IWorkspaceDashboardsService;
