# (C) 2026 GoodData Corporation
# /// script
# dependencies = ["datamodel-code-generator[ruff]>=0.56.0"]
# requires-python = ">=3.10"
# ///

"""Generate Python TypedDict types from the AAC JSON Schema.

Usage:
    uv run python scripts/generate_types.py          # generate _types.py
    uv run python scripts/generate_types.py --check   # verify _types.py is up-to-date
"""

from __future__ import annotations

import hashlib
import re
import subprocess
import sys
import tempfile
from pathlib import Path

SCRIPT_DIR = Path(__file__).resolve().parent
PYTHON_PKG_DIR = SCRIPT_DIR.parent
SCHEMAS_PKG_DIR = PYTHON_PKG_DIR.parent.parent / "sdk-code-schemas"
SCHEMA_PATH = SCHEMAS_PKG_DIR / "src" / "v1" / "metadata.json"
REFRESH_SCRIPT = SCHEMAS_PKG_DIR / "scripts" / "refresh-schema.mjs"
OUTPUT_PATH = PYTHON_PKG_DIR / "src" / "gooddata_code_convertors" / "_types.py"

COPYRIGHT_HEADER = f"# (C) {2026} GoodData Corporation\n"
SCHEMA_HASH_PREFIX = "# schema-hash: "

# Target Python 3.10+:
# - --no-use-closed-typed-dict: closed=True (PEP 728) requires Python 3.13+
# - NotRequired is imported from typing_extensions (moved to typing in 3.11)
# - TypeAlias and union operator (X | Y) work in 3.10 with __future__.annotations
CODEGEN_BASE_ARGS = [
    "--input-file-type", "jsonschema",
    "--output-model-type", "typing.TypedDict",
    "--use-standard-collections",
    "--target-python-version", "3.10",
    "--use-union-operator",
    "--strict-nullable",
    "--no-use-closed-typed-dict",
]


def post_process(source: str) -> str:
    # Strip the generated-by header and timestamp.
    source = re.sub(
        r"^# generated by datamodel-codegen:.*?\n(?:#.*\n)*\n",
        "",
        source,
    )

    # Remove duplicate TypedDict import from typing_extensions when typing already has it.
    # Keep NotRequired from typing_extensions (needed for Python 3.10).
    source = source.replace(
        "from typing_extensions import NotRequired, TypedDict\n",
        "from typing_extensions import NotRequired\n",
    )
    source = source.replace(
        "from typing_extensions import TypedDict\n",
        "",
    )

    # Generate __all__ so `from _types import *` only exports domain types,
    # not stdlib re-exports like Any, Literal, TypedDict, etc.
    public_names = re.findall(
        r"^(?:class (\w+)\(|(\w+): TypeAlias|(\w+) = TypedDict\()",
        source,
        re.MULTILINE,
    )
    names = sorted({n for group in public_names for n in group if n})
    all_block = "__all__ = [\n" + "".join(f'    "{n}",\n' for n in names) + "]\n\n"

    # Insert __all__ after the imports block (after the last import line).
    last_import = max(source.rfind("\nimport "), source.rfind("\nfrom "))
    insert_pos = source.index("\n", last_import + 1) + 1
    source = source[:insert_pos] + "\n" + all_block + source[insert_pos:]

    # Deduplicate Literal values. The narrowed JSON Schema repeats enum values
    # across oneOf branches and datamodel-code-generator concatenates them,
    # producing e.g. Literal['a', 'b', 'a', 'b'] instead of Literal['a', 'b'].
    source = re.sub(
        r"Literal\[([^\]]+)\]",
        lambda m: "Literal[{}]".format(
            ", ".join(
                dict.fromkeys(
                    v for v in (s.strip() for s in m.group(1).split(",")) if v
                )
            )
        ),
        source,
    )

    # Embed schema hash so a Node.js check can detect staleness without Python.
    schema_hash = hashlib.sha256(Path(SCHEMA_PATH).read_bytes()).hexdigest()
    header = COPYRIGHT_HEADER + f"{SCHEMA_HASH_PREFIX}{schema_hash}\n"

    return header + "\n" + source


def get_narrowed_schema() -> str:
    """Run the Node.js schema script to produce the narrowed JSON Schema."""
    result = subprocess.run(
        ["node", str(REFRESH_SCRIPT), "--narrowed-json"],
        capture_output=True,
        text=True,
        cwd=str(SCHEMAS_PKG_DIR),
        check=False,
    )
    if result.returncode != 0:
        print(f"Schema narrowing failed:\n{result.stderr}", file=sys.stderr)
        sys.exit(result.returncode)
    return result.stdout


def generate() -> str:
    narrowed_json = get_narrowed_schema()

    with tempfile.NamedTemporaryFile(mode="w", suffix=".json", delete=True) as tmp:
        tmp.write(narrowed_json)
        tmp.flush()

        result = subprocess.run(
            [sys.executable, "-m", "datamodel_code_generator",
             "--input", tmp.name, *CODEGEN_BASE_ARGS],
            capture_output=True,
            text=True,
            check=False,
        )

    if result.returncode != 0:
        print(result.stderr, file=sys.stderr)
        sys.exit(result.returncode)
    return post_process(result.stdout)


def main() -> None:
    if not SCHEMA_PATH.exists():
        print(f"Schema not found: {SCHEMA_PATH}", file=sys.stderr)
        sys.exit(1)
    if not REFRESH_SCRIPT.exists():
        print(f"Schema script not found: {REFRESH_SCRIPT}", file=sys.stderr)
        sys.exit(1)

    content = generate()

    if "--check" in sys.argv:
        if not OUTPUT_PATH.exists():
            print(f"Types file does not exist: {OUTPUT_PATH}", file=sys.stderr)
            sys.exit(1)
        existing = OUTPUT_PATH.read_text()
        if existing != content:
            print(
                f"Types file is stale: {OUTPUT_PATH}\n"
                "Run 'uv run python scripts/generate_types.py' to regenerate.",
                file=sys.stderr,
            )
            sys.exit(1)
        print("Types check passed - _types.py is up-to-date.")
    else:
        OUTPUT_PATH.write_text(content)
        print(f"Generated {OUTPUT_PATH}")


if __name__ == "__main__":
    main()
