# (C) 2026 GoodData Corporation
# /// script
# dependencies = ["datamodel-code-generator[ruff]>=0.66.1"]
# requires-python = ">=3.10"
# ///

"""Generate Python types from the AAC JSON Schema: static TypedDicts and, separately,
real runtime-validating Pydantic models.

Usage:
    uv run python scripts/generate_types.py          # generate _types.py + pydantic_models.py
    uv run python scripts/generate_types.py --check   # verify both are up-to-date
"""

from __future__ import annotations

import dataclasses
import hashlib
import json
import re
import subprocess
import sys
import tempfile
from pathlib import Path

SCRIPT_DIR = Path(__file__).resolve().parent
PYTHON_PKG_DIR = SCRIPT_DIR.parent
SCHEMAS_PKG_DIR = PYTHON_PKG_DIR.parent.parent / "sdk-code-schemas"
SCHEMA_PATH = SCHEMAS_PKG_DIR / "src" / "v1" / "metadata.json"
REFRESH_SCRIPT = SCHEMAS_PKG_DIR / "scripts" / "refresh-schema.mjs"
PACKAGE_DIR = PYTHON_PKG_DIR / "src" / "gooddata_code_convertors"

COPYRIGHT_HEADER = f"# (C) {2026} GoodData Corporation\n"
SCHEMA_HASH_PREFIX = "# schema-hash: "

# Target Python 3.10+ for both targets:
# - NotRequired is imported from typing_extensions (moved to typing in 3.11)
# - TypeAlias and union operator (X | Y) work in 3.10 with __future__.annotations
CODEGEN_SHARED_ARGS = [
    "--input-file-type", "jsonschema",
    "--use-standard-collections",
    "--target-python-version", "3.10",
    "--use-union-operator",
    "--strict-nullable",
]


# Some generated RootModel classes (e.g. Identifier) need model_config regex_engine=
# "python-re" to validate our schema's negative-lookahead patterns — a config pydantic
# didn't understand before 2.5.0, and which some 2.10.x RootModel releases silently
# ignored (pydantic#11042, fixed by pydantic#11184, landed by 2.11.0). That's a SILENT
# validation failure, not a crash, so pyproject.toml's floor alone can't be trusted to
# always be honored (stale venvs, transitive resolution) — inject a loud runtime guard
# into the generated file itself so it travels with the artifact.
MIN_PYDANTIC_VERSION = (2, 11, 0)


@dataclasses.dataclass(frozen=True)
class Target:
    """A single datamodel-code-generator invocation: one output model type, one file."""

    output_path: Path
    extra_args: list[str]
    require_pydantic: bool = False


TARGETS = [
    Target(
        output_path=PACKAGE_DIR / "_types.py",
        extra_args=[
            "--output-model-type", "typing.TypedDict",
            # closed=True (PEP 728) requires Python 3.13+, above our 3.10 floor.
            "--no-use-closed-typed-dict",
        ],
    ),
    Target(
        # No leading underscore: unlike _types.py (star-imported into __init__.py's
        # namespace), this is meant to be imported directly by name — `from
        # gooddata_code_convertors.pydantic_models import Dashboard` — since it can't
        # share __init__.py's namespace with _types (identical class names would collide).
        output_path=PACKAGE_DIR / "pydantic_models.py",
        require_pydantic=True,
        extra_args=[
            "--output-model-type", "pydantic_v2.BaseModel",
            # NOTE: --collapse-root-models was tried to avoid wrapping shared string-pattern
            # definitions (e.g. "id") in their own `class Id(RootModel[str])` — but it makes
            # datamodel-code-generator concatenate some prefixed variants (e.g. "metric/...")
            # with our schema's negative-lookahead patterns (`(?!\.)`), which pydantic-core's
            # Rust regex engine cannot compile (no look-around support) — SchemaError at import
            # time. Left uncollapsed: callers of those specific fields access `.root` to get the
            # str (see python/README.md). Revisit if a future datamodel-code-generator/
            # pydantic-core release fixes this.
            #
            # --generate-schema-validators is a no-op for this schema: every if/then/else
            # branch here is a pure type-discriminator ($ref selection by `type`), already
            # fully expressed by the generated Union/RootModel — not a conditional-required-
            # property rule, which is the only thing that flag actually emits validators for.
        ],
    ),
]


def post_process(source: str, schema_hash: str, *, require_pydantic: bool = False) -> str:
    # Strip the generated-by header and timestamp.
    source = re.sub(
        r"^# generated by datamodel-codegen:.*?\n(?:#.*\n)*\n",
        "",
        source,
    )

    # Remove duplicate TypedDict import from typing_extensions when typing already has it.
    # Keep NotRequired from typing_extensions (needed for Python 3.10).
    source = source.replace(
        "from typing_extensions import NotRequired, TypedDict\n",
        "from typing_extensions import NotRequired\n",
    )
    source = source.replace(
        "from typing_extensions import TypedDict\n",
        "",
    )

    # Generate __all__ so `from _types import *` only exports domain types,
    # not stdlib re-exports like Any, Literal, TypedDict, etc.
    public_names = re.findall(
        r"^(?:class (\w+)\(|(\w+): TypeAlias|(\w+) = TypedDict\()",
        source,
        re.MULTILINE,
    )
    names = sorted({n for group in public_names for n in group if n})
    all_block = "__all__ = [\n" + "".join(f'    "{n}",\n' for n in names) + "]\n\n"

    version_guard = ""
    if require_pydantic:
        min_version = ".".join(map(str, MIN_PYDANTIC_VERSION))
        version_guard = (
            "import re as _re\n"
            "import pydantic as _pydantic\n\n"
            # Match only the release core (major.minor.micro): pydantic.VERSION can be a
            # PEP 440 pre-release/local string (e.g. "2.13.0b2", "2.13.0+dev123"), and
            # int() on a raw dot-split segment like "0b2" raises ValueError instead of
            # the intended ImportError for an otherwise-compatible install.
            "_pydantic_version_match = _re.match(r'(\\d+)\\.(\\d+)\\.(\\d+)', _pydantic.VERSION)\n"
            f"if not _pydantic_version_match or tuple(int(g) for g in _pydantic_version_match.groups()) < {MIN_PYDANTIC_VERSION!r}:\n"
            "    raise ImportError(\n"
            f"        f'gooddata_code_convertors.pydantic_models requires pydantic>={min_version} '\n"
            "        f'(RootModel classes here need model_config regex_engine=\"python-re\" to validate "
            "negative-lookahead patterns, silently broken on some earlier/2.10.x releases — see "
            "pydantic#11042/#11184), but pydantic {_pydantic.VERSION} is installed.'\n"
            "    )\n\n"
        )

    # Insert the version guard and __all__ after the imports block (after the last
    # import line) — must come after `from __future__ import annotations`, which
    # datamodel-code-generator always emits first.
    last_import = max(source.rfind("\nimport "), source.rfind("\nfrom "))
    insert_pos = source.index("\n", last_import + 1) + 1
    source = source[:insert_pos] + "\n" + version_guard + all_block + source[insert_pos:]

    # Deduplicate Literal values. The narrowed JSON Schema repeats enum values
    # across oneOf branches and datamodel-code-generator concatenates them,
    # producing e.g. Literal['a', 'b', 'a', 'b'] instead of Literal['a', 'b'].
    source = re.sub(
        r"Literal\[([^\]]+)\]",
        lambda m: "Literal[{}]".format(
            ", ".join(
                dict.fromkeys(
                    v for v in (s.strip() for s in m.group(1).split(",")) if v
                )
            )
        ),
        source,
    )

    # Embed schema hash so a Node.js check can detect staleness without Python.
    header = COPYRIGHT_HEADER + f"{SCHEMA_HASH_PREFIX}{schema_hash}\n"

    return header + "\n" + source


# --- Conditional-branch resolution (narrowed schema -> plain oneOf of $refs) -----------
#
# refresh-schema.mjs already rewrites the schema's `allOf` + `if`/`then`/`else` unions
# into `oneOf`, which is enough for json-schema-to-typescript. It is NOT enough for
# datamodel-code-generator, which produced silently-truncating models until GDAI-2172:
#
#   * A branch keeps the `if` alongside its `then` body, and a `then` that is a bare
#     `$ref` ends up as `{"$ref": ..., "if": ...}`. Sibling keys next to a `$ref` make
#     datamodel-code-generator try to turn the reference into a BASE CLASS. That works
#     only when the target is a plain object model; when the target is itself a union
#     (a RootModel, e.g. Date Filter) there is nothing to inherit from, so it silently
#     emits a member carrying only the union's own `properties` — a `type`-only stub.
#     A stub has no `extra='forbid'`, so it validates ANY payload with a matching
#     `type` and drops every other key on model_dump(). Data loss, not an error.
#   * `{"not": {}}` (an intentionally unsatisfiable `else`) becomes `Any`, which is the
#     exact inverse of its meaning and makes the whole union accept anything.
#
# So before the generator runs, collapse each conditional branch to the branch body
# itself. The parent union's `properties`/`required` are dropped with it: they are only
# the discriminator, every branch restates them, and each branch is already merged with
# its parent by narrowSchema. That leaves a plain `oneOf` over the real per-type models,
# which datamodel-code-generator turns into a correct RootModel union.
#
# This runs on the narrowed schema in memory. metadata.json (the shared contract with
# the TS side) and the TypeScript output are both untouched.

# Lifted off a union node whose members are all conditional branches, and pushed down
# into any branch that does not state its own. Leaving them on the parent is what makes
# the generator emit stubs; dropping them outright loses constraints, because a branch
# body is free to omit a keyword while still meaning it. Two worked examples:
# $defs/queryDateFilter states `additionalProperties: false` once and lets both if/then
# branches inherit it, and $defs/dashboardAttributeFilter states
# `required: ["type", "using"]` once while neither branch restates it. In JSON Schema
# the parent constrains every branch conjunctively, so copying down is exact.
INHERITED_KEYWORDS = ("properties", "required", "additionalProperties", "type")

# Keywords that describe rather than constrain; a branch holding only these matches
# anything. `$semantic` is our own editor-completion extension, used for the
# "no `type` yet" branch of a union — an authoring hint, not a data variant.
ANNOTATION_KEYWORDS = frozenset(
    {"$semantic", "$comment", "title", "description", "examples", "default", "deprecated"}
)


def is_dead_branch(branch: object) -> bool:
    """True for a union member that must not become a generated model.

    Two cases, opposite in meaning, same treatment:
      * annotation-only — matches everything, so as a union member it swallows payloads
        that belong to a sibling member;
      * `{"not": {}}` — matches nothing, an `else` written to make the branch fail.
    """
    if not isinstance(branch, dict):
        return False
    constraints = set(branch) - ANNOTATION_KEYWORDS
    if not constraints:
        return True
    return constraints == {"not"} and branch["not"] == {}


def resolve_conditional_branches(node: object) -> object:
    """Rewrite narrowed `if`-carrying branches into plain schemas, bottom-up."""
    if isinstance(node, list):
        return [resolve_conditional_branches(item) for item in node]
    if not isinstance(node, dict):
        return node

    # Read the `if` marker off the raw members: resolving them strips it.
    members = node.get("oneOf")
    is_conditional_union = (
        isinstance(members, list)
        and bool(members)
        and all(isinstance(member, dict) and "if" in member for member in members)
    )

    resolved = {key: resolve_conditional_branches(value) for key, value in node.items()}

    if is_conditional_union:
        # Identify dead branches BEFORE inheriting anything, and never inherit into
        # one: a `{"not": {}}` or annotation-only branch that picks up a keyword stops
        # looking dead to is_dead_branch() and survives into the union as a stub.
        live = [member for member in resolved["oneOf"] if not is_dead_branch(member)]
        for keyword in INHERITED_KEYWORDS:
            inherited = resolved.pop(keyword, None)
            if inherited is None:
                continue
            for member in live:
                # A `$ref` member carries its own definition; anything beside the
                # `$ref` is what made the generator emit a stub in the first place.
                if not isinstance(member, dict) or "$ref" in member:
                    continue
                # An empty `properties: {}` counts as unstated. The generator renders a
                # closed-but-propertyless object as `dict[str, Any]`, which in a union
                # matches any mapping and swallows payloads meant for its siblings —
                # e.g. the "All (no condition)" branch of $defs/mvfCondition.
                if member.get(keyword) in (None, {}) and keyword not in ("type",):
                    member[keyword] = inherited
                elif keyword not in member:
                    member[keyword] = inherited
        # An all-dead union keeps its members rather than emit an empty `oneOf` the
        # generator can't read. Nothing was inherited into them, so the node stays
        # annotation-only and the enclosing union drops it in turn.
        if live:
            resolved["oneOf"] = live

    if "if" not in resolved:
        return resolved
    # This node is one conditional branch. Its body is the whole truth; `if` and the
    # parent keys merged into it by narrowSchema only re-state the discriminator.
    if "$ref" in resolved:
        return {"$ref": resolved["$ref"]}
    if "oneOf" in resolved:
        branches = resolved["oneOf"]
        return branches[0] if len(branches) == 1 else {"oneOf": branches}
    resolved.pop("if", None)
    return resolved


def get_narrowed_schema() -> str:
    """Run the Node.js schema script to produce the narrowed JSON Schema."""
    result = subprocess.run(
        ["node", str(REFRESH_SCRIPT), "--narrowed-json"],
        capture_output=True,
        text=True,
        cwd=str(SCHEMAS_PKG_DIR),
        check=False,
    )
    if result.returncode != 0:
        print(f"Schema narrowing failed:\n{result.stderr}", file=sys.stderr)
        sys.exit(result.returncode)
    return json.dumps(resolve_conditional_branches(json.loads(result.stdout)))


def generate(target: Target, schema_path: str, schema_hash: str) -> str:
    result = subprocess.run(
        [sys.executable, "-m", "datamodel_code_generator",
         "--input", schema_path, *CODEGEN_SHARED_ARGS, *target.extra_args],
        capture_output=True,
        text=True,
        check=False,
    )
    if result.returncode != 0:
        print(result.stderr, file=sys.stderr)
        sys.exit(result.returncode)
    return post_process(result.stdout, schema_hash, require_pydantic=target.require_pydantic)


def main() -> None:
    if not SCHEMA_PATH.exists():
        print(f"Schema not found: {SCHEMA_PATH}", file=sys.stderr)
        sys.exit(1)
    if not REFRESH_SCRIPT.exists():
        print(f"Schema script not found: {REFRESH_SCRIPT}", file=sys.stderr)
        sys.exit(1)

    narrowed_json = get_narrowed_schema()
    schema_hash = hashlib.sha256(Path(SCHEMA_PATH).read_bytes()).hexdigest()

    # Single shared temp file: both targets read the same narrowed schema, and
    # delete=False + explicit unlink is needed because datamodel-code-generator (a
    # separate process) opens it by path — Windows can't reopen a file while the
    # writer's handle is still open.
    tmp = tempfile.NamedTemporaryFile(mode="w", suffix=".json", delete=False)
    try:
        tmp.write(narrowed_json)
        tmp.close()
        # Generate all targets before writing any of them: a later target failing
        # (generate() calls sys.exit itself) must not leave an earlier target's
        # freshly-regenerated file committed while its sibling is stale/missing.
        contents = [(target, generate(target, tmp.name, schema_hash)) for target in TARGETS]
    finally:
        Path(tmp.name).unlink(missing_ok=True)

    check = "--check" in sys.argv
    stale: list[Path] = []

    for target, content in contents:
        if check:
            if not target.output_path.exists():
                print(f"Types file does not exist: {target.output_path}", file=sys.stderr)
                stale.append(target.output_path)
                continue
            if target.output_path.read_text() != content:
                stale.append(target.output_path)
        else:
            target.output_path.write_text(content)
            print(f"Generated {target.output_path}")

    if check:
        if stale:
            names = ", ".join(p.name for p in stale)
            print(
                f"Stale or missing: {names}\n"
                "Run 'uv run python scripts/generate_types.py' to regenerate.",
                file=sys.stderr,
            )
            sys.exit(1)
        print("Types check passed - all generated files are up-to-date.")


if __name__ == "__main__":
    main()
