// (C) 2023 GoodData Corporation

import { type ICatalogDateDataset, type IDateHierarchyTemplate } from "@gooddata/sdk-model";

export const defaultDateHierarchyTemplates: IDateHierarchyTemplate[] = [
    {
        type: "dateHierarchyTemplate",
        ref: {
            identifier: "default",
        },
        id: "default",
        uri: "/default",
        title: "Year, quarter, month, date, hour, minute",
        granularities: [
            "GDC.time.year",
            "GDC.time.quarter",
            "GDC.time.month",
            "GDC.time.date",
            "GDC.time.hour",
            "GDC.time.minute",
        ],
        description: "Default hierarchy template for date dataset",
        production: true,
        deprecated: false,
        unlisted: false,
    },
];

export const catalogDateDatasets: ICatalogDateDataset[] = [
    {
        type: "dateDataset",
        relevance: 0,
        dataSet: {
            type: "dataSet",
            ref: {
                identifier: "order_date",
                type: "dataSet",
            },
            id: "order_date",
            title: "Order date",
            description: "",
            uri: "/api/v1/entities/workspaces/cef8d39392784675852790d4d1df14fc/datasets/order_date",
            production: true,
            deprecated: false,
            unlisted: false,
        },
        dateAttributes: [
            {
                granularity: "GDC.time.date",
                attribute: {
                    type: "attribute",
                    ref: {
                        identifier: "order_date.day",
                        type: "attribute",
                    },
                    id: "order_date.day",
                    uri: "/api/v1/entities/workspaces/cef8d39392784675852790d4d1df14fc/attributes/order_date.day",
                    title: "Order date - Date",
                    description: "Date",
                    displayForms: [
                        {
                            type: "displayForm",
                            ref: {
                                identifier: "order_date.day",
                                type: "displayForm",
                            },
                            id: "order_date.day",
                            uri: "/api/v1/entities/workspaces/cef8d39392784675852790d4d1df14fc/labels/order_date.day",
                            title: "Order date - Date",
                            description: "Date",
                            attribute: {
                                identifier: "order_date.day",
                                type: "attribute",
                            },
                            production: true,
                            deprecated: false,
                            unlisted: false,
                        },
                    ],
                    production: true,
                    deprecated: false,
                    unlisted: false,
                },
                defaultDisplayForm: {
                    type: "displayForm",
                    ref: {
                        identifier: "order_date.day",
                        type: "displayForm",
                    },
                    id: "order_date.day",
                    uri: "/api/v1/entities/workspaces/cef8d39392784675852790d4d1df14fc/labels/order_date.day",
                    title: "Order date - Date",
                    description: "Date",
                    attribute: {
                        identifier: "order_date.day",
                        type: "attribute",
                    },
                    production: true,
                    deprecated: false,
                    unlisted: false,
                },
            },
            {
                granularity: "GDC.time.day_in_month",
                attribute: {
                    type: "attribute",
                    ref: {
                        identifier: "order_date.dayOfMonth",
                        type: "attribute",
                    },
                    id: "order_date.dayOfMonth",
                    uri: "/api/v1/entities/workspaces/cef8d39392784675852790d4d1df14fc/attributes/order_date.dayOfMonth",
                    title: "Order date - Day of Month",
                    description: "Generic Day of the Month (D1-D31)",
                    displayForms: [
                        {
                            type: "displayForm",
                            ref: {
                                identifier: "order_date.dayOfMonth",
                                type: "displayForm",
                            },
                            id: "order_date.dayOfMonth",
                            uri: "/api/v1/entities/workspaces/cef8d39392784675852790d4d1df14fc/labels/order_date.dayOfMonth",
                            title: "Order date - Day of Month",
                            description: "Generic Day of the Month (D1-D31)",
                            attribute: {
                                identifier: "order_date.dayOfMonth",
                                type: "attribute",
                            },
                            production: true,
                            deprecated: false,
                            unlisted: false,
                        },
                    ],
                    production: true,
                    deprecated: false,
                    unlisted: false,
                },
                defaultDisplayForm: {
                    type: "displayForm",
                    ref: {
                        identifier: "order_date.dayOfMonth",
                        type: "displayForm",
                    },
                    id: "order_date.dayOfMonth",
                    uri: "/api/v1/entities/workspaces/cef8d39392784675852790d4d1df14fc/labels/order_date.dayOfMonth",
                    title: "Order date - Day of Month",
                    description: "Generic Day of the Month (D1-D31)",
                    attribute: {
                        identifier: "order_date.dayOfMonth",
                        type: "attribute",
                    },
                    production: true,
                    deprecated: false,
                    unlisted: false,
                },
            },
            {
                granularity: "GDC.time.day_in_week",
                attribute: {
                    type: "attribute",
                    ref: {
                        identifier: "order_date.dayOfWeek",
                        type: "attribute",
                    },
                    id: "order_date.dayOfWeek",
                    uri: "/api/v1/entities/workspaces/cef8d39392784675852790d4d1df14fc/attributes/order_date.dayOfWeek",
                    title: "Order date - Day of Week",
                    description: "Generic Day of the Week (D1-D7)",
                    displayForms: [
                        {
                            type: "displayForm",
                            ref: {
                                identifier: "order_date.dayOfWeek",
                                type: "displayForm",
                            },
                            id: "order_date.dayOfWeek",
                            uri: "/api/v1/entities/workspaces/cef8d39392784675852790d4d1df14fc/labels/order_date.dayOfWeek",
                            title: "Order date - Day of Week",
                            description: "Generic Day of the Week (D1-D7)",
                            attribute: {
                                identifier: "order_date.dayOfWeek",
                                type: "attribute",
                            },
                            production: true,
                            deprecated: false,
                            unlisted: false,
                        },
                    ],
                    production: true,
                    deprecated: false,
                    unlisted: false,
                },
                defaultDisplayForm: {
                    type: "displayForm",
                    ref: {
                        identifier: "order_date.dayOfWeek",
                        type: "displayForm",
                    },
                    id: "order_date.dayOfWeek",
                    uri: "/api/v1/entities/workspaces/cef8d39392784675852790d4d1df14fc/labels/order_date.dayOfWeek",
                    title: "Order date - Day of Week",
                    description: "Generic Day of the Week (D1-D7)",
                    attribute: {
                        identifier: "order_date.dayOfWeek",
                        type: "attribute",
                    },
                    production: true,
                    deprecated: false,
                    unlisted: false,
                },
            },
            {
                granularity: "GDC.time.day_in_year",
                attribute: {
                    type: "attribute",
                    ref: {
                        identifier: "order_date.dayOfYear",
                        type: "attribute",
                    },
                    id: "order_date.dayOfYear",
                    uri: "/api/v1/entities/workspaces/cef8d39392784675852790d4d1df14fc/attributes/order_date.dayOfYear",
                    title: "Order date - Day of Year",
                    description: "Generic Day of the Year (D1-D366)",
                    displayForms: [
                        {
                            type: "displayForm",
                            ref: {
                                identifier: "order_date.dayOfYear",
                                type: "displayForm",
                            },
                            id: "order_date.dayOfYear",
                            uri: "/api/v1/entities/workspaces/cef8d39392784675852790d4d1df14fc/labels/order_date.dayOfYear",
                            title: "Order date - Day of Year",
                            description: "Generic Day of the Year (D1-D366)",
                            attribute: {
                                identifier: "order_date.dayOfYear",
                                type: "attribute",
                            },
                            production: true,
                            deprecated: false,
                            unlisted: false,
                        },
                    ],
                    production: true,
                    deprecated: false,
                    unlisted: false,
                },
                defaultDisplayForm: {
                    type: "displayForm",
                    ref: {
                        identifier: "order_date.dayOfYear",
                        type: "displayForm",
                    },
                    id: "order_date.dayOfYear",
                    uri: "/api/v1/entities/workspaces/cef8d39392784675852790d4d1df14fc/labels/order_date.dayOfYear",
                    title: "Order date - Day of Year",
                    description: "Generic Day of the Year (D1-D366)",
                    attribute: {
                        identifier: "order_date.dayOfYear",
                        type: "attribute",
                    },
                    production: true,
                    deprecated: false,
                    unlisted: false,
                },
            },
            {
                granularity: "GDC.time.hour_in_day",
                attribute: {
                    type: "attribute",
                    ref: {
                        identifier: "order_date.hourOfDay",
                        type: "attribute",
                    },
                    id: "order_date.hourOfDay",
                    uri: "/api/v1/entities/workspaces/cef8d39392784675852790d4d1df14fc/attributes/order_date.hourOfDay",
                    title: "Order date - Hour of Day",
                    description: "Generic Hour of the Day(H1-H24)",
                    displayForms: [
                        {
                            type: "displayForm",
                            ref: {
                                identifier: "order_date.hourOfDay",
                                type: "displayForm",
                            },
                            id: "order_date.hourOfDay",
                            uri: "/api/v1/entities/workspaces/cef8d39392784675852790d4d1df14fc/labels/order_date.hourOfDay",
                            title: "Order date - Hour of Day",
                            description: "Generic Hour of the Day(H1-H24)",
                            attribute: {
                                identifier: "order_date.hourOfDay",
                                type: "attribute",
                            },
                            production: true,
                            deprecated: false,
                            unlisted: false,
                        },
                    ],
                    production: true,
                    deprecated: false,
                    unlisted: false,
                },
                defaultDisplayForm: {
                    type: "displayForm",
                    ref: {
                        identifier: "order_date.hourOfDay",
                        type: "displayForm",
                    },
                    id: "order_date.hourOfDay",
                    uri: "/api/v1/entities/workspaces/cef8d39392784675852790d4d1df14fc/labels/order_date.hourOfDay",
                    title: "Order date - Hour of Day",
                    description: "Generic Hour of the Day(H1-H24)",
                    attribute: {
                        identifier: "order_date.hourOfDay",
                        type: "attribute",
                    },
                    production: true,
                    deprecated: false,
                    unlisted: false,
                },
            },
            {
                granularity: "GDC.time.minute",
                attribute: {
                    type: "attribute",
                    ref: {
                        identifier: "order_date.minute",
                        type: "attribute",
                    },
                    id: "order_date.minute",
                    uri: "/api/v1/entities/workspaces/cef8d39392784675852790d4d1df14fc/attributes/order_date.minute",
                    title: "Order date - Minute",
                    description: "Minute",
                    displayForms: [
                        {
                            type: "displayForm",
                            ref: {
                                identifier: "order_date.minute",
                                type: "displayForm",
                            },
                            id: "order_date.minute",
                            uri: "/api/v1/entities/workspaces/cef8d39392784675852790d4d1df14fc/labels/order_date.minute",
                            title: "Order date - Minute",
                            description: "Minute",
                            attribute: {
                                identifier: "order_date.minute",
                                type: "attribute",
                            },
                            production: true,
                            deprecated: false,
                            unlisted: false,
                        },
                    ],
                    production: true,
                    deprecated: false,
                    unlisted: false,
                },
                defaultDisplayForm: {
                    type: "displayForm",
                    ref: {
                        identifier: "order_date.minute",
                        type: "displayForm",
                    },
                    id: "order_date.minute",
                    uri: "/api/v1/entities/workspaces/cef8d39392784675852790d4d1df14fc/labels/order_date.minute",
                    title: "Order date - Minute",
                    description: "Minute",
                    attribute: {
                        identifier: "order_date.minute",
                        type: "attribute",
                    },
                    production: true,
                    deprecated: false,
                    unlisted: false,
                },
            },
            {
                granularity: "GDC.time.minute_in_hour",
                attribute: {
                    type: "attribute",
                    ref: {
                        identifier: "order_date.minuteOfHour",
                        type: "attribute",
                    },
                    id: "order_date.minuteOfHour",
                    uri: "/api/v1/entities/workspaces/cef8d39392784675852790d4d1df14fc/attributes/order_date.minuteOfHour",
                    title: "Order date - Minute of Hour",
                    description: "Generic Minute of the Hour(MI1-MI60)",
                    displayForms: [
                        {
                            type: "displayForm",
                            ref: {
                                identifier: "order_date.minuteOfHour",
                                type: "displayForm",
                            },
                            id: "order_date.minuteOfHour",
                            uri: "/api/v1/entities/workspaces/cef8d39392784675852790d4d1df14fc/labels/order_date.minuteOfHour",
                            title: "Order date - Minute of Hour",
                            description: "Generic Minute of the Hour(MI1-MI60)",
                            attribute: {
                                identifier: "order_date.minuteOfHour",
                                type: "attribute",
                            },
                            production: true,
                            deprecated: false,
                            unlisted: false,
                        },
                    ],
                    production: true,
                    deprecated: false,
                    unlisted: false,
                },
                defaultDisplayForm: {
                    type: "displayForm",
                    ref: {
                        identifier: "order_date.minuteOfHour",
                        type: "displayForm",
                    },
                    id: "order_date.minuteOfHour",
                    uri: "/api/v1/entities/workspaces/cef8d39392784675852790d4d1df14fc/labels/order_date.minuteOfHour",
                    title: "Order date - Minute of Hour",
                    description: "Generic Minute of the Hour(MI1-MI60)",
                    attribute: {
                        identifier: "order_date.minuteOfHour",
                        type: "attribute",
                    },
                    production: true,
                    deprecated: false,
                    unlisted: false,
                },
            },
            {
                granularity: "GDC.time.month",
                attribute: {
                    type: "attribute",
                    ref: {
                        identifier: "order_date.month",
                        type: "attribute",
                    },
                    id: "order_date.month",
                    uri: "/api/v1/entities/workspaces/cef8d39392784675852790d4d1df14fc/attributes/order_date.month",
                    title: "Order date - Month/Year",
                    description: "Month and Year (12/2020)",
                    displayForms: [
                        {
                            type: "displayForm",
                            ref: {
                                identifier: "order_date.month",
                                type: "displayForm",
                            },
                            id: "order_date.month",
                            uri: "/api/v1/entities/workspaces/cef8d39392784675852790d4d1df14fc/labels/order_date.month",
                            title: "Order date - Month/Year",
                            description: "Month and Year (12/2020)",
                            attribute: {
                                identifier: "order_date.month",
                                type: "attribute",
                            },
                            production: true,
                            deprecated: false,
                            unlisted: false,
                        },
                    ],
                    production: true,
                    deprecated: false,
                    unlisted: false,
                },
                defaultDisplayForm: {
                    type: "displayForm",
                    ref: {
                        identifier: "order_date.month",
                        type: "displayForm",
                    },
                    id: "order_date.month",
                    uri: "/api/v1/entities/workspaces/cef8d39392784675852790d4d1df14fc/labels/order_date.month",
                    title: "Order date - Month/Year",
                    description: "Month and Year (12/2020)",
                    attribute: {
                        identifier: "order_date.month",
                        type: "attribute",
                    },
                    production: true,
                    deprecated: false,
                    unlisted: false,
                },
            },
            {
                granularity: "GDC.time.month_in_year",
                attribute: {
                    type: "attribute",
                    ref: {
                        identifier: "order_date.monthOfYear",
                        type: "attribute",
                    },
                    id: "order_date.monthOfYear",
                    uri: "/api/v1/entities/workspaces/cef8d39392784675852790d4d1df14fc/attributes/order_date.monthOfYear",
                    title: "Order date - Month of Year",
                    description: "Generic Month (M1-M12)",
                    displayForms: [
                        {
                            type: "displayForm",
                            ref: {
                                identifier: "order_date.monthOfYear",
                                type: "displayForm",
                            },
                            id: "order_date.monthOfYear",
                            uri: "/api/v1/entities/workspaces/cef8d39392784675852790d4d1df14fc/labels/order_date.monthOfYear",
                            title: "Order date - Month of Year",
                            description: "Generic Month (M1-M12)",
                            attribute: {
                                identifier: "order_date.monthOfYear",
                                type: "attribute",
                            },
                            production: true,
                            deprecated: false,
                            unlisted: false,
                        },
                    ],
                    production: true,
                    deprecated: false,
                    unlisted: false,
                },
                defaultDisplayForm: {
                    type: "displayForm",
                    ref: {
                        identifier: "order_date.monthOfYear",
                        type: "displayForm",
                    },
                    id: "order_date.monthOfYear",
                    uri: "/api/v1/entities/workspaces/cef8d39392784675852790d4d1df14fc/labels/order_date.monthOfYear",
                    title: "Order date - Month of Year",
                    description: "Generic Month (M1-M12)",
                    attribute: {
                        identifier: "order_date.monthOfYear",
                        type: "attribute",
                    },
                    production: true,
                    deprecated: false,
                    unlisted: false,
                },
            },
            {
                granularity: "GDC.time.quarter",
                attribute: {
                    type: "attribute",
                    ref: {
                        identifier: "order_date.quarter",
                        type: "attribute",
                    },
                    id: "order_date.quarter",
                    uri: "/api/v1/entities/workspaces/cef8d39392784675852790d4d1df14fc/attributes/order_date.quarter",
                    title: "Order date - Quarter/Year",
                    description: "Quarter and Year (Q1/2020)",
                    displayForms: [
                        {
                            type: "displayForm",
                            ref: {
                                identifier: "order_date.quarter",
                                type: "displayForm",
                            },
                            id: "order_date.quarter",
                            uri: "/api/v1/entities/workspaces/cef8d39392784675852790d4d1df14fc/labels/order_date.quarter",
                            title: "Order date - Quarter/Year",
                            description: "Quarter and Year (Q1/2020)",
                            attribute: {
                                identifier: "order_date.quarter",
                                type: "attribute",
                            },
                            production: true,
                            deprecated: false,
                            unlisted: false,
                        },
                    ],
                    production: true,
                    deprecated: false,
                    unlisted: false,
                },
                defaultDisplayForm: {
                    type: "displayForm",
                    ref: {
                        identifier: "order_date.quarter",
                        type: "displayForm",
                    },
                    id: "order_date.quarter",
                    uri: "/api/v1/entities/workspaces/cef8d39392784675852790d4d1df14fc/labels/order_date.quarter",
                    title: "Order date - Quarter/Year",
                    description: "Quarter and Year (Q1/2020)",
                    attribute: {
                        identifier: "order_date.quarter",
                        type: "attribute",
                    },
                    production: true,
                    deprecated: false,
                    unlisted: false,
                },
            },
            {
                granularity: "GDC.time.quarter_in_year",
                attribute: {
                    type: "attribute",
                    ref: {
                        identifier: "order_date.quarterOfYear",
                        type: "attribute",
                    },
                    id: "order_date.quarterOfYear",
                    uri: "/api/v1/entities/workspaces/cef8d39392784675852790d4d1df14fc/attributes/order_date.quarterOfYear",
                    title: "Order date - Quarter of Year",
                    description: "Generic Quarter (Q1-Q4)",
                    displayForms: [
                        {
                            type: "displayForm",
                            ref: {
                                identifier: "order_date.quarterOfYear",
                                type: "displayForm",
                            },
                            id: "order_date.quarterOfYear",
                            uri: "/api/v1/entities/workspaces/cef8d39392784675852790d4d1df14fc/labels/order_date.quarterOfYear",
                            title: "Order date - Quarter of Year",
                            description: "Generic Quarter (Q1-Q4)",
                            attribute: {
                                identifier: "order_date.quarterOfYear",
                                type: "attribute",
                            },
                            production: true,
                            deprecated: false,
                            unlisted: false,
                        },
                    ],
                    production: true,
                    deprecated: false,
                    unlisted: false,
                },
                defaultDisplayForm: {
                    type: "displayForm",
                    ref: {
                        identifier: "order_date.quarterOfYear",
                        type: "displayForm",
                    },
                    id: "order_date.quarterOfYear",
                    uri: "/api/v1/entities/workspaces/cef8d39392784675852790d4d1df14fc/labels/order_date.quarterOfYear",
                    title: "Order date - Quarter of Year",
                    description: "Generic Quarter (Q1-Q4)",
                    attribute: {
                        identifier: "order_date.quarterOfYear",
                        type: "attribute",
                    },
                    production: true,
                    deprecated: false,
                    unlisted: false,
                },
            },
            {
                granularity: "GDC.time.week_us",
                attribute: {
                    type: "attribute",
                    ref: {
                        identifier: "order_date.week",
                        type: "attribute",
                    },
                    id: "order_date.week",
                    uri: "/api/v1/entities/workspaces/cef8d39392784675852790d4d1df14fc/attributes/order_date.week",
                    title: "Order date - Week/Year",
                    description: "Week and Year (W52/2020)",
                    displayForms: [
                        {
                            type: "displayForm",
                            ref: {
                                identifier: "order_date.week",
                                type: "displayForm",
                            },
                            id: "order_date.week",
                            uri: "/api/v1/entities/workspaces/cef8d39392784675852790d4d1df14fc/labels/order_date.week",
                            title: "Order date - Week/Year",
                            description: "Week and Year (W52/2020)",
                            attribute: {
                                identifier: "order_date.week",
                                type: "attribute",
                            },
                            production: true,
                            deprecated: false,
                            unlisted: false,
                        },
                    ],
                    production: true,
                    deprecated: false,
                    unlisted: false,
                },
                defaultDisplayForm: {
                    type: "displayForm",
                    ref: {
                        identifier: "order_date.week",
                        type: "displayForm",
                    },
                    id: "order_date.week",
                    uri: "/api/v1/entities/workspaces/cef8d39392784675852790d4d1df14fc/labels/order_date.week",
                    title: "Order date - Week/Year",
                    description: "Week and Year (W52/2020)",
                    attribute: {
                        identifier: "order_date.week",
                        type: "attribute",
                    },
                    production: true,
                    deprecated: false,
                    unlisted: false,
                },
            },
            {
                granularity: "GDC.time.week_in_year",
                attribute: {
                    type: "attribute",
                    ref: {
                        identifier: "order_date.weekOfYear",
                        type: "attribute",
                    },
                    id: "order_date.weekOfYear",
                    uri: "/api/v1/entities/workspaces/cef8d39392784675852790d4d1df14fc/attributes/order_date.weekOfYear",
                    title: "Order date - Week of Year",
                    description: "Generic Week (W1-W53)",
                    displayForms: [
                        {
                            type: "displayForm",
                            ref: {
                                identifier: "order_date.weekOfYear",
                                type: "displayForm",
                            },
                            id: "order_date.weekOfYear",
                            uri: "/api/v1/entities/workspaces/cef8d39392784675852790d4d1df14fc/labels/order_date.weekOfYear",
                            title: "Order date - Week of Year",
                            description: "Generic Week (W1-W53)",
                            attribute: {
                                identifier: "order_date.weekOfYear",
                                type: "attribute",
                            },
                            production: true,
                            deprecated: false,
                            unlisted: false,
                        },
                    ],
                    production: true,
                    deprecated: false,
                    unlisted: false,
                },
                defaultDisplayForm: {
                    type: "displayForm",
                    ref: {
                        identifier: "order_date.weekOfYear",
                        type: "displayForm",
                    },
                    id: "order_date.weekOfYear",
                    uri: "/api/v1/entities/workspaces/cef8d39392784675852790d4d1df14fc/labels/order_date.weekOfYear",
                    title: "Order date - Week of Year",
                    description: "Generic Week (W1-W53)",
                    attribute: {
                        identifier: "order_date.weekOfYear",
                        type: "attribute",
                    },
                    production: true,
                    deprecated: false,
                    unlisted: false,
                },
            },
            {
                granularity: "GDC.time.year",
                attribute: {
                    type: "attribute",
                    ref: {
                        identifier: "order_date.year",
                        type: "attribute",
                    },
                    id: "order_date.year",
                    uri: "/api/v1/entities/workspaces/cef8d39392784675852790d4d1df14fc/attributes/order_date.year",
                    title: "Order date - Year",
                    description: "Year",
                    displayForms: [
                        {
                            type: "displayForm",
                            ref: {
                                identifier: "order_date.year",
                                type: "displayForm",
                            },
                            id: "order_date.year",
                            uri: "/api/v1/entities/workspaces/cef8d39392784675852790d4d1df14fc/labels/order_date.year",
                            title: "Order date - Year",
                            description: "Year",
                            attribute: {
                                identifier: "order_date.year",
                                type: "attribute",
                            },
                            production: true,
                            deprecated: false,
                            unlisted: false,
                        },
                    ],
                    production: true,
                    deprecated: false,
                    unlisted: false,
                },
                defaultDisplayForm: {
                    type: "displayForm",
                    ref: {
                        identifier: "order_date.year",
                        type: "displayForm",
                    },
                    id: "order_date.year",
                    uri: "/api/v1/entities/workspaces/cef8d39392784675852790d4d1df14fc/labels/order_date.year",
                    title: "Order date - Year",
                    description: "Year",
                    attribute: {
                        identifier: "order_date.year",
                        type: "attribute",
                    },
                    production: true,
                    deprecated: false,
                    unlisted: false,
                },
            },
        ],
    },
    {
        type: "dateDataset",
        relevance: 0,
        dataSet: {
            type: "dataSet",
            ref: {
                identifier: "return_date",
                type: "dataSet",
            },
            id: "return_date",
            title: "Return date",
            description: "",
            uri: "/api/v1/entities/workspaces/cef8d39392784675852790d4d1df14fc/datasets/return_date",
            production: true,
            deprecated: false,
            unlisted: false,
        },
        dateAttributes: [
            {
                granularity: "GDC.time.date",
                attribute: {
                    type: "attribute",
                    ref: {
                        identifier: "return_date.day",
                        type: "attribute",
                    },
                    id: "return_date.day",
                    uri: "/api/v1/entities/workspaces/cef8d39392784675852790d4d1df14fc/attributes/return_date.day",
                    title: "Return date - Date",
                    description: "Date",
                    displayForms: [
                        {
                            type: "displayForm",
                            ref: {
                                identifier: "return_date.day",
                                type: "displayForm",
                            },
                            id: "return_date.day",
                            uri: "/api/v1/entities/workspaces/cef8d39392784675852790d4d1df14fc/labels/return_date.day",
                            title: "Return date - Date",
                            description: "Date",
                            attribute: {
                                identifier: "return_date.day",
                                type: "attribute",
                            },
                            production: true,
                            deprecated: false,
                            unlisted: false,
                        },
                    ],
                    production: true,
                    deprecated: false,
                    unlisted: false,
                },
                defaultDisplayForm: {
                    type: "displayForm",
                    ref: {
                        identifier: "return_date.day",
                        type: "displayForm",
                    },
                    id: "return_date.day",
                    uri: "/api/v1/entities/workspaces/cef8d39392784675852790d4d1df14fc/labels/return_date.day",
                    title: "Return date - Date",
                    description: "Date",
                    attribute: {
                        identifier: "return_date.day",
                        type: "attribute",
                    },
                    production: true,
                    deprecated: false,
                    unlisted: false,
                },
            },
            {
                granularity: "GDC.time.day_in_month",
                attribute: {
                    type: "attribute",
                    ref: {
                        identifier: "return_date.dayOfMonth",
                        type: "attribute",
                    },
                    id: "return_date.dayOfMonth",
                    uri: "/api/v1/entities/workspaces/cef8d39392784675852790d4d1df14fc/attributes/return_date.dayOfMonth",
                    title: "Return date - Day of Month",
                    description: "Generic Day of the Month (D1-D31)",
                    displayForms: [
                        {
                            type: "displayForm",
                            ref: {
                                identifier: "return_date.dayOfMonth",
                                type: "displayForm",
                            },
                            id: "return_date.dayOfMonth",
                            uri: "/api/v1/entities/workspaces/cef8d39392784675852790d4d1df14fc/labels/return_date.dayOfMonth",
                            title: "Return date - Day of Month",
                            description: "Generic Day of the Month (D1-D31)",
                            attribute: {
                                identifier: "return_date.dayOfMonth",
                                type: "attribute",
                            },
                            production: true,
                            deprecated: false,
                            unlisted: false,
                        },
                    ],
                    production: true,
                    deprecated: false,
                    unlisted: false,
                },
                defaultDisplayForm: {
                    type: "displayForm",
                    ref: {
                        identifier: "return_date.dayOfMonth",
                        type: "displayForm",
                    },
                    id: "return_date.dayOfMonth",
                    uri: "/api/v1/entities/workspaces/cef8d39392784675852790d4d1df14fc/labels/return_date.dayOfMonth",
                    title: "Return date - Day of Month",
                    description: "Generic Day of the Month (D1-D31)",
                    attribute: {
                        identifier: "return_date.dayOfMonth",
                        type: "attribute",
                    },
                    production: true,
                    deprecated: false,
                    unlisted: false,
                },
            },
            {
                granularity: "GDC.time.day_in_week",
                attribute: {
                    type: "attribute",
                    ref: {
                        identifier: "return_date.dayOfWeek",
                        type: "attribute",
                    },
                    id: "return_date.dayOfWeek",
                    uri: "/api/v1/entities/workspaces/cef8d39392784675852790d4d1df14fc/attributes/return_date.dayOfWeek",
                    title: "Return date - Day of Week",
                    description: "Generic Day of the Week (D1-D7)",
                    displayForms: [
                        {
                            type: "displayForm",
                            ref: {
                                identifier: "return_date.dayOfWeek",
                                type: "displayForm",
                            },
                            id: "return_date.dayOfWeek",
                            uri: "/api/v1/entities/workspaces/cef8d39392784675852790d4d1df14fc/labels/return_date.dayOfWeek",
                            title: "Return date - Day of Week",
                            description: "Generic Day of the Week (D1-D7)",
                            attribute: {
                                identifier: "return_date.dayOfWeek",
                                type: "attribute",
                            },
                            production: true,
                            deprecated: false,
                            unlisted: false,
                        },
                    ],
                    production: true,
                    deprecated: false,
                    unlisted: false,
                },
                defaultDisplayForm: {
                    type: "displayForm",
                    ref: {
                        identifier: "return_date.dayOfWeek",
                        type: "displayForm",
                    },
                    id: "return_date.dayOfWeek",
                    uri: "/api/v1/entities/workspaces/cef8d39392784675852790d4d1df14fc/labels/return_date.dayOfWeek",
                    title: "Return date - Day of Week",
                    description: "Generic Day of the Week (D1-D7)",
                    attribute: {
                        identifier: "return_date.dayOfWeek",
                        type: "attribute",
                    },
                    production: true,
                    deprecated: false,
                    unlisted: false,
                },
            },
            {
                granularity: "GDC.time.day_in_year",
                attribute: {
                    type: "attribute",
                    ref: {
                        identifier: "return_date.dayOfYear",
                        type: "attribute",
                    },
                    id: "return_date.dayOfYear",
                    uri: "/api/v1/entities/workspaces/cef8d39392784675852790d4d1df14fc/attributes/return_date.dayOfYear",
                    title: "Return date - Day of Year",
                    description: "Generic Day of the Year (D1-D366)",
                    displayForms: [
                        {
                            type: "displayForm",
                            ref: {
                                identifier: "return_date.dayOfYear",
                                type: "displayForm",
                            },
                            id: "return_date.dayOfYear",
                            uri: "/api/v1/entities/workspaces/cef8d39392784675852790d4d1df14fc/labels/return_date.dayOfYear",
                            title: "Return date - Day of Year",
                            description: "Generic Day of the Year (D1-D366)",
                            attribute: {
                                identifier: "return_date.dayOfYear",
                                type: "attribute",
                            },
                            production: true,
                            deprecated: false,
                            unlisted: false,
                        },
                    ],
                    production: true,
                    deprecated: false,
                    unlisted: false,
                },
                defaultDisplayForm: {
                    type: "displayForm",
                    ref: {
                        identifier: "return_date.dayOfYear",
                        type: "displayForm",
                    },
                    id: "return_date.dayOfYear",
                    uri: "/api/v1/entities/workspaces/cef8d39392784675852790d4d1df14fc/labels/return_date.dayOfYear",
                    title: "Return date - Day of Year",
                    description: "Generic Day of the Year (D1-D366)",
                    attribute: {
                        identifier: "return_date.dayOfYear",
                        type: "attribute",
                    },
                    production: true,
                    deprecated: false,
                    unlisted: false,
                },
            },
            {
                granularity: "GDC.time.hour",
                attribute: {
                    type: "attribute",
                    ref: {
                        identifier: "return_date.hour",
                        type: "attribute",
                    },
                    id: "return_date.hour",
                    uri: "/api/v1/entities/workspaces/cef8d39392784675852790d4d1df14fc/attributes/return_date.hour",
                    title: "Return date - Hour",
                    description: "Hour",
                    displayForms: [
                        {
                            type: "displayForm",
                            ref: {
                                identifier: "return_date.hour",
                                type: "displayForm",
                            },
                            id: "return_date.hour",
                            uri: "/api/v1/entities/workspaces/cef8d39392784675852790d4d1df14fc/labels/return_date.hour",
                            title: "Return date - Hour",
                            description: "Hour",
                            attribute: {
                                identifier: "return_date.hour",
                                type: "attribute",
                            },
                            production: true,
                            deprecated: false,
                            unlisted: false,
                        },
                    ],
                    production: true,
                    deprecated: false,
                    unlisted: false,
                },
                defaultDisplayForm: {
                    type: "displayForm",
                    ref: {
                        identifier: "return_date.hour",
                        type: "displayForm",
                    },
                    id: "return_date.hour",
                    uri: "/api/v1/entities/workspaces/cef8d39392784675852790d4d1df14fc/labels/return_date.hour",
                    title: "Return date - Hour",
                    description: "Hour",
                    attribute: {
                        identifier: "return_date.hour",
                        type: "attribute",
                    },
                    production: true,
                    deprecated: false,
                    unlisted: false,
                },
            },
            {
                granularity: "GDC.time.hour_in_day",
                attribute: {
                    type: "attribute",
                    ref: {
                        identifier: "return_date.hourOfDay",
                        type: "attribute",
                    },
                    id: "return_date.hourOfDay",
                    uri: "/api/v1/entities/workspaces/cef8d39392784675852790d4d1df14fc/attributes/return_date.hourOfDay",
                    title: "Return date - Hour of Day",
                    description: "Generic Hour of the Day(H1-H24)",
                    displayForms: [
                        {
                            type: "displayForm",
                            ref: {
                                identifier: "return_date.hourOfDay",
                                type: "displayForm",
                            },
                            id: "return_date.hourOfDay",
                            uri: "/api/v1/entities/workspaces/cef8d39392784675852790d4d1df14fc/labels/return_date.hourOfDay",
                            title: "Return date - Hour of Day",
                            description: "Generic Hour of the Day(H1-H24)",
                            attribute: {
                                identifier: "return_date.hourOfDay",
                                type: "attribute",
                            },
                            production: true,
                            deprecated: false,
                            unlisted: false,
                        },
                    ],
                    production: true,
                    deprecated: false,
                    unlisted: false,
                },
                defaultDisplayForm: {
                    type: "displayForm",
                    ref: {
                        identifier: "return_date.hourOfDay",
                        type: "displayForm",
                    },
                    id: "return_date.hourOfDay",
                    uri: "/api/v1/entities/workspaces/cef8d39392784675852790d4d1df14fc/labels/return_date.hourOfDay",
                    title: "Return date - Hour of Day",
                    description: "Generic Hour of the Day(H1-H24)",
                    attribute: {
                        identifier: "return_date.hourOfDay",
                        type: "attribute",
                    },
                    production: true,
                    deprecated: false,
                    unlisted: false,
                },
            },
            {
                granularity: "GDC.time.minute",
                attribute: {
                    type: "attribute",
                    ref: {
                        identifier: "return_date.minute",
                        type: "attribute",
                    },
                    id: "return_date.minute",
                    uri: "/api/v1/entities/workspaces/cef8d39392784675852790d4d1df14fc/attributes/return_date.minute",
                    title: "Return date - Minute",
                    description: "Minute",
                    displayForms: [
                        {
                            type: "displayForm",
                            ref: {
                                identifier: "return_date.minute",
                                type: "displayForm",
                            },
                            id: "return_date.minute",
                            uri: "/api/v1/entities/workspaces/cef8d39392784675852790d4d1df14fc/labels/return_date.minute",
                            title: "Return date - Minute",
                            description: "Minute",
                            attribute: {
                                identifier: "return_date.minute",
                                type: "attribute",
                            },
                            production: true,
                            deprecated: false,
                            unlisted: false,
                        },
                    ],
                    production: true,
                    deprecated: false,
                    unlisted: false,
                },
                defaultDisplayForm: {
                    type: "displayForm",
                    ref: {
                        identifier: "return_date.minute",
                        type: "displayForm",
                    },
                    id: "return_date.minute",
                    uri: "/api/v1/entities/workspaces/cef8d39392784675852790d4d1df14fc/labels/return_date.minute",
                    title: "Return date - Minute",
                    description: "Minute",
                    attribute: {
                        identifier: "return_date.minute",
                        type: "attribute",
                    },
                    production: true,
                    deprecated: false,
                    unlisted: false,
                },
            },
            {
                granularity: "GDC.time.minute_in_hour",
                attribute: {
                    type: "attribute",
                    ref: {
                        identifier: "return_date.minuteOfHour",
                        type: "attribute",
                    },
                    id: "return_date.minuteOfHour",
                    uri: "/api/v1/entities/workspaces/cef8d39392784675852790d4d1df14fc/attributes/return_date.minuteOfHour",
                    title: "Return date - Minute of Hour",
                    description: "Generic Minute of the Hour(MI1-MI60)",
                    displayForms: [
                        {
                            type: "displayForm",
                            ref: {
                                identifier: "return_date.minuteOfHour",
                                type: "displayForm",
                            },
                            id: "return_date.minuteOfHour",
                            uri: "/api/v1/entities/workspaces/cef8d39392784675852790d4d1df14fc/labels/return_date.minuteOfHour",
                            title: "Return date - Minute of Hour",
                            description: "Generic Minute of the Hour(MI1-MI60)",
                            attribute: {
                                identifier: "return_date.minuteOfHour",
                                type: "attribute",
                            },
                            production: true,
                            deprecated: false,
                            unlisted: false,
                        },
                    ],
                    production: true,
                    deprecated: false,
                    unlisted: false,
                },
                defaultDisplayForm: {
                    type: "displayForm",
                    ref: {
                        identifier: "return_date.minuteOfHour",
                        type: "displayForm",
                    },
                    id: "return_date.minuteOfHour",
                    uri: "/api/v1/entities/workspaces/cef8d39392784675852790d4d1df14fc/labels/return_date.minuteOfHour",
                    title: "Return date - Minute of Hour",
                    description: "Generic Minute of the Hour(MI1-MI60)",
                    attribute: {
                        identifier: "return_date.minuteOfHour",
                        type: "attribute",
                    },
                    production: true,
                    deprecated: false,
                    unlisted: false,
                },
            },
            {
                granularity: "GDC.time.month",
                attribute: {
                    type: "attribute",
                    ref: {
                        identifier: "return_date.month",
                        type: "attribute",
                    },
                    id: "return_date.month",
                    uri: "/api/v1/entities/workspaces/cef8d39392784675852790d4d1df14fc/attributes/return_date.month",
                    title: "Return date - Month/Year",
                    description: "Month and Year (12/2020)",
                    displayForms: [
                        {
                            type: "displayForm",
                            ref: {
                                identifier: "return_date.month",
                                type: "displayForm",
                            },
                            id: "return_date.month",
                            uri: "/api/v1/entities/workspaces/cef8d39392784675852790d4d1df14fc/labels/return_date.month",
                            title: "Return date - Month/Year",
                            description: "Month and Year (12/2020)",
                            attribute: {
                                identifier: "return_date.month",
                                type: "attribute",
                            },
                            production: true,
                            deprecated: false,
                            unlisted: false,
                        },
                    ],
                    production: true,
                    deprecated: false,
                    unlisted: false,
                },
                defaultDisplayForm: {
                    type: "displayForm",
                    ref: {
                        identifier: "return_date.month",
                        type: "displayForm",
                    },
                    id: "return_date.month",
                    uri: "/api/v1/entities/workspaces/cef8d39392784675852790d4d1df14fc/labels/return_date.month",
                    title: "Return date - Month/Year",
                    description: "Month and Year (12/2020)",
                    attribute: {
                        identifier: "return_date.month",
                        type: "attribute",
                    },
                    production: true,
                    deprecated: false,
                    unlisted: false,
                },
            },
            {
                granularity: "GDC.time.month_in_year",
                attribute: {
                    type: "attribute",
                    ref: {
                        identifier: "return_date.monthOfYear",
                        type: "attribute",
                    },
                    id: "return_date.monthOfYear",
                    uri: "/api/v1/entities/workspaces/cef8d39392784675852790d4d1df14fc/attributes/return_date.monthOfYear",
                    title: "Return date - Month of Year",
                    description: "Generic Month (M1-M12)",
                    displayForms: [
                        {
                            type: "displayForm",
                            ref: {
                                identifier: "return_date.monthOfYear",
                                type: "displayForm",
                            },
                            id: "return_date.monthOfYear",
                            uri: "/api/v1/entities/workspaces/cef8d39392784675852790d4d1df14fc/labels/return_date.monthOfYear",
                            title: "Return date - Month of Year",
                            description: "Generic Month (M1-M12)",
                            attribute: {
                                identifier: "return_date.monthOfYear",
                                type: "attribute",
                            },
                            production: true,
                            deprecated: false,
                            unlisted: false,
                        },
                    ],
                    production: true,
                    deprecated: false,
                    unlisted: false,
                },
                defaultDisplayForm: {
                    type: "displayForm",
                    ref: {
                        identifier: "return_date.monthOfYear",
                        type: "displayForm",
                    },
                    id: "return_date.monthOfYear",
                    uri: "/api/v1/entities/workspaces/cef8d39392784675852790d4d1df14fc/labels/return_date.monthOfYear",
                    title: "Return date - Month of Year",
                    description: "Generic Month (M1-M12)",
                    attribute: {
                        identifier: "return_date.monthOfYear",
                        type: "attribute",
                    },
                    production: true,
                    deprecated: false,
                    unlisted: false,
                },
            },
            {
                granularity: "GDC.time.quarter",
                attribute: {
                    type: "attribute",
                    ref: {
                        identifier: "return_date.quarter",
                        type: "attribute",
                    },
                    id: "return_date.quarter",
                    uri: "/api/v1/entities/workspaces/cef8d39392784675852790d4d1df14fc/attributes/return_date.quarter",
                    title: "Return date - Quarter/Year",
                    description: "Quarter and Year (Q1/2020)",
                    displayForms: [
                        {
                            type: "displayForm",
                            ref: {
                                identifier: "return_date.quarter",
                                type: "displayForm",
                            },
                            id: "return_date.quarter",
                            uri: "/api/v1/entities/workspaces/cef8d39392784675852790d4d1df14fc/labels/return_date.quarter",
                            title: "Return date - Quarter/Year",
                            description: "Quarter and Year (Q1/2020)",
                            attribute: {
                                identifier: "return_date.quarter",
                                type: "attribute",
                            },
                            production: true,
                            deprecated: false,
                            unlisted: false,
                        },
                    ],
                    production: true,
                    deprecated: false,
                    unlisted: false,
                },
                defaultDisplayForm: {
                    type: "displayForm",
                    ref: {
                        identifier: "return_date.quarter",
                        type: "displayForm",
                    },
                    id: "return_date.quarter",
                    uri: "/api/v1/entities/workspaces/cef8d39392784675852790d4d1df14fc/labels/return_date.quarter",
                    title: "Return date - Quarter/Year",
                    description: "Quarter and Year (Q1/2020)",
                    attribute: {
                        identifier: "return_date.quarter",
                        type: "attribute",
                    },
                    production: true,
                    deprecated: false,
                    unlisted: false,
                },
            },
            {
                granularity: "GDC.time.quarter_in_year",
                attribute: {
                    type: "attribute",
                    ref: {
                        identifier: "return_date.quarterOfYear",
                        type: "attribute",
                    },
                    id: "return_date.quarterOfYear",
                    uri: "/api/v1/entities/workspaces/cef8d39392784675852790d4d1df14fc/attributes/return_date.quarterOfYear",
                    title: "Return date - Quarter of Year",
                    description: "Generic Quarter (Q1-Q4)",
                    displayForms: [
                        {
                            type: "displayForm",
                            ref: {
                                identifier: "return_date.quarterOfYear",
                                type: "displayForm",
                            },
                            id: "return_date.quarterOfYear",
                            uri: "/api/v1/entities/workspaces/cef8d39392784675852790d4d1df14fc/labels/return_date.quarterOfYear",
                            title: "Return date - Quarter of Year",
                            description: "Generic Quarter (Q1-Q4)",
                            attribute: {
                                identifier: "return_date.quarterOfYear",
                                type: "attribute",
                            },
                            production: true,
                            deprecated: false,
                            unlisted: false,
                        },
                    ],
                    production: true,
                    deprecated: false,
                    unlisted: false,
                },
                defaultDisplayForm: {
                    type: "displayForm",
                    ref: {
                        identifier: "return_date.quarterOfYear",
                        type: "displayForm",
                    },
                    id: "return_date.quarterOfYear",
                    uri: "/api/v1/entities/workspaces/cef8d39392784675852790d4d1df14fc/labels/return_date.quarterOfYear",
                    title: "Return date - Quarter of Year",
                    description: "Generic Quarter (Q1-Q4)",
                    attribute: {
                        identifier: "return_date.quarterOfYear",
                        type: "attribute",
                    },
                    production: true,
                    deprecated: false,
                    unlisted: false,
                },
            },
            {
                granularity: "GDC.time.week_us",
                attribute: {
                    type: "attribute",
                    ref: {
                        identifier: "return_date.week",
                        type: "attribute",
                    },
                    id: "return_date.week",
                    uri: "/api/v1/entities/workspaces/cef8d39392784675852790d4d1df14fc/attributes/return_date.week",
                    title: "Return date - Week/Year",
                    description: "Week and Year (W52/2020)",
                    displayForms: [
                        {
                            type: "displayForm",
                            ref: {
                                identifier: "return_date.week",
                                type: "displayForm",
                            },
                            id: "return_date.week",
                            uri: "/api/v1/entities/workspaces/cef8d39392784675852790d4d1df14fc/labels/return_date.week",
                            title: "Return date - Week/Year",
                            description: "Week and Year (W52/2020)",
                            attribute: {
                                identifier: "return_date.week",
                                type: "attribute",
                            },
                            production: true,
                            deprecated: false,
                            unlisted: false,
                        },
                    ],
                    production: true,
                    deprecated: false,
                    unlisted: false,
                },
                defaultDisplayForm: {
                    type: "displayForm",
                    ref: {
                        identifier: "return_date.week",
                        type: "displayForm",
                    },
                    id: "return_date.week",
                    uri: "/api/v1/entities/workspaces/cef8d39392784675852790d4d1df14fc/labels/return_date.week",
                    title: "Return date - Week/Year",
                    description: "Week and Year (W52/2020)",
                    attribute: {
                        identifier: "return_date.week",
                        type: "attribute",
                    },
                    production: true,
                    deprecated: false,
                    unlisted: false,
                },
            },
            {
                granularity: "GDC.time.week_in_year",
                attribute: {
                    type: "attribute",
                    ref: {
                        identifier: "return_date.weekOfYear",
                        type: "attribute",
                    },
                    id: "return_date.weekOfYear",
                    uri: "/api/v1/entities/workspaces/cef8d39392784675852790d4d1df14fc/attributes/return_date.weekOfYear",
                    title: "Return date - Week of Year",
                    description: "Generic Week (W1-W53)",
                    displayForms: [
                        {
                            type: "displayForm",
                            ref: {
                                identifier: "return_date.weekOfYear",
                                type: "displayForm",
                            },
                            id: "return_date.weekOfYear",
                            uri: "/api/v1/entities/workspaces/cef8d39392784675852790d4d1df14fc/labels/return_date.weekOfYear",
                            title: "Return date - Week of Year",
                            description: "Generic Week (W1-W53)",
                            attribute: {
                                identifier: "return_date.weekOfYear",
                                type: "attribute",
                            },
                            production: true,
                            deprecated: false,
                            unlisted: false,
                        },
                    ],
                    production: true,
                    deprecated: false,
                    unlisted: false,
                },
                defaultDisplayForm: {
                    type: "displayForm",
                    ref: {
                        identifier: "return_date.weekOfYear",
                        type: "displayForm",
                    },
                    id: "return_date.weekOfYear",
                    uri: "/api/v1/entities/workspaces/cef8d39392784675852790d4d1df14fc/labels/return_date.weekOfYear",
                    title: "Return date - Week of Year",
                    description: "Generic Week (W1-W53)",
                    attribute: {
                        identifier: "return_date.weekOfYear",
                        type: "attribute",
                    },
                    production: true,
                    deprecated: false,
                    unlisted: false,
                },
            },
            {
                granularity: "GDC.time.year",
                attribute: {
                    type: "attribute",
                    ref: {
                        identifier: "return_date.year",
                        type: "attribute",
                    },
                    id: "return_date.year",
                    uri: "/api/v1/entities/workspaces/cef8d39392784675852790d4d1df14fc/attributes/return_date.year",
                    title: "Return date - Year",
                    description: "Year",
                    displayForms: [
                        {
                            type: "displayForm",
                            ref: {
                                identifier: "return_date.year",
                                type: "displayForm",
                            },
                            id: "return_date.year",
                            uri: "/api/v1/entities/workspaces/cef8d39392784675852790d4d1df14fc/labels/return_date.year",
                            title: "Return date - Year",
                            description: "Year",
                            attribute: {
                                identifier: "return_date.year",
                                type: "attribute",
                            },
                            production: true,
                            deprecated: false,
                            unlisted: false,
                        },
                    ],
                    production: true,
                    deprecated: false,
                    unlisted: false,
                },
                defaultDisplayForm: {
                    type: "displayForm",
                    ref: {
                        identifier: "return_date.year",
                        type: "displayForm",
                    },
                    id: "return_date.year",
                    uri: "/api/v1/entities/workspaces/cef8d39392784675852790d4d1df14fc/labels/return_date.year",
                    title: "Return date - Year",
                    description: "Year",
                    attribute: {
                        identifier: "return_date.year",
                        type: "attribute",
                    },
                    production: true,
                    deprecated: false,
                    unlisted: false,
                },
            },
        ],
    },
];
