// (C) 2026 GoodData Corporation

import { isEmpty } from "lodash-es";

import { type FilterContextItem, type IDashboardFilterReference } from "../dashboard/filterContext.js";
import { type VisualizationProperties } from "../insight/index.js";
import { type ObjRef } from "../objRef/index.js";

import {
    DefaultReportHeadingType,
    DefaultReportParagraphType,
    type IReportHeadingStyle,
    type IReportImageStyle,
    type IReportParagraphStyle,
    ReportHeadingTypes,
    ReportParagraphTypes,
    type ReportTextType,
    isReportHeadingType,
    isReportParagraphType,
} from "./styling.js";

/**
 * Metadata of a slot that is intentionally left unfilled in a report page or template.
 *
 * @alpha
 */
export interface IReportSlotPlaceholder {
    /**
     * Authoring hint shown in the empty slot.
     */
    hint?: string;

    /**
     * When true, a report is not considered complete until this slot is filled.
     */
    required?: boolean;
}

/**
 * Structural base of every report slot.
 *
 * @remarks
 * Parsers written against this base can skip slot types introduced by a newer
 * content version instead of failing.
 *
 * @alpha
 */
export interface IReportSlotBase {
    type: string;

    /**
     * Identifier unique within the page body. The layout tree references it, and it is
     * the join key when a report fills a template's slots. Regenerated when a page is
     * cloned into template content so repeated use of one page stays unique.
     */
    localIdentifier: string;

    /**
     * Present when the slot is an unfilled placeholder.
     */
    placeholder?: IReportSlotPlaceholder;
}

/**
 * Slot rendering an insight, with its own filter context.
 *
 * @alpha
 */
export interface IReportVisualizationSlot extends IReportSlotBase {
    type: "visualization";

    /**
     * Insight to render. Undefined = declared-but-empty slot; renderers show a placeholder.
     */
    insight?: ObjRef;

    /**
     * Optional title rendered above the visualization. Supports `{variables}`.
     */
    title?: string;

    showTitle?: boolean;

    /**
     * Visualization properties overriding the insight's own.
     */
    properties?: VisualizationProperties;

    /**
     * Slot-level filters, applied on top of the effective content and page filters.
     * A slot filter targeting the same object replaces the inherited one.
     */
    filters?: FilterContextItem[];

    /**
     * Content- and page-level filters this slot ignores (matched by display form / date dataset).
     */
    ignoredFilters?: IDashboardFilterReference[];

    /**
     * Date dataset the report's period (periodStart/periodEnd) is applied to as an
     * absolute date filter at execution time. Undefined = backend date-dataset
     * auto-resolution applies.
     */
    dateDataSet?: ObjRef;

    /**
     * When true, the implicit date filter derived from the report's period is not
     * applied to this slot.
     */
    ignoreReportPeriod?: boolean;
}

/**
 * Author-written text.
 *
 * @alpha
 */
export interface IReportStaticTextSource {
    type: "static";

    /**
     * Markdown content with `{variable}` placeholders. Stored raw — placeholders are
     * resolved only at render/export time.
     */
    content: string;
}

/**
 * Text generated by AI at report-build time.
 *
 * @alpha
 */
export interface IReportAiTextSource {
    type: "ai";

    /**
     * Instruction for the generator. Supports `{variables}`.
     */
    prompt: string;

    /**
     * Materialized generation result (markdown), stored so the report renders
     * deterministically without re-invoking AI. Absent until first generation.
     */
    content?: string;

    /**
     * ISO 8601 timestamp of the stored generation.
     */
    generatedAt?: string;
}

/**
 * Where the text of a text slot comes from.
 *
 * @alpha
 */
export type ReportTextSource = IReportStaticTextSource | IReportAiTextSource;

/**
 * Slot rendering a heading.
 *
 * @remarks
 * A heading is a line of display text, so it carries no markup of its own: what is typed in it is
 * what it renders.
 *
 * @alpha
 */
export interface IReportHeadingSlot extends IReportSlotBase {
    type: "heading";

    style?: IReportHeadingStyle;

    /**
     * Undefined = declared-but-empty slot.
     */
    source?: ReportTextSource;
}

/**
 * Slot rendering prose, written as markdown.
 *
 * @alpha
 */
export interface IReportParagraphSlot extends IReportSlotBase {
    type: "paragraph";

    style?: IReportParagraphStyle;

    /**
     * Undefined = declared-but-empty slot.
     */
    source?: ReportTextSource;
}

/**
 * Slot rendering text of either kind.
 *
 * @alpha
 */
export type IReportTextSlot = IReportHeadingSlot | IReportParagraphSlot;

/**
 * What an image slot displays.
 *
 * @alpha
 */
export type ReportImageSource =
    | {
          type: "url";

          /**
           * Image URL. Supports `{variables}` — a logo slot uses `{logo}`.
           */
          url: string;
      }
    | {
          type: "asset";

          /**
           * Reference to a backend-managed asset.
           */
          ref: ObjRef;
      };

/**
 * How an image is fitted to the area it is drawn in: kept whole inside it, filling it and cropped to
 * do so, or stretched to its shape.
 *
 * @alpha
 */
export type ReportImageFit = "contain" | "cover" | "fill";

/**
 * Slot rendering an image.
 *
 * @alpha
 */
export interface IReportImageSlot extends IReportSlotBase {
    type: "image";

    /**
     * Undefined = declared-but-empty slot.
     */
    source?: ReportImageSource;

    altText?: string;

    /**
     * How the image fills the slot area. Defaults to "contain".
     */
    fit?: ReportImageFit;

    /**
     * Placement overrides for the drawn image; centered on both axes by default.
     */
    style?: IReportImageStyle;
}

/**
 * All slot types of report content version 1.
 *
 * @alpha
 */
export type ReportSlot = IReportVisualizationSlot | IReportTextSlot | IReportImageSlot;

/**
 * List of built-in report slot type names.
 *
 * @alpha
 */
export const BuiltInReportSlotTypes: string[] = ["visualization", "heading", "paragraph", "image"];

/**
 * All sizes a text slot can be rendered at, headings first.
 *
 * @alpha
 */
export const ReportTextTypes: ReportTextType[] = [...ReportHeadingTypes, ...ReportParagraphTypes];

/**
 * Sizes the slot can be rendered at, which is what its own type decides.
 *
 * @alpha
 */
export function reportTextSlotTypes(slot: IReportTextSlot): ReportTextType[] {
    return slot.type === "heading" ? ReportHeadingTypes : ReportParagraphTypes;
}

/**
 * Size the slot is rendered at.
 *
 * @remarks
 * A slot states its size, and content is an open format: a size the slot cannot carry, and a size
 * from a newer version, both fall back to the default of the slot's own type.
 *
 * @alpha
 */
export function reportTextSlotType(slot: IReportTextSlot): ReportTextType {
    const stated = slot.style?.type;
    if (slot.type === "heading") {
        return isReportHeadingType(stated) ? stated : DefaultReportHeadingType;
    }
    return isReportParagraphType(stated) ? stated : DefaultReportParagraphType;
}

/**
 * Type-guard testing whether the provided object is an instance of {@link IReportVisualizationSlot}.
 *
 * @alpha
 */
export function isReportVisualizationSlot(obj: unknown): obj is IReportVisualizationSlot {
    return !isEmpty(obj) && (obj as IReportVisualizationSlot).type === "visualization";
}

/**
 * Type-guard testing whether the provided object is an instance of {@link IReportHeadingSlot}.
 *
 * @alpha
 */
export function isReportHeadingSlot(obj: unknown): obj is IReportHeadingSlot {
    return !isEmpty(obj) && (obj as IReportHeadingSlot).type === "heading";
}

/**
 * Type-guard testing whether the provided object is an instance of {@link IReportParagraphSlot}.
 *
 * @alpha
 */
export function isReportParagraphSlot(obj: unknown): obj is IReportParagraphSlot {
    return !isEmpty(obj) && (obj as IReportParagraphSlot).type === "paragraph";
}

/**
 * Type-guard testing whether the provided object is an instance of {@link IReportTextSlot}.
 *
 * @alpha
 */
export function isReportTextSlot(obj: unknown): obj is IReportTextSlot {
    return isReportHeadingSlot(obj) || isReportParagraphSlot(obj);
}

/**
 * Type-guard testing whether the provided object is an instance of {@link IReportImageSlot}.
 *
 * @alpha
 */
export function isReportImageSlot(obj: unknown): obj is IReportImageSlot {
    return !isEmpty(obj) && (obj as IReportImageSlot).type === "image";
}

/**
 * Type-guard testing whether the provided object is an instance of {@link ReportSlot}.
 *
 * @alpha
 */
export function isReportSlot(obj: unknown): obj is ReportSlot {
    return [isReportVisualizationSlot, isReportTextSlot, isReportImageSlot].some((guard) => guard(obj));
}
