name: check-approve

on:
  pull_request_review:
    types:
      - submitted
      - dismissed

concurrency:
  group: check-approve-${{ github.event.pull_request.number }}
  cancel-in-progress: true

jobs:
  detect-changes:
    if: ${{ github.event.review.state == 'approved' }}
    secrets: inherit
    permissions:
      contents: write
      id-token: write
    uses: ./.github/workflows/rw-rush-detect-changes.yml
    with:
      source-branch: ${{ github.event.pull_request.head.sha }}
      target-branch: ${{ github.event.pull_request.base.ref }}
      package-name: "@gooddata/sdk-ui-tests-e2e"

  e2e-stage:
    needs: [detect-changes]
    if: ${{ needs.detect-changes.outputs.is-changed == 'true' }}
    permissions:
      id-token: write
      contents: read
      pull-requests: read
    name: e2e-stage
    uses: ./.github/workflows/rw-rush-build-e2e-tests.yml
    with:
      source-ref: ${{ github.event.pull_request.merge_commit_sha }}
    secrets: inherit

  ready-to-merge-approved:
    runs-on:
      group: infra1-runners-arc
      labels: runners-small
    if: ${{ github.event.review.state == 'approved' && !cancelled() }}
    needs:
      - e2e-stage
    steps:
      - name: Check if needed jobs succeeded
        uses: re-actors/alls-green@release/v1
        with:
          allowed-skips: ${{ toJSON(needs) }}
          jobs: ${{ toJSON(needs) }}

  notify-sync-pr-check-failed:
    runs-on:
      group: infra1-runners-arc
      labels: runners-small
    if: ${{ always() && needs.ready-to-merge-approved.result == 'failure' && contains(github.event.pull_request.labels.*.name, 'sync') }}
    needs:
      - ready-to-merge-approved
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          repository: ${{ inputs.githubuser }}/gdc-ui
          token: ${{ secrets.TOKEN_GITHUB_YENKINS}}
      - name: Notify sync PR check failure
        uses: ./.github/actions/slack/send-notification
        with:
          message: |
            :warning: Automated sync PR from gdc-ui failed checks in gooddata-ui-sdk
            
            PR: #${{ github.event.pull_request.number }} - ${{ github.event.pull_request.title }}
            
            Check the PR: ${{ github.event.pull_request.html_url }}
          slack-bot-token: ${{ secrets.SLACK_BOT_TOKEN }}
