name: Doc ~ Netlify Deploy
on:
  workflow_dispatch:

jobs:
  release-ui-sdk-examples-deploy:
    secrets: inherit
    permissions:
      contents: write
      id-token: write
    uses: ./.github/workflows/rw-rush-build-basic-checks.yml
    with:
      target-branch: "master"

