# (C) 2023 GoodData Corporation

name: get ecr docker credentials

on:
  workflow_call:
    outputs:
      ecr-docker-username:
        description: "docker username to login ecr"
        value: ${{ jobs.login-to-infra-ecr.outputs.docker_username }}
      ecr-docker-password:
        description: "docker password to login ecr"
        value: ${{ jobs.login-to-infra-ecr.outputs.docker_password }}

jobs:
  login-to-infra-ecr:
    runs-on: [infra1-small]
    permissions:
      id-token: write
    steps:
      - name: Get Vault secrets for ECR
        uses: hashicorp/vault-action@v2
        with:
          url: "https://vault.ord1.infra.intgdc.com"
          method: jwt
          path: jwt/github
          role: ecr-pull
          secrets: |
            secret/data/v2/data-special/infra1-user-ecr-ro aws_ecr_access_key | AWS_ACCESS_KEY ;
            secret/data/v2/data-special/infra1-user-ecr-ro aws_ecr_secret_key | AWS_SECRET_KEY ;
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ env.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ env.AWS_SECRET_KEY }}
          aws-region: us-east-1
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
    outputs:
      docker_username: ${{ steps.login-ecr.outputs.docker_username_020413372491_dkr_ecr_us_east_1_amazonaws_com }}
      docker_password: ${{ steps.login-ecr.outputs.docker_password_020413372491_dkr_ecr_us_east_1_amazonaws_com }}
