# (C) 2022 GoodData Corporation

name: Pull request ~ Commits validation

on:
    pull_request:
        types: [opened, edited, synchronize, reopened]

jobs:
    validate-commits:
        name: Commits validation
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v3
              with:
                  fetch-depth: 0
            - name: Set commit range variables
              run: |
                  echo "PR_HEAD=${{ github.event.pull_request.head.sha }}" >> $GITHUB_ENV
                  echo "PR_BASE=${{ github.event.pull_request.base.sha }}" >> $GITHUB_ENV
            - name: Check the pull request commit messages
              uses: ./.github/actions/check-pull-request-commits
              with:
                  pr_head: ${{ env.PR_HEAD }}
                  pr_base: ${{ env.PR_BASE }}
                  lint_config: ./.github/actions/check-pull-request-commits/commitlint.config.cjs
