# (C) 2024 GoodData Corporation

name: rw ~ Release ~ Release documentation for major/minor
on:
    workflow_call:

jobs:
    get-version:
        uses: ./.github/workflows/rw-bump-version.yml
        secrets: inherit
        permissions:
            contents: write
        with:
            skip-bump: true
            source-branch: 'release'

    update-apidocs-version:
        needs: [get-version]
        uses: ./.github/workflows/rw-doc-release-apidocs.yml
        permissions:
            contents: write
            id-token: write
        secrets: inherit
        with:
            source-branch: "release"
            version: ${{ needs.get-version.outputs.version }}
            is-new-latest: true

    publish-netlify:
        uses: ./.github/workflows/rw-doc-netlify-deploy.yml
        permissions:
            contents: write
            id-token: write
        secrets: inherit

    slack-notification:
        runs-on: [ubuntu-latest]
        needs: [publish-netlify, update-apidocs-version, get-version]
        steps:
          - name: Checkout repository
            uses: actions/checkout@v4
            with:
              token: ${{ secrets.TOKEN_GITHUB_YENKINS}}
          - name: Notify to slack
            uses: ./.github/actions/slack/send-notification
            with:
              message: "The documentation for ui sdk *${{ env.RELEASE_VERSION }}* was successfully released by *${{ env.GITHUB_USER }}*"
              slack-bot-token: ${{ secrets.SLACK_BOT_TOKEN }}
            env:
              RELEASE_VERSION: ${{ needs.get-version.outputs.version }}
              GITHUB_USER: ${{ github.actor }}
