name: rw ~ rush ~ build validate and run unit tests
on:
  workflow_call:
    inputs:
      target-branch:
          required: true
          description: "Target branch to compare with (marge into)"
          type: string


jobs:
  test:
    runs-on:
      ubuntu-latest
    steps:
      - name: Echo some test running
        run: echo "Running tests"
