name: rw ~ rush ~ e2e tests
on:
  workflow_call:
    inputs:
      filter:
          required: false
          description: "List of spec files to filter"
          type: string
      source-ref:
          required: false
          description: "source ref of the current code"
          type: string

jobs:
  warm-up-cache:
    runs-on:
      group: infra1-runners-arc
      labels: runners-cxa-xlarge
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ inputs.source-ref }}
          fetch-depth: 2

      - name: Git config user
        uses: snow-actions/git-config-user@v1.0.0
        with:
          name: git-action
          email: git-action@gooddata.com
      - name: Warmup rush
        env:
          NPM_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        uses: ./.github/actions/rush/warm-up-rush
  build:
    needs: [warm-up-cache]
    runs-on:
      group: infra1-runners-arc
      labels: runners-rxa-xlarge
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ inputs.source-ref }}
          fetch-depth: 2
      - name: Debug
        run: git log -1
      - name: Git config user
        uses: snow-actions/git-config-user@v1.0.0
        with:
          name: git-action
          email: git-action@gooddata.com
      - name: Debug
        run: git log -1
      - name: Setup rush
        env:
          NPM_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        uses: ./.github/actions/rush/set-up-rush
      - name: Rush build
        run: node common/scripts/install-run-rush.js build --to @gooddata/sdk-ui-tests-e2e

  e2e-prepare-matrix:
    runs-on:
      group: infra1-runners-arc
      labels: runners-small
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
      count: ${{ steps.set-matrix.outputs.count }}
    steps:
      - id: set-matrix
        run: |
          if [ -n "$USER_FILTER" ]; then
            # only one runner when user provided filter
            echo "matrix=[\"runner1\"]" >> $GITHUB_OUTPUT
            echo "runners=1" >> $GITHUB_OUTPUT
          else
            # hardcode runners count
            COUNT=3
            MATRIX="["
            for i in $(seq 1 $COUNT); do
              if [ $i -ne 1 ]; then
                MATRIX+=", "
              fi
              MATRIX+="\"runner$i\""
            done
            MATRIX+="]"

            echo "Matrix for $COUNT: $MATRIX"
            echo "matrix=$MATRIX" >> $GITHUB_OUTPUT
            echo "count=$COUNT" >> $GITHUB_OUTPUT
          fi
    env:
      USER_FILTER: ${{ inputs.filter }}

  e2e:
    needs: [warm-up-cache,build,e2e-prepare-matrix]
    runs-on:
      group: infra1-runners-arc
      labels: runners-rxa-xlarge
    strategy:
      fail-fast: true
      matrix:
        runner: ${{fromJson(needs.e2e-prepare-matrix.outputs.matrix)}}
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ inputs.source-ref }}
          fetch-depth: 2
      - name: Git config user
        uses: snow-actions/git-config-user@v1.0.0
        with:
          name: git-action
          email: git-action@gooddata.com
      - name: Setup rush
        env:
          NPM_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        uses: ./.github/actions/rush/set-up-rush
      - name: Rush build
        run: |
          node common/scripts/install-run-rush.js build --to @gooddata/sdk-ui-tests-e2e
      - name: Rush generate dynamic files related to build
        run: node common/scripts/install-run-rush.js build-generate-version
      - name: Run e2e tests
        run: |
          export EXECUTOR_NUMBER=$GH_RUN_ID
          if [ -n "$USER_FILTER" ]; then
            export FILTER=$USER_FILTER
          else
            export FILTER=$(common/scripts/ci/get-tests-filter.sh sdk-ui-tests-e2e $RUNNER pre-merge_isolated_tiger $RUNNERS_COUNT)
          fi
          echo "Running with FILTER=$FILTER"
          ./common/scripts/ci/run_cypress_isolated_tests.sh
        env:
          GH_RUN_ID: ${{ github.run_id }}
          RUNNER: ${{ matrix.runner }}
          RUNNERS_COUNT: ${{ needs.e2e-prepare-matrix.outputs.count }}
          USER_FILTER: ${{ inputs.filter }}
      - name: Archive the cypress test artifacts
        uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: cypress-test-artifacts-${{matrix.runner}}
          path: |
            libs/sdk-ui-tests-e2e/cypress/videos/**/*.mp4
