name: rw ~ rush ~ build validate and run unit tests
on:
  workflow_call:

jobs:
  ######################################################
  # Warm up the cache pnmp and rush
  ######################################################
  warm-up-cache:
    runs-on:
      group: infra1-runners-arc
      labels: runners-cxa-xlarge
    steps:
      - uses: actions/checkout@v4
      - name: Git config user
        uses: snow-actions/git-config-user@v1.0.0
        with:
          name: git-action
          email: git-action@gooddata.com
      - name: Warmup rush
        env:
          NPM_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        uses: ./.github/actions/rush/warm-up-rush


