# (C) 2024 GoodData Corporation

name: Test ~ Backstop screen tests
on:
  workflow_dispatch:
    inputs:
      keep-passing-screenshots:
        description: Keep screenshots for passing tests
        type: boolean
        required: false
        default: false
  schedule:
    - cron: '0 4 * * 1-5'

jobs:
  e2e-backstop:
    permissions:
      id-token: write
      contents: read
      pull-requests: read
    uses: ./.github/workflows/rw-rush-build-e2e-tests-backstop.yml
    with:
      keep-passing-screenshots: ${{ github.event_name == 'workflow_dispatch' && inputs.keep-passing-screenshots || false }}
    secrets: inherit

  slack-notification:
    runs-on:
      group: infra1-runners-arc
      labels: runners-small
    if: ${{ !cancelled() }}
    needs: [e2e-backstop]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.TOKEN_GITHUB_YENKINS}}
      - name: Notify to slack
        uses: ./.github/actions/slack/send-notification
        with:
          message: "${{env.ICON}} The scheduled backstop tests for *gooddata-ui-sdk* dispatched by *${{env.DISPATCHED_BY}}* finished with result *${{env.TEST_RESULT_BACKSTOP}}*. Check the *<${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}|log here>*"
          slack-bot-token: ${{ secrets.SLACK_BOT_TOKEN }}
        env:
          TEST_RESULT_BACKSTOP: ${{ needs.e2e-backstop.result }}
          ICON: ${{ needs.e2e-backstop.result == 'success' && '✅' || '❌' }}
          DISPATCHED_BY: ${{ github.event_name == 'workflow_dispatch' && github.actor || 'cron scheduler' }}
