// (C) 2007-2018 GoodData Corporation
export const PIE_CHART_LIMIT = 20;
export const HEATMAP_DATA_POINTS_LIMIT = 10000;
export const SANKEY_CHART_NODE_LIMIT = 1000;
export const SANKEY_CHART_DATA_POINT_LIMIT = 60000;
export const WATERFALL_CHART_DATA_POINT_LIMIT = 400;
